/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
/* ------------------------------------------ */
/* FirstInterface.c                                  */
/*                                            */
/* This file was automaticly generated by     */
/* View Designer/X                            */
/*                                            */
/* ------------------------------------------ */


#include <stdio.h>

#include "FirstInterface.h"


/* Need toggle button functions */
#include <Xm/ToggleB.h>

extern FirstInterface *createFirstInterface_base(
#if NeedFunctionPrototypes
    	Widget,	ArgList, Cardinal
#endif
);




/* ------------------------------------------ */
/* Initialization function of this module     */
/*                                            */
/* If you want to create a popupShell         */
/* parent must be NULL, otherwise you create  */
/* a Frame                                    */
/* ------------------------------------------ */

FirstInterface *createFirstInterface(parent, args, n)
	Widget parent;
	ArgList args;
	Cardinal n;
{
  FirstInterface *self;

  self = createFirstInterface_base(parent,args,n);
  
  /* Set the amex a default
     last parameter is true, because we
     want to call value canged callback 
     */
  XmToggleButtonSetState(self->base.amex_toggle, TRUE, TRUE);

  return self;
}


/* ------------------------------------------ */
/* Impelemtation of your methods              */
/* ------------------------------------------ */

extern void printf_credit_card(self)
FirstInterface *self;
{
  switch(self->ccsel) {
  case AMEX_CARD:
    printf("American Express\n");
    break;
  case VISA_CARD:
    printf("Visa Card\n");
    break;
  case MASTER_CARD:
    printf("Master Card\n");
    break;
  }
}


/* ------------------------------------------ */
/* Method: cc_value_changed()                      */
/* ------------------------------------------ */

void cc_value_changed(self, wg, callData)
     FirstInterface *self;
     Widget wg;
     XtPointer callData;
{
  if(XmToggleButtonGetState(wg)) {    /* only the change to true */
    if(wg == self->base.amex_toggle) {
      self->ccsel = AMEX_CARD;
    } else if(wg == self->base.visa_toggle) {
      self->ccsel = VISA_CARD;
    } else if(wg == self->base.master_toggle) {
      self->ccsel = MASTER_CARD;
    }
  }
}





