/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
/* ------------------------------------------ */
/* FirstInterface.h                                  */
/*                                            */
/* This file was automaticly generated by     */
/* View Designer/X                            */ 
/*                                            */
/* ------------------------------------------ */

#ifndef _FirstInterface_H_
#define _FirstInterface_H_


/* Include the base module */

#include "FirstInterface_base.h"


typedef enum {
  AMEX_CARD,
  VISA_CARD,
  MASTER_CARD
} CreditCardSelection;


/* ------------------------------------------ */
/*                                            */
/* Edit the following structure to add        */
/* associated data                            */
/*                                            */
/* ------------------------------------------ */

typedef struct _FirstInterface {
  CreditCardSelection ccsel;
  FirstInterface_base base;             /* The widgets */
} FirstInterface;



extern void printf_credit_card(
#if NeedFunctionPrototypes
			       FirstInterface *
#endif
			       );

/* ------------------------------------------ */
/* initialization function of this module     */
/* ------------------------------------------ */

extern FirstInterface *createFirstInterface(
#if NeedFunctionPrototypes
	Widget,	ArgList, Cardinal
#endif
);


/* ------------------------------------------ */
/* Methods, you have to implement             */
/* ------------------------------------------ */

extern void cc_value_changed(
#if NeedFunctionPrototypes
    	FirstInterface*, Widget, XtPointer
#endif
);




#endif /* Don't add stuff after this #endif */
