/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
/* ----------------------------------------- */
/* FirstInterface_base.c                            */
/*                                           */
/* This file was automaticly generated by    */
/* View Designer/X                           */
/*                                           */
/* Don't edit this file, please!             */
/*                                           */
/* ----------------------------------------- */


/* Used in createWidgets() */

#define RES_CONVERT(t,s) cvtResourceFromString(parent, t, s)
  

/* Include the header files for Motif */

#include <stdlib.h>
#include <Xm/Frame.h>
#include <X11/Shell.h>
#include <Xm/RowColumn.h>
#include <Xm/ToggleB.h>






/* Include linked interfaces */




#include "FirstInterface_base.h"
#include "FirstInterface.h"
#include "vcmisc.h"


/* Forward declarations */

static void FirstInterface_createWidgets(
#if NeedFunctionPrototypes
	FirstInterface *self
#endif
);

static void FirstInterface_addCallbacks(
#if NeedFunctionPrototypes
	FirstInterface *self
#endif
);

static void FirstInterface_addRelations(
#if NeedFunctionPrototypes
	FirstInterface *self
#endif
);


/* ----------------------------------------- */
/* Forward declarations for methods          */
/* ----------------------------------------- */

static void cc_value_changed_CB(
#if NeedFunctionPrototypes
	Widget, 
	XtPointer, 
	XtPointer
#endif
);




/* ----------------------------------------- */
/* The initialization function of this       */
/* module                                    */
/* ----------------------------------------- */

FirstInterface *createFirstInterface_base(p, f_args, f_n)
	Widget p;
	ArgList f_args;
	Cardinal f_n;
{
	Widget parent;
	Arg args[100];
	Cardinal n = 0;
	FirstInterface *self;

	self = (FirstInterface*)XtMalloc(sizeof(FirstInterface));   	/* Allocate Memory */
	memset(self, 0, sizeof(FirstInterface));

	if(p)
		parent = p;
	else
		parent = getTopLevel();

	if(p) {                                 
		self->base.topWidget = self->base.FirstInterface = 
			XtCreateWidget("FirstInterface",xmFrameWidgetClass,
				       parent, f_args, f_n);
	} else {
	        

		self->base.topWidget = self->base.popupShell = self->base.FirstInterface = 
			XtCreatePopupShell("FirstInterface", topLevelShellWidgetClass,
			parent, args, n);
	}
	FirstInterface_createWidgets(self); 	/* create widgets               */
	FirstInterface_addCallbacks(self);	/* add callbacks                */
	FirstInterface_addRelations(self);	/* set resources of type widget */

	if(self->base.FirstInterface)		/* add callback to free memory  */
		XtAddCallback(self->base.FirstInterface, XmNdestroyCallback,
			      vcDestroyCallback, self);
	return self;
}



/* ----------------------------------------- */
/* Create widgets                            */
/* ----------------------------------------- */

static void FirstInterface_createWidgets(self)
FirstInterface *self;
{
  Widget parent;
  Arg args[100];
  Cardinal n;

  
  /* ---------- Creating Widget:    radioBox -------------- */
  parent = self->base.FirstInterface;

  /* Building resource list */
  n = 0;


  /* Creating Widget */
  self->base.radioBox = XmCreateRadioBox( parent, "radioBox", args, n);
  
  /* Manage the Widget */
  XtManageChild(self->base.radioBox);
  

  
  /* ---------- Creating Widget:    amex_toggle -------------- */
  parent = self->base.radioBox;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  self->base.amex_toggle = XtCreateWidget("amex_toggle", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(self->base.amex_toggle);
  

  
  /* ---------- Creating Widget:    visa_toggle -------------- */
  parent = self->base.radioBox;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  self->base.visa_toggle = XtCreateWidget("visa_toggle", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(self->base.visa_toggle);
  

  
  /* ---------- Creating Widget:    master_toggle -------------- */
  parent = self->base.radioBox;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  self->base.master_toggle = XtCreateWidget("master_toggle", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(self->base.master_toggle);
  


}



/* ----------------------------------------- */
/* Add Callbacks                             */
/* ----------------------------------------- */

static void FirstInterface_addCallbacks(self)
FirstInterface *self;
{

  XtAddCallback( self->base.amex_toggle, "valueChangedCallback",
                 cc_value_changed_CB, self);

  XtAddCallback( self->base.visa_toggle, "valueChangedCallback",
                 cc_value_changed_CB, self);

  XtAddCallback( self->base.master_toggle, "valueChangedCallback",
                 cc_value_changed_CB, self);

}



/* ----------------------------------------- */
/* Set resources of type widget              */
/* ----------------------------------------- */

void FirstInterface_addRelations(self)
FirstInterface *self;
{

}



/* ----------------------------------------- */
/* Now follows the callbacks                 */
/* ----------------------------------------- */


/* --------------------------------- */
/* cc_value_changed_CB()                    */
/* --------------------------------- */

static void cc_value_changed_CB(wg, clientData, callData)
    Widget wg;
    XtPointer clientData;
    XtPointer callData;
{
    /* Calling method which is implemented in FirstInterface.c */

    cc_value_changed((FirstInterface*)clientData, wg, callData);
}







