/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
/* ------------------------------------------ */
/* OrderWindow.c                              */
/*                                            */
/* This file was automaticly generated by     */
/* View Designer/X                            */
/*                                            */
/* ------------------------------------------ */


#include <stdio.h>

#include "OrderWindow.h"

/* needed for XmMessageBoxGetChild() */
#include <Xm/MessageB.h>

extern OrderWindow *createOrderWindow_base(
#if NeedFunctionPrototypes
    	Widget,	ArgList, Cardinal
#endif
);




/* ------------------------------------------ */
/* Initialization function of this module     */
/*                                            */
/* If you want to create a popupShell         */
/* parent must be NULL, otherwise you create  */
/* a Frame                                    */
/* ------------------------------------------ */

OrderWindow *createOrderWindow(parent, args, n)
	Widget parent;
	ArgList args;
	Cardinal n;
{
  OrderWindow *self;

  self = createOrderWindow_base(parent,args,n);

  /* We don't want the help and cancel button in helpDialog */

  XtUnmanageChild(XmMessageBoxGetChild(self->base.helpDialog, 
				       XmDIALOG_HELP_BUTTON));
  XtUnmanageChild(XmMessageBoxGetChild(self->base.helpDialog, 
				       XmDIALOG_CANCEL_BUTTON));

  return self;
}


/* ------------------------------------------ */
/* Impelemtation of your methods              */
/* ------------------------------------------ */


/* ------------------------------------------ */
/* Method: do_order()                      */
/* ------------------------------------------ */

void do_order(self, wg, callData)
     OrderWindow *self;
     Widget wg;
     XtPointer callData;
{
  printf("Your order: ");
  printf_product(self->base.product_link);
  printf("Your credit card: ");
  printf_credit_card(self->base.credit_card_link);
}


/* ------------------------------------------ */
/* Method: do_close()                      */
/* ------------------------------------------ */

void do_close(self, wg, callData)
     OrderWindow *self;
     Widget wg;
     XtPointer callData;
{
  printf("Bye!\n");
  exit(0);
}





