/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
/****************************************************************
 *
 *  $RCSfile: AttachmentEditor.C,v $
 *  $Date: 1999/08/27 15:30:40 $
 *  $Revision: 1.1.1.1.2.1 $
 *
 *  Copyright 1997, Dirk Laessig
 *  ALL RIGHTS RESERVED
 *  See the file Copyright for more information
 *
 *  Dirk Laessig
 *  Goettingstr. 5
 *  38106 Braunschweig
 *  Germany
 ****************************************************************/
/*
 * $Log: AttachmentEditor.C,v $
 * Revision 1.1.1.1.2.1  1999/08/27 15:30:40  dirk
 * Transform the copyright to GPL
 *
 * Revision 1.1.1.1  1998/04/24 23:45:16  lazy
 * Imported to CVS
 *
 * Revision 1.3  1998/03/30 19:07:48  lazy
 * *** empty log message ***
 *
 * Revision 1.2  1997/09/02  18:36:34  lazy
 * Browser default -> AttachmentEditor defaults
 *
 * Revision 1.1  1997/07/25  20:24:10  lazy
 * Initial revision
 *
 */

// ------------------------------ 
// AttachmentEditor.C                      
//
// This file was automaticly generated by
// View Designer/X v1.1.0
//
// User: lazy@apfel.goetting5
// Date: Sat Jun 21 13:02:30 1997
//
// ------------------------------

#include "AttachmentEditor.h"


#include "Lwidget.h"
#include "Lproperty.h"
#include "lic.h"
#include <lac/Controller.h>

#include <Xm/ToggleB.h>

RefArray<AttachmentEditor> AttachmentEditor::allViews;
Ref<AttachmentEditor> AttachmentEditor::automaticLoadView;

// ------------------------------
// AttachmentEditor()
// ------------------------------

AttachmentEditor::AttachmentEditor(Lwidget *lwidget)
: AttachmentEditor_base(NULL,NULL,0), selectionCallback(this),
  topWidgetView(topWidget),
  rightWidgetView(rightWidget),
  bottomWidgetView(bottomWidget),
  leftWidgetView(leftWidget)
{
  LicView::quickHelpLabel = quickHelpLabel;

  Selectable::selectionCallbacks.add(&selectionCallback);

  iconView = new WidgetIconView(lwidget, childrenFrame);
  iconView->setOneRow(TRUE);
  XtManageChild(iconView->getTop());
  allViews.add(this);

  setWidget(lwidget);
  setGeometryModel(app);

  selectionCallback.call();

  controllerImpl.add(editButton, LWIDGET_EDIT);
  controllerImpl.add(browseButton, LWIDGET_BROWSE);
  controllerImpl.add(menuEditButton, LWIDGET_MENUEDIT);
  controllerImpl.add(cutButton, LWIDGET_CUT);
  controllerImpl.add(copyButton, LWIDGET_COPY);
  controllerImpl.add(pasteButton, LWIDGET_PASTE);
  controllerImpl.add(deleteButton, LWIDGET_DELETE);

  XmToggleButtonSetState(automaticLoadButton, 
			 app->getAttachmentEditorAutomaticLoad(), TRUE);

  XmToggleButtonSetState(withClassNameButton, TRUE, FALSE);
  XmToggleButtonSetState(withClassNameButton, 
			 app->getAttachmentEditorWithClassName(), TRUE);

  XmToggleButtonSetState(smallIconButton, 
			 app->getAttachmentEditorSmallIcons(), TRUE);

  XmToggleButtonSetState(withIconButton, TRUE, FALSE);
  XmToggleButtonSetState(withIconButton, 
			 app->getAttachmentEditorWithIcons(), TRUE);
}

// ----------------------------
//      ~AttachmentEditor()
// ----------------------------
AttachmentEditor::~AttachmentEditor()
{
  if(!iconView.isNil())
    iconView.Delete();
  while(datas.getSize())
    datas[0].Delete();
}


// ------------------------------
// showView()
// ------------------------------

void
AttachmentEditor::showView(Lwidget *lwidget)
{
  ::AttachmentEditor *view = NULL;
  if(!isOfValidClass(lwidget)) {
    fprintf(stderr, "Fatal Error: AttachmentEditor::showView() called with invalid parameter.\n");
    return;
  }
  if(!automaticLoadView.isNil()) {
    view = automaticLoadView;
    view->setWidget(lwidget);
  } else {
    for(unsigned int i=0; i<allViews.getSize(); i++) {
      if(allViews[i]->model == lwidget) {
	view = allViews[i];
	break;
      }
    }
  }
  if(view == NULL) {
    view = new ::AttachmentEditor(lwidget);
  }
  view->open();
}


// ----------------------------
//      update()
// ----------------------------
void AttachmentEditor::update( unsigned long flags )
{
  if(flags & NAME_CHANGED) {
    char title[256];
    msgCat->getMsg(title, ATTACHMENT_EDITOR_TITLE, 
		   model->getName(), 
		   model->getClass()->getName() );
    XtVaSetValues(popupShell, 
		  XmNtitle, title,
		  XmNiconName, title,
		  NULL );
  }
  if(flags & CONTAINER_CHANGED) {
    selectionCallback.call();
  }
}

// ------------------------------
// isOfValidClass()
// ------------------------------

Boolean 
AttachmentEditor::isOfValidClass(Lwidget *lwidget)
{
  Lcreator *lclass;
  lclass = lwidget->getClass();
  if(lclass && !strcmp(lclass->getName(), "XmForm"))
    return True;
  return False;
}

// ------------------------------
// setWidget()
// ------------------------------

void 
AttachmentEditor::setWidget(Lwidget *m)
{
  while(datas.getSize())      // delete old datas
    datas[0].Delete();

  this->model = m;
  setModel(m);
  iconView->setModel(m);
  leftWidgetView.setContainer(m);
  rightWidgetView.setContainer(m);
  topWidgetView.setContainer(m);
  bottomWidgetView.setContainer(m);

  update(NAME_CHANGED);
}


// ------------------------------
// do_load()
// ------------------------------
void 
AttachmentEditor::do_load(Widget, XtPointer)
{
  RefArray<Selectable> selection(Selectable::getSelection());
  
  if(!strcmp(Selectable::getCurrentClass(), "Lwidget")
     && selection.getSize() > 0) {
    Lwidget *lwidget = (Lwidget*)(Selectable*)selection[0];
    if(isOfValidClass(lwidget))
      setWidget(lwidget);
  }
}


// ------------------------------
// do_apply()
// ------------------------------
void 
AttachmentEditor::do_apply(Widget, XtPointer)
{
  if(!currentData.isNil()) {
    readBottom();
    readTop();
    readLeft();
    readRight();
    readResizable();
  }
  for(unsigned int i=0; i<datas.getSize(); i++) {
    datas[i]->apply();
  }
  model->changed(RESOURCE_CHANGED);
}


// ------------------------------
// do_close()
// ------------------------------
void 
AttachmentEditor::do_close(Widget, XtPointer)
{
  close();
  delete this;
}


// ------------------------------
// do_smallIcon()
// ------------------------------
void 
AttachmentEditor::do_smallIcon(Widget wg, XtPointer)
{
  iconView->setWithSmallIcons(XmToggleButtonGetState(wg));
}


// ------------------------------
// do_withIcon()
// ------------------------------
void 
AttachmentEditor::do_withIcon(Widget wg, XtPointer)
{
  iconView->setWithIcons(XmToggleButtonGetState(wg));
}


// ------------------------------
// do_withClassName()
// ------------------------------
void 
AttachmentEditor::do_withClassName(Widget, XtPointer)
{
  iconView->setWithClasses(XmToggleButtonGetState(withClassNameButton));
}


// ------------------------------
// do_widgetMenuMap()
// ------------------------------
void 
AttachmentEditor::do_widgetMenuMap(Widget, XtPointer)
{
  controllerImpl.process(iconView);
}


// ------------------------------
// do_onHelp()
// ------------------------------
void 
AttachmentEditor::do_onHelp(Widget, XtPointer)
{
  getHelp(HID_USING_HELP);
}


// ------------------------------
// do_onContext()
// ------------------------------
void 
AttachmentEditor::do_onContext(Widget, XtPointer)
{
  contextHelp();
}


// ------------------------------
// do_help()
// ------------------------------
void 
AttachmentEditor::do_help(Widget wg, XtPointer)
{
  printf("Callback AttachmentEditor::do_help called by widget '%s'.\n",
         XtName(wg));
}


// ------------------------------
// do_automaticLoad()
// ------------------------------
void 
AttachmentEditor::do_automaticLoad(Widget, XtPointer)
{
  if(XmToggleButtonGetState(automaticLoadButton)) {
    if(!automaticLoadView.isNil())
      XmToggleButtonSetState(automaticLoadView->automaticLoadButton, FALSE,
			     TRUE);
    automaticLoadView = this;
  } else {
    automaticLoadView = NULL;
  }
}


// ------------------------------
// valueChanged()
// ------------------------------
void 
AttachmentEditor::valueChanged(Widget, XtPointer)
{
}


// ------------------------------
// topAttachmentChanged()
// ------------------------------
void 
AttachmentEditor::topAttachmentChanged(Widget, XtPointer callData)
{
  Widget selected;
  XmRowColumnCallbackStruct *cbs = (XmRowColumnCallbackStruct*)callData;
  
  selected = cbs->widget;

  readTop();
  if(selected == topAttachNone) {
    currentData->top.attach = XmATTACH_NONE;
  } else if(selected == topAttachForm) {
    currentData->top.attach = XmATTACH_FORM;
  } else if(selected == topAttachWidget) {
    currentData->top.attach = XmATTACH_WIDGET;
  } else if(selected == topAttachPosition) {
    currentData->top.attach = XmATTACH_POSITION;
  } else if(selected == topAttachSelf) {
    currentData->top.attach = XmATTACH_SELF;
  }
  displayTop();
}


// ------------------------------
// rightAttachmentChanged()
// ------------------------------
void 
AttachmentEditor::rightAttachmentChanged(Widget, XtPointer callData)
{
  Widget selected;
  XmRowColumnCallbackStruct *cbs = (XmRowColumnCallbackStruct*)callData;
  
  selected = cbs->widget;

  readRight();
  if(selected == rightAttachNone) {
    currentData->right.attach = XmATTACH_NONE;
  } else if(selected == rightAttachForm) {
    currentData->right.attach = XmATTACH_FORM;
  } else if(selected == rightAttachWidget) {
    currentData->right.attach = XmATTACH_WIDGET;
  } else if(selected == rightAttachPosition) {
    currentData->right.attach = XmATTACH_POSITION;
  } else if(selected == rightAttachSelf) {
    currentData->right.attach = XmATTACH_SELF;
  }
  displayRight();
}


// ------------------------------
// leftAttachmentChanged()
// ------------------------------
void 
AttachmentEditor::leftAttachmentChanged(Widget, XtPointer callData)
{
  Widget selected;
  XmRowColumnCallbackStruct *cbs = (XmRowColumnCallbackStruct*)callData;
  
  selected = cbs->widget;

  readLeft();
  if(selected == leftAttachNone) {
    currentData->left.attach = XmATTACH_NONE;
  } else if(selected == leftAttachForm) {
    currentData->left.attach = XmATTACH_FORM;
  } else if(selected == leftAttachWidget) {
    currentData->left.attach = XmATTACH_WIDGET;
  } else if(selected == leftAttachPosition) {
    currentData->left.attach = XmATTACH_POSITION;
  } else if(selected == leftAttachSelf) {
    currentData->left.attach = XmATTACH_SELF;
  }
  displayLeft();
}


// ------------------------------
// bottomAttachmentChanged()
// ------------------------------
void 
AttachmentEditor::bottomAttachmentChanged(Widget, XtPointer callData)
{
  Widget selected;
  XmRowColumnCallbackStruct *cbs = (XmRowColumnCallbackStruct*)callData;
  
  selected = cbs->widget;

  readBottom();
  if(selected == bottomAttachNone) {
    currentData->bottom.attach = XmATTACH_NONE;
  } else if(selected == bottomAttachForm) {
    currentData->bottom.attach = XmATTACH_FORM;
  } else if(selected == bottomAttachWidget) {
    currentData->bottom.attach = XmATTACH_WIDGET;
  } else if(selected == bottomAttachPosition) {
    currentData->bottom.attach = XmATTACH_POSITION;
  } else if(selected == bottomAttachSelf) {
    currentData->bottom.attach = XmATTACH_SELF;
  }
  displayBottom();
}


// ----------------------------
// readTop()
// ----------------------------
void 
AttachmentEditor::readTop()
{
  char *str;
  unsigned int i;

  str = XmTextGetString(topOffset);
  currentData->top.offset = str;
  XtFree(str);
  str = XmTextGetString(topPosition);
  currentData->top.position = str;
  XtFree(str);
  if(topWidgetView.selectedIndex(i)) {
    currentData->top.widget = model->getChildren()[i];
  }
}

// ----------------------------
// readLeft()
// ----------------------------
void 
AttachmentEditor::readLeft()
{
  char *str;
  unsigned int i;

  str = XmTextGetString(leftOffset);
  currentData->left.offset = str;
  XtFree(str);
  str = XmTextGetString(leftPosition);
  currentData->left.position = str;
  XtFree(str);
  if(leftWidgetView.selectedIndex(i)) {
    currentData->left.widget = model->getChildren()[i];
  }
}


// ----------------------------
// readRight()
// ----------------------------
void 
AttachmentEditor::readRight()
{
  char *str;
  unsigned int i;

  str = XmTextGetString(rightOffset);
  currentData->right.offset = str;
  XtFree(str);
  str = XmTextGetString(rightPosition);
  currentData->right.position = str;
  XtFree(str);
  if(rightWidgetView.selectedIndex(i)) {
    currentData->right.widget = model->getChildren()[i];
  }
}

// ----------------------------
// readBottom()
// ----------------------------
void 
AttachmentEditor::readBottom()
{
  char *str;
  unsigned int i;

  str = XmTextGetString(bottomOffset);
  currentData->bottom.offset = str;
  XtFree(str);
  str = XmTextGetString(bottomPosition);
  currentData->bottom.position = str;
  XtFree(str);
  if(bottomWidgetView.selectedIndex(i)) {
    currentData->bottom.widget = model->getChildren()[i];
  }
}

// ----------------------------
// readResizable()
// ----------------------------
void 
AttachmentEditor::readResizable()
{
  currentData->resizable = XmToggleButtonGetState(resizableToggle);
}

// ----------------------------
// displayTop()
// ----------------------------
void 
AttachmentEditor::displayTop()
{
  AttachData *data = currentData;

  topWidgetView.setSelected(data->top.widget);
  XmTextSetString(topOffset, data->top.offset);
  XmTextSetString(topPosition, data->top.position);
  switch(data->top.attach) {
  case XmATTACH_NONE:
    XtSetSensitive(topOffset, FALSE);
    XtSetSensitive(topPosition, FALSE);
    XtSetSensitive(topWidget, FALSE);
    XtVaSetValues(topAttachment, XmNmenuHistory, topAttachNone, NULL);
    break;
  case XmATTACH_FORM:
    XtSetSensitive(topOffset, TRUE);
    XtSetSensitive(topPosition, FALSE);
    XtSetSensitive(topWidget, FALSE);
    XtVaSetValues(topAttachment, XmNmenuHistory, topAttachForm, NULL);
    break;
  case XmATTACH_WIDGET:
    XtSetSensitive(topOffset, TRUE);
    XtSetSensitive(topPosition, FALSE);
    XtSetSensitive(topWidget, TRUE);
    XtVaSetValues(topAttachment, XmNmenuHistory, topAttachWidget, NULL);
    break;
  case XmATTACH_POSITION:
    XtSetSensitive(topOffset, TRUE);
    XtSetSensitive(topPosition, TRUE);
    XtSetSensitive(topWidget, FALSE);
    XtVaSetValues(topAttachment, XmNmenuHistory, topAttachPosition, NULL);
    break;
  case XmATTACH_SELF:
    XtSetSensitive(topOffset, FALSE);
    XtSetSensitive(topPosition, FALSE);
    XtSetSensitive(topWidget, FALSE);
    XtVaSetValues(topAttachment, XmNmenuHistory, topAttachSelf, NULL);
    break;
  }
}

// ----------------------------
// displayLeft()
// ----------------------------
void 
AttachmentEditor::displayLeft()
{
  AttachData *data = currentData;

  leftWidgetView.setSelected(data->left.widget);
  XmTextSetString(leftOffset, data->left.offset);
  XmTextSetString(leftPosition, data->left.position);
  switch(data->left.attach) {
  case XmATTACH_NONE:
    XtSetSensitive(leftOffset, FALSE);
    XtSetSensitive(leftPosition, FALSE);
    XtSetSensitive(leftWidget, FALSE);
    XtVaSetValues(leftAttachment, XmNmenuHistory, leftAttachNone, NULL);
    break;
  case XmATTACH_FORM:
    XtSetSensitive(leftOffset, TRUE);
    XtSetSensitive(leftPosition, FALSE);
    XtSetSensitive(leftWidget, FALSE);
    XtVaSetValues(leftAttachment, XmNmenuHistory, leftAttachForm, NULL);
    break;
  case XmATTACH_WIDGET:
    XtSetSensitive(leftOffset, TRUE);
    XtSetSensitive(leftPosition, FALSE);
    XtSetSensitive(leftWidget, TRUE);
    XtVaSetValues(leftAttachment, XmNmenuHistory, leftAttachWidget, NULL);
    break;
  case XmATTACH_POSITION:
    XtSetSensitive(leftOffset, TRUE);
    XtSetSensitive(leftPosition, TRUE);
    XtSetSensitive(leftWidget, FALSE);
    XtVaSetValues(leftAttachment, XmNmenuHistory, leftAttachPosition, NULL);
    break;
  case XmATTACH_SELF:
    XtSetSensitive(leftOffset, FALSE);
    XtSetSensitive(leftPosition, FALSE);
    XtSetSensitive(leftWidget, FALSE);
    XtVaSetValues(leftAttachment, XmNmenuHistory, leftAttachSelf, NULL);
    break;
  }
}


// ----------------------------
// displayRight()
// ----------------------------
void 
AttachmentEditor::displayRight()
{
  AttachData *data = currentData;

  rightWidgetView.setSelected(data->right.widget);
  XmTextSetString(rightOffset, data->right.offset);
  XmTextSetString(rightPosition, data->right.position);
  switch(data->right.attach) {
  case XmATTACH_NONE:
    XtSetSensitive(rightOffset, FALSE);
    XtSetSensitive(rightPosition, FALSE);
    XtSetSensitive(rightWidget, FALSE);
    XtVaSetValues(rightAttachment, XmNmenuHistory, rightAttachNone, NULL);
    break;
  case XmATTACH_FORM:
    XtSetSensitive(rightOffset, TRUE);
    XtSetSensitive(rightPosition, FALSE);
    XtSetSensitive(rightWidget, FALSE);
    XtVaSetValues(rightAttachment, XmNmenuHistory, rightAttachForm, NULL);
    break;
  case XmATTACH_WIDGET:
    XtSetSensitive(rightOffset, TRUE);
    XtSetSensitive(rightPosition, FALSE);
    XtSetSensitive(rightWidget, TRUE);
    XtVaSetValues(rightAttachment, XmNmenuHistory, rightAttachWidget, NULL);
    break;
  case XmATTACH_POSITION:
    XtSetSensitive(rightOffset, TRUE);
    XtSetSensitive(rightPosition, TRUE);
    XtSetSensitive(rightWidget, FALSE);
    XtVaSetValues(rightAttachment, XmNmenuHistory, rightAttachPosition, NULL);
    break;
  case XmATTACH_SELF:
    XtSetSensitive(rightOffset, FALSE);
    XtSetSensitive(rightPosition, FALSE);
    XtSetSensitive(rightWidget, FALSE);
    XtVaSetValues(rightAttachment, XmNmenuHistory, rightAttachSelf, NULL);
    break;
  }
}

// ----------------------------
// displayBottom()
// ----------------------------
void 
AttachmentEditor::displayBottom()
{
  AttachData *data = currentData;

  bottomWidgetView.setSelected(data->bottom.widget);
  XmTextSetString(bottomOffset, data->bottom.offset);
  XmTextSetString(bottomPosition, data->bottom.position);
  switch(data->bottom.attach) {
  case XmATTACH_NONE:
    XtSetSensitive(bottomOffset, FALSE);
    XtSetSensitive(bottomPosition, FALSE);
    XtSetSensitive(bottomWidget, FALSE);
    XtVaSetValues(bottomAttachment, XmNmenuHistory, bottomAttachNone, NULL);
    break;
  case XmATTACH_FORM:
    XtSetSensitive(bottomOffset, TRUE);
    XtSetSensitive(bottomPosition, FALSE);
    XtSetSensitive(bottomWidget, FALSE);
    XtVaSetValues(bottomAttachment, XmNmenuHistory, bottomAttachForm, NULL);
    break;
  case XmATTACH_WIDGET:
    XtSetSensitive(bottomOffset, TRUE);
    XtSetSensitive(bottomPosition, FALSE);
    XtSetSensitive(bottomWidget, TRUE);
    XtVaSetValues(bottomAttachment, XmNmenuHistory, bottomAttachWidget, NULL);
    break;
  case XmATTACH_POSITION:
    XtSetSensitive(bottomOffset, TRUE);
    XtSetSensitive(bottomPosition, TRUE);
    XtSetSensitive(bottomWidget, FALSE);
    XtVaSetValues(bottomAttachment, XmNmenuHistory, bottomAttachPosition, NULL);
    break;
  case XmATTACH_SELF:
    XtSetSensitive(bottomOffset, FALSE);
    XtSetSensitive(bottomPosition, FALSE);
    XtSetSensitive(bottomWidget, FALSE);
    XtVaSetValues(bottomAttachment, XmNmenuHistory, bottomAttachSelf, NULL);
    break;
  }
}

// ----------------------------
// displayResizable()
// ----------------------------
void 
AttachmentEditor::displayResizable()
{
  XmToggleButtonSetState(resizableToggle, currentData->resizable, FALSE);
}

// ----------------------------
// AttachData::delNotify()
// ----------------------------
void 
AttachmentEditor::AttachData::delNotify(BaseRef *r)
{
  if(r == &child)
    delete this;
}

// ----------------------------
// AttachData::AttachData()
// ----------------------------
AttachmentEditor::AttachData::AttachData(Lwidget *c)
  :child(c, this)
{
  char buf[100];
  Lproperty *props;
  unsigned int len = sizeof(buf);

  props = child->getProperties();

  bottom.attach = props->getLresource("bottomAttachment")->getValue();
  bottom.offset = props->getLresource("bottomOffset")->getString(buf,len);
  bottom.position = props->getLresource("bottomPosition")->getString(buf,len);
  bottom.widget = child->getParent()->findNamedWidget(props->getLresource("bottomWidget")->getString(buf,len));
  
  top.attach = props->getLresource("topAttachment")->getValue();
  top.offset = props->getLresource("topOffset")->getString(buf,len);
  top.position = props->getLresource("topPosition")->getString(buf,len);
  top.widget = child->getParent()->findNamedWidget(props->getLresource("topWidget")->getString(buf,len));
  
  left.attach = props->getLresource("leftAttachment")->getValue();
  left.offset = props->getLresource("leftOffset")->getString(buf,len);
  left.position = props->getLresource("leftPosition")->getString(buf,len);
  left.widget = child->getParent()->findNamedWidget(props->getLresource("leftWidget")->getString(buf,len));
  
  right.attach = props->getLresource("rightAttachment")->getValue();
  right.offset = props->getLresource("rightOffset")->getString(buf,len);
  right.position = props->getLresource("rightPosition")->getString(buf,len);
  right.widget = child->getParent()->findNamedWidget(props->getLresource("rightWidget")->getString(buf,len));
  
  resizable = props->getLresource("resizable")->getValue();
}
    
// ----------------------------
// AttachData::apply()
// ----------------------------
void
AttachmentEditor::AttachData::apply()
{
  Lproperty *props;
  Lresource *offset, *position, *widget;
  props = child->getProperties();

  offset = props->getLresource("bottomOffset");
  position = props->getLresource("bottomPosition");
  widget = props->getLresource("bottomWidget");

  props->getLresource("bottomAttachment")->setValue(bottom.attach);
  switch(bottom.attach) {
  case XmATTACH_NONE:
    offset->setDefault(TRUE);
    position->setDefault(TRUE);
    widget->setDefault(TRUE);
    break;
  case XmATTACH_FORM:
    offset->setString(bottom.offset);
    position->setDefault(TRUE);
    widget->setDefault(TRUE);
    break;
  case XmATTACH_POSITION:
    offset->setString(bottom.offset);
    position->setString(bottom.position);
    widget->setDefault(TRUE);
    break;
  case XmATTACH_WIDGET:
    offset->setString(bottom.offset);
    position->setDefault(TRUE);
    if(bottom.widget)
      widget->setString(bottom.widget->getName());
    break;
  case XmATTACH_SELF:
    offset->setDefault(TRUE);
    position->setDefault(TRUE);
    widget->setDefault(TRUE);
    break;
  }

  offset = props->getLresource("topOffset");
  position = props->getLresource("topPosition");
  widget = props->getLresource("topWidget");

  props->getLresource("topAttachment")->setValue(top.attach);
  switch(top.attach) {
  case XmATTACH_NONE:
    offset->setDefault(TRUE);
    position->setDefault(TRUE);
    widget->setDefault(TRUE);
    break;
  case XmATTACH_FORM:
    offset->setString(top.offset);
    position->setDefault(TRUE);
    widget->setDefault(TRUE);
    break;
  case XmATTACH_POSITION:
    offset->setString(top.offset);
    position->setString(top.position);
    widget->setDefault(TRUE);
    break;
  case XmATTACH_WIDGET:
    offset->setString(top.offset);
    position->setDefault(TRUE);
    if(top.widget)
      widget->setString(top.widget->getName());
    break;
  case XmATTACH_SELF:
    offset->setDefault(TRUE);
    position->setDefault(TRUE);
    widget->setDefault(TRUE);
    break;
  }

  offset = props->getLresource("leftOffset");
  position = props->getLresource("leftPosition");
  widget = props->getLresource("leftWidget");

  props->getLresource("leftAttachment")->setValue(left.attach);
  switch(left.attach) {
  case XmATTACH_NONE:
    offset->setDefault(TRUE);
    position->setDefault(TRUE);
    widget->setDefault(TRUE);
    break;
  case XmATTACH_FORM:
    offset->setString(left.offset);
    position->setDefault(TRUE);
    widget->setDefault(TRUE);
    break;
  case XmATTACH_POSITION:
    offset->setString(left.offset);
    position->setString(left.position);
    widget->setDefault(TRUE);
    break;
  case XmATTACH_WIDGET:
    offset->setString(left.offset);
    position->setDefault(TRUE);
    if(left.widget)
      widget->setString(left.widget->getName());
    break;
  case XmATTACH_SELF:
    offset->setDefault(TRUE);
    position->setDefault(TRUE);
    widget->setDefault(TRUE);
    break;
  }

  offset = props->getLresource("rightOffset");
  position = props->getLresource("rightPosition");
  widget = props->getLresource("rightWidget");

  props->getLresource("rightAttachment")->setValue(right.attach);
  switch(right.attach) {
  case XmATTACH_NONE:
    offset->setDefault(TRUE);
    position->setDefault(TRUE);
    widget->setDefault(TRUE);
    break;
  case XmATTACH_FORM:
    offset->setString(right.offset);
    position->setDefault(TRUE);
    widget->setDefault(TRUE);
    break;
  case XmATTACH_POSITION:
    offset->setString(right.offset);
    position->setString(right.position);
    widget->setDefault(TRUE);
    break;
  case XmATTACH_WIDGET:
    offset->setString(right.offset);
    position->setDefault(TRUE);
    if(right.widget)
      widget->setString(right.widget->getName());
    break;
  case XmATTACH_SELF:
    offset->setDefault(TRUE);
    position->setDefault(TRUE);
    widget->setDefault(TRUE);
    break;
  }

  props->getLresource("resizable")->setValue(resizable);
}

// ----------------------------
// SelectionCallback::call
// ----------------------------
void
AttachmentEditor::SelectionCallback::call()
{
  RefArray<Selectable> selection(Selectable::getSelection());
  if(!strcmp(Selectable::getCurrentClass(), "Lwidget")
     && selection.getSize() == 1) {
    Lwidget *lwidget = (Lwidget*)(Selectable*)selection[0];
    if(AttachmentEditor::isOfValidClass(lwidget)) {
      XtSetSensitive(parent->loadButton, TRUE);
    } else {
      XtSetSensitive(parent->loadButton, FALSE);
    }
    if(lwidget->getParent() && lwidget->getParent() == parent->model)
      parent->setSelectedChild(lwidget);
    else
      parent->setSelectedChild(NULL);
  }
}


// ----------------------------
// setSelectedChild()
// ----------------------------

void 
AttachmentEditor::setSelectedChild(Lwidget *child)
{
  if(child) {
    if(!currentData.isNil()) {
      readBottom();
      readTop();
      readLeft();
      readRight();
      readResizable();
    }
    XtSetSensitive(attachmentCellTable, TRUE);
    Boolean found = FALSE;
    for(unsigned int i=0; i<datas.getSize(); i++) {
      if(datas[i]->getChild() == child) {
	currentData = datas[i];
	found = TRUE;
	break;
      }
    }
    if(!found) {
      currentData = new AttachData(child);
      datas.add(currentData);
    }
    displayBottom();
    displayTop();
    displayLeft();
    displayRight();
    displayResizable();
  } else {
    if(!currentData.isNil()) {
      readBottom();
      readTop();
      readLeft();
      readRight();
      readResizable();
    }
    currentData = NULL;
    XtSetSensitive(attachmentCellTable, FALSE);
  }
}

