/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// -----------------------------------------------------
// AttachmentEditor_base.h
// 
// This file was automaticly generated by
// View Designer/X  v1.2
//
// User: lazy@apfel
// Date: Tue Jun  2 17:02:49 1998
//
// Don't edit this file, please !
// -----------------------------------------------------

#ifndef _AttachmentEditor_base_H_
#define _AttachmentEditor_base_H_

#include <X11/Intrinsic.h>
#include <lac/LicView.h>



// -----------------------------------------------------
// Class definition 
// class AttachmentEditor_base is a derived class of LicView
// -----------------------------------------------------

class AttachmentEditor_base : public LicView {
private:
  void createWidgets();
  void addRelations();
  void addCallbacks();

protected:
  Widget AttachmentEditor;
  Widget mainWindow_1;       /* XmMainWindow */
  Widget menuBar;       /* XmCreateMenuBar */
  Widget fileButton;       /* XmCascadeButton */
  Widget fileMenu;       /* XmCreatePulldownMenu */
  Widget loadButton;       /* XmPushButton */
  Widget applyButton;       /* XmPushButton */
  Widget closeButton;       /* XmPushButton */
  Widget viewButton;       /* XmCascadeButton */
  Widget viewMenu;       /* XmCreatePulldownMenu */
  Widget smallIconButton;       /* XmToggleButton */
  Widget withIconButton;       /* XmToggleButton */
  Widget withClassNameButton;       /* XmToggleButton */
  Widget widgetButton;       /* XmCascadeButton */
  Widget widgetMenu;       /* XmCreatePulldownMenu */
  Widget editButton;       /* XmPushButton */
  Widget browseButton;       /* XmPushButton */
  Widget menuEditButton;       /* XmPushButton */
  Widget cutButton;       /* XmPushButton */
  Widget copyButton;       /* XmPushButton */
  Widget pasteButton;       /* XmPushButton */
  Widget separator;       /* XmSeparator */
  Widget deleteButton;       /* XmPushButton */
  Widget helpButton;       /* XmCascadeButton */
  Widget helpMenu;       /* XmCreatePulldownMenu */
  Widget onHelp;       /* XmPushButton */
  Widget onContext;       /* XmPushButton */
  Widget onWidResEditor;       /* XmPushButton */
  Widget optionsButton;       /* XmCascadeButton */
  Widget optionsMenu;       /* XmCreatePulldownMenu */
  Widget automaticLoadButton;       /* XmToggleButton */
  Widget topCellTable;       /* XlCellTable */
  Widget quickHelpLabel;       /* XmLabel */
  Widget mainCellTable;       /* XlCellTable */
  Widget childrenTable;       /* XlCellTable */
  Widget childrenFrame;       /* XmFrame */
  Widget childrenLabel;       /* XmLabel */
  Widget buttonBox;       /* XlButtonBox */
  Widget pushButton_1;       /* XmPushButton */
  Widget pushButton_2;       /* XmPushButton */
  Widget pushButton_3;       /* XmPushButton */
  Widget attachmentCellTable;       /* XlCellTable */
  Widget xlCellTable_1;       /* XlCellTable */
  Widget resizableToggle;       /* XmToggleButton */
  Widget separator_1;       /* XmSeparator */
  Widget separator_1_1;       /* XmSeparator */
  Widget separator_1_2;       /* XmSeparator */
  Widget separator_1_1_1;       /* XmSeparator */
  Widget bottomCellTable;       /* XlCellTable */
  Widget bottomAttachment;       /* XmCreateOptionMenu */
  Widget bottomAttachmentMenu;       /* XmCreatePulldownMenu */
  Widget bottomAttachNone;       /* XmPushButton */
  Widget bottomAttachForm;       /* XmPushButton */
  Widget bottomAttachWidget;       /* XmPushButton */
  Widget bottomAttachPosition;       /* XmPushButton */
  Widget bottomAttachSelf;       /* XmPushButton */
  Widget bottomWidget;       /* XmCreateOptionMenu */
  Widget xlCellTable_5;       /* XlCellTable */
  Widget bottomOffsetLabel;       /* XmLabel */
  Widget bottomPositionLabel;       /* XmLabel */
  Widget bottomOffset;       /* XmText */
  Widget bottomPosition;       /* XmText */
  Widget leftCellTable;       /* XlCellTable */
  Widget leftAttachment;       /* XmCreateOptionMenu */
  Widget leftAttachmentMenu;       /* XmCreatePulldownMenu */
  Widget leftAttachNone;       /* XmPushButton */
  Widget leftAttachForm;       /* XmPushButton */
  Widget leftAttachWidget;       /* XmPushButton */
  Widget leftAttachPosition;       /* XmPushButton */
  Widget leftAttachSelf;       /* XmPushButton */
  Widget leftWidget;       /* XmCreateOptionMenu */
  Widget xlCellTable_3;       /* XlCellTable */
  Widget leftOffsetLabel;       /* XmLabel */
  Widget leftPositionLabel;       /* XmLabel */
  Widget leftOffset;       /* XmText */
  Widget leftPosition;       /* XmText */
  Widget rightCellTable;       /* XlCellTable */
  Widget rightAttachment;       /* XmCreateOptionMenu */
  Widget rightAttachmentMenu;       /* XmCreatePulldownMenu */
  Widget rightAttachNone;       /* XmPushButton */
  Widget rightAttachForm;       /* XmPushButton */
  Widget rightAttachWidget;       /* XmPushButton */
  Widget rightAttachPosition;       /* XmPushButton */
  Widget rightAttachSelf;       /* XmPushButton */
  Widget rightWidget;       /* XmCreateOptionMenu */
  Widget xlCellTable_4;       /* XlCellTable */
  Widget rightOffsetLabel;       /* XmLabel */
  Widget rightPositionLabel;       /* XmLabel */
  Widget rightOffset;       /* XmText */
  Widget rightPosition;       /* XmText */
  Widget xlCellTable;       /* XlCellTable */
  Widget topAttachment;       /* XmCreateOptionMenu */
  Widget topAttachmentMenu;       /* XmCreatePulldownMenu */
  Widget topAttachNone;       /* XmPushButton */
  Widget topAttachForm;       /* XmPushButton */
  Widget topAttachWidget;       /* XmPushButton */
  Widget topAttachPosition;       /* XmPushButton */
  Widget topAttachSelf;       /* XmPushButton */
  Widget topWidget;       /* XmCreateOptionMenu */
  Widget xlCellTable_2;       /* XlCellTable */
  Widget topPositionLabel;       /* XmLabel */
  Widget topOffsetLabel;       /* XmLabel */
  Widget topOffset;       /* XmText */
  Widget topPosition;       /* XmText */


  static void do_load_CB(Widget,XtPointer,XtPointer);
  static void do_apply_CB(Widget,XtPointer,XtPointer);
  static void do_close_CB(Widget,XtPointer,XtPointer);
  static void do_smallIcon_CB(Widget,XtPointer,XtPointer);
  static void do_withIcon_CB(Widget,XtPointer,XtPointer);
  static void do_withClassName_CB(Widget,XtPointer,XtPointer);
  static void do_widgetMenuMap_CB(Widget,XtPointer,XtPointer);
  static void do_onHelp_CB(Widget,XtPointer,XtPointer);
  static void do_onContext_CB(Widget,XtPointer,XtPointer);
  static void do_help_CB(Widget,XtPointer,XtPointer);
  static void do_automaticLoad_CB(Widget,XtPointer,XtPointer);
  static void bottomAttachmentChanged_CB(Widget,XtPointer,XtPointer);
  static void valueChanged_CB(Widget,XtPointer,XtPointer);
  static void leftAttachmentChanged_CB(Widget,XtPointer,XtPointer);
  static void rightAttachmentChanged_CB(Widget,XtPointer,XtPointer);
  static void topAttachmentChanged_CB(Widget,XtPointer,XtPointer);



  // override the following methods in class AttachmentEditor

  virtual void do_load(Widget,XtPointer) = 0;
  virtual void do_apply(Widget,XtPointer) = 0;
  virtual void do_close(Widget,XtPointer) = 0;
  virtual void do_smallIcon(Widget,XtPointer) = 0;
  virtual void do_withIcon(Widget,XtPointer) = 0;
  virtual void do_withClassName(Widget,XtPointer) = 0;
  virtual void do_widgetMenuMap(Widget,XtPointer) = 0;
  virtual void do_onHelp(Widget,XtPointer) = 0;
  virtual void do_onContext(Widget,XtPointer) = 0;
  virtual void do_help(Widget,XtPointer) = 0;
  virtual void do_automaticLoad(Widget,XtPointer) = 0;
  virtual void bottomAttachmentChanged(Widget,XtPointer) = 0;
  virtual void valueChanged(Widget,XtPointer) = 0;
  virtual void leftAttachmentChanged(Widget,XtPointer) = 0;
  virtual void rightAttachmentChanged(Widget,XtPointer) = 0;
  virtual void topAttachmentChanged(Widget,XtPointer) = 0;


public:
  AttachmentEditor_base(Widget parent = NULL, ArgList args = NULL, Cardinal n = 0, char
*fbRes = NULL);

  Widget getTop() { return AttachmentEditor; }
  Pixmap createPixmapFromData(char **data);
  Pixmap createPixmapFromFile(char *filename);
  static void manageWidget(Widget wg, XtPointer c, XtPointer call);
};

#endif /* Don't add stuff after this #endif */






