/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// ---------------------------------------
// ColorSelect_base.C
//
// This file was automaticly generated by
// View Designer/X v1.2
//
// User: lazy@apfel
// Date: Tue Jun  2 17:02:44 1998
//
// Don't edit this file, please !
// ---------------------------------------


// Include class definition

#include "ColorSelect_base.h"

// Include X11 header
#include <X11/xpm.h>

// Include OSF/Motif header files
#include <Xm/Frame.h>
#include <X11/Shell.h>
#include <Xm/Form.h>
#include <Xm/Text.h>
#include <Xm/Separator.h>
#include <Xm/Label.h>
#include <Xm/RowColumn.h>
#include <Xm/Scale.h>
#include <lwid/ButtonBox.h>
#include <Xm/PushB.h>
#include <Xm/ScrolledW.h>
#include <Xm/List.h>
#include <Xm/Frame.h>








#define RES_CONVERT(t,s) cvtResourceFromString(parent, t, s)


// -----------------------------------
// ColorSelect_base(parent,args,n)
// -----------------------------------

ColorSelect_base::ColorSelect_base(Widget p, ArgList f_args, Cardinal f_n, char *fbRes)
{
  Widget parent;
  Arg args[100];
  Cardinal n = 0;

  if(p) 
    parent = p;
  else
    parent = getTopLevel();

  if(fbRes) {
    XrmDatabase database, fallback;
    
    fallback = XrmGetStringDatabase(fbRes);
    database = XrmGetDatabase(XtDisplay(parent));
    
    XrmCombineDatabase(fallback, &database, FALSE);
  }

  if(!XtIsShell(parent)) {
    ColorSelect = XtCreateWidget("ColorSelect",xmFrameWidgetClass,
				       parent,f_args,f_n);
  } else { 
     XtSetArg(args[n], "iconPixmap", createPixmapFromFile("ColorSelect.xpm")); n++;
  XtSetArg(args[n], "title", "Color Selection"); n++;

    popupShell = ColorSelect = XtCreatePopupShell("ColorSelect", topLevelShellWidgetClass,
			parent, args, n);
  }
  createWidgets();
  addCallbacks();
  addRelations();
}


// ----------------------------
// createWidgets()
// ----------------------------

void ColorSelect_base::createWidgets()
{
  Widget parent;           // the parent for every widget
  Arg args[100];           // resource list
  Cardinal n;              // number of resources

  // Now we create every Widget

  
  /* ---------- Creating Widget:    form_1 -------------- */
  parent = ColorSelect;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 358); n++;
  XtSetArg(args[n], "width", 330); n++;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  form_1 = XtCreateWidget("form_1", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(form_1);
  
  addQuickHelp(form_1);
  addHelpId(form_1,10);

  
  /* ---------- Creating Widget:    colorText -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 316); n++;
  XtSetArg(args[n], "y", 3414); n++;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "bottomOffset", 5); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 5); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 5); n++;


  /* Creating Widget */
  colorText = XtCreateWidget("colorText", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(colorText);
  
  addQuickHelp(colorText);
  addHelpId(colorText,-1);

  
  /* ---------- Creating Widget:    separator_1 -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "bottomOffset", 1); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;


  /* Creating Widget */
  separator_1 = XtCreateWidget("separator_1", xmSeparatorWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(separator_1);
  
  addQuickHelp(separator_1);
  addHelpId(separator_1,-1);

  
  /* ---------- Creating Widget:    quickHelp -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "bottomAttachment", 1); n++;
  XtSetArg(args[n], "bottomOffset", 1); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;


  /* Creating Widget */
  quickHelp = XtCreateWidget("quickHelp", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(quickHelp);
  
  addQuickHelp(quickHelp);
  addHelpId(quickHelp,-1);

  
  /* ---------- Creating Widget:    rowColumn_1 -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 333); n++;
  XtSetArg(args[n], "y", 142); n++;
  XtSetArg(args[n], "orientation", 1); n++;
  XtSetArg(args[n], "packing", 1); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 10); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 8); n++;


  /* Creating Widget */
  rowColumn_1 = XtCreateWidget("rowColumn_1", xmRowColumnWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(rowColumn_1);
  
  addQuickHelp(rowColumn_1);
  addHelpId(rowColumn_1,-1);

  
  /* ---------- Creating Widget:    redScale -------------- */
  parent = rowColumn_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 56); n++;
  XtSetArg(args[n], "width", 140); n++;
  XtSetArg(args[n], "x", 3); n++;
  XtSetArg(args[n], "y", 3); n++;
  XtSetArg(args[n], "maximum", 255); n++;
  XtSetArg(args[n], "orientation", 2); n++;
  XtSetArg(args[n], "showValue", 1); n++;
  XtSetArg(args[n], "titleString", RES_CONVERT("XmString", "Red")); n++;


  /* Creating Widget */
  redScale = XtCreateWidget("redScale", xmScaleWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(redScale);
  
  addQuickHelp(redScale);
  addHelpId(redScale,-1);

  
  /* ---------- Creating Widget:    greenScale -------------- */
  parent = rowColumn_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 1666); n++;
  XtSetArg(args[n], "y", 142); n++;
  XtSetArg(args[n], "maximum", 255); n++;
  XtSetArg(args[n], "orientation", 2); n++;
  XtSetArg(args[n], "showValue", 1); n++;
  XtSetArg(args[n], "titleString", RES_CONVERT("XmString", "Green")); n++;


  /* Creating Widget */
  greenScale = XtCreateWidget("greenScale", xmScaleWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(greenScale);
  
  addQuickHelp(greenScale);
  addHelpId(greenScale,-1);

  
  /* ---------- Creating Widget:    blueScale -------------- */
  parent = rowColumn_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 2500); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "maximum", 255); n++;
  XtSetArg(args[n], "orientation", 2); n++;
  XtSetArg(args[n], "showValue", 1); n++;
  XtSetArg(args[n], "titleString", RES_CONVERT("XmString", "Blue")); n++;


  /* Creating Widget */
  blueScale = XtCreateWidget("blueScale", xmScaleWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(blueScale);
  
  addQuickHelp(blueScale);
  addHelpId(blueScale,-1);

  
  /* ---------- Creating Widget:    xlButtonBox_1 -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "bottomOffset", 1); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;


  /* Creating Widget */
  xlButtonBox_1 = XtCreateWidget("xlButtonBox_1", xlButtonBoxWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(xlButtonBox_1);
  
  addQuickHelp(xlButtonBox_1);
  addHelpId(xlButtonBox_1,-1);

  
  /* ---------- Creating Widget:    okButton -------------- */
  parent = xlButtonBox_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 150); n++;
  XtSetArg(args[n], "y", 4414); n++;


  /* Creating Widget */
  okButton = XtCreateWidget("okButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(okButton);
  
  addQuickHelp(okButton);
  addHelpId(okButton,-1);

  
  /* ---------- Creating Widget:    cancelButton -------------- */
  parent = xlButtonBox_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 1500); n++;
  XtSetArg(args[n], "y", 4428); n++;


  /* Creating Widget */
  cancelButton = XtCreateWidget("cancelButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(cancelButton);
  
  addQuickHelp(cancelButton);
  addHelpId(cancelButton,-1);

  
  /* ---------- Creating Widget:    helpButton -------------- */
  parent = xlButtonBox_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 2833); n++;
  XtSetArg(args[n], "y", 4428); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "Help")); n++;


  /* Creating Widget */
  helpButton = XtCreateWidget("helpButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(helpButton);
  
  addQuickHelp(helpButton);
  addHelpId(helpButton,-1);

  
  /* ---------- Creating Widget:    scrolledWindow_1 -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "bottomOffset", 10); n++;
  XtSetArg(args[n], "leftAttachment", 3); n++;
  XtSetArg(args[n], "leftOffset", 10); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 10); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 10); n++;


  /* Creating Widget */
  scrolledWindow_1 = XtCreateWidget("scrolledWindow_1", xmScrolledWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(scrolledWindow_1);
  
  addQuickHelp(scrolledWindow_1);
  addHelpId(scrolledWindow_1,-1);

  
  /* ---------- Creating Widget:    colorList -------------- */
  parent = scrolledWindow_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "scrollBarDisplayPolicy", 0); n++;


  /* Creating Widget */
  colorList = XtCreateWidget("colorList", xmListWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(colorList);
  
  addQuickHelp(colorList);
  addHelpId(colorList,-1);

  
  /* ---------- Creating Widget:    frame_1 -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 47); n++;
  XtSetArg(args[n], "width", 146); n++;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 180); n++;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "bottomOffset", 10); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 10); n++;
  XtSetArg(args[n], "rightAttachment", 3); n++;
  XtSetArg(args[n], "rightOffset", 10); n++;
  XtSetArg(args[n], "topAttachment", 3); n++;
  XtSetArg(args[n], "topOffset", 10); n++;


  /* Creating Widget */
  frame_1 = XtCreateWidget("frame_1", xmFrameWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(frame_1);
  
  addQuickHelp(frame_1);
  addHelpId(frame_1,-1);

  
  /* ---------- Creating Widget:    sampleColor -------------- */
  parent = frame_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 316); n++;
  XtSetArg(args[n], "y", 2414); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", " ")); n++;


  /* Creating Widget */
  sampleColor = XtCreateWidget("sampleColor", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(sampleColor);
  
  addQuickHelp(sampleColor);
  addHelpId(sampleColor,-1);


}



// ----------------------------
// addCallbacks()
// ----------------------------

void ColorSelect_base::addCallbacks()
{

  XtAddCallback( colorText, "activateCallback",
                 textValueChanged_CB, this);

  XtAddCallback( redScale, "dragCallback",
                 valueChanged_CB, this);

  XtAddCallback( redScale, "valueChangedCallback",
                 valueChanged_CB, this);

  XtAddCallback( greenScale, "dragCallback",
                 valueChanged_CB, this);

  XtAddCallback( greenScale, "valueChangedCallback",
                 valueChanged_CB, this);

  XtAddCallback( blueScale, "dragCallback",
                 valueChanged_CB, this);

  XtAddCallback( blueScale, "valueChangedCallback",
                 valueChanged_CB, this);

  XtAddCallback( okButton, "activateCallback",
                 colorSelectOk_CB, this);

  XtAddCallback( cancelButton, "activateCallback",
                 colorSelectCancel_CB, this);

  XtAddCallback( helpButton, "activateCallback",
                 colorSelectHelp_CB, this);

  XtAddCallback( colorList, "browseSelectionCallback",
                 do_browseSelection_CB, this);

}



// ----------------------------
// addRelations()
// ----------------------------

void ColorSelect_base::addRelations()
{
  XtVaSetValues(colorText, "bottomWidget", separator_1, NULL);

  XtVaSetValues(separator_1, "bottomWidget", xlButtonBox_1, NULL);

  XtVaSetValues(xlButtonBox_1, "bottomWidget", quickHelp, NULL);

  XtVaSetValues(scrolledWindow_1, "bottomWidget", colorText, NULL);

  XtVaSetValues(scrolledWindow_1, "leftWidget", rowColumn_1, NULL);

  XtVaSetValues(frame_1, "bottomWidget", colorText, NULL);

  XtVaSetValues(frame_1, "rightWidget", scrolledWindow_1, NULL);

  XtVaSetValues(frame_1, "topWidget", rowColumn_1, NULL);


}


// ----------------------------
// manageWidget()
// ----------------------------
void ColorSelect_base::manageWidget(Widget, XtPointer c, XtPointer)
{
  XtManageChild((Widget)c);
}


// ----------------------------
// createPixmapFromData()
// ----------------------------

Pixmap ColorSelect_base::createPixmapFromData(char **data)
{
  Pixmap pix, mask;
  XpmAttributes attr;

  memset(&attr, 0, sizeof(attr));
  attr.valuemask = XpmReturnPixels;

  if( !XpmCreatePixmapFromData(XtDisplay(LicView::getTopLevel()),
		               XRootWindowOfScreen(XtScreen(LicView::getTopLevel())),
			       data,
			       &pix, &mask, &attr) )
    return pix;
  return XmUNSPECIFIED_PIXMAP;
}

// ------------------------------------------
// createPixmapFromFile()
//
// Creating a pixmap by XpmRaedFileToPixmap()
// Uses XFILESEARCHPATH to find the pixmap
// default path: /usr/lib/X11/pixmaps/%N.xpm
// ------------------------------------------

Pixmap ColorSelect_base::createPixmapFromFile(char *name)
{
  String string;
  Pixmap pix, mask;
  XpmAttributes attr;

  string = XtResolvePathname(XtDisplay(LicView::getTopLevel()),
			     "pixmaps", name, "", NULL,
			     NULL, 0, NULL);
  if(string) {
    memset(&attr, 0, sizeof(attr));
    attr.valuemask = XpmReturnPixels;
    if( !XpmReadFileToPixmap(XtDisplay(LicView::getTopLevel()),
			     XRootWindowOfScreen(
			     XtScreen(LicView::getTopLevel())),
			     string,
			     &pix, &mask, &attr) )
      return pix;
    return XmUNSPECIFIED_PIXMAP;
    XtFree(string);
  }
  return XmUNSPECIFIED_PIXMAP;
}

// ---------------------------------------------------------
// Following class method are used as a callback.
// The method is calling a abstract virtual method, which
// must be overloaded in the derived class 'ColorSelect'
// ---------------------------------------------------------

void ColorSelect_base::textValueChanged_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ColorSelect_base*)clientData)->textValueChanged(wg,callData);
}

void ColorSelect_base::valueChanged_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ColorSelect_base*)clientData)->valueChanged(wg,callData);
}

void ColorSelect_base::colorSelectOk_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ColorSelect_base*)clientData)->colorSelectOk(wg,callData);
}

void ColorSelect_base::colorSelectCancel_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ColorSelect_base*)clientData)->colorSelectCancel(wg,callData);
}

void ColorSelect_base::colorSelectHelp_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ColorSelect_base*)clientData)->colorSelectHelp(wg,callData);
}

void ColorSelect_base::do_browseSelection_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ColorSelect_base*)clientData)->do_browseSelection(wg,callData);
}


