/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// -----------------------------------------------------
// FontSelect_base.h
// 
// This file was automaticly generated by
// View Designer/X  v1.2
//
// User: lazy@apfel
// Date: Tue Jun  2 17:02:44 1998
//
// Don't edit this file, please !
// -----------------------------------------------------

#ifndef _FontSelect_base_H_
#define _FontSelect_base_H_

#include <X11/Intrinsic.h>
#include <lac/LicView.h>



// -----------------------------------------------------
// Class definition 
// class FontSelect_base is a derived class of LicView
// -----------------------------------------------------

class FontSelect_base : public LicView {
private:
  void createWidgets();
  void addRelations();
  void addCallbacks();

protected:
  Widget FontSelect;
  Widget fontCellTable;       /* XmForm */
  Widget fontFilterRowColumn;       /* XmRowColumn */
  Widget companyMenu;       /* XmCreatePulldownMenu */
  Widget companyDontCare;       /* XmPushButton */
  Widget companyOptionMenu;       /* XmCreateOptionMenu */
  Widget familyMenu;       /* XmCreatePulldownMenu */
  Widget familyDontCare;       /* XmPushButton */
  Widget familyOptionMenu;       /* XmCreateOptionMenu */
  Widget sizeMenu;       /* XmCreatePulldownMenu */
  Widget sizeDontCare;       /* XmPushButton */
  Widget sizeOptionMenu;       /* XmCreateOptionMenu */
  Widget listScrolledWindow;       /* XmScrolledWindow */
  Widget fontList;       /* XmList */
  Widget sampleText;       /* XmText */
  Widget fontSelection;       /* XmText */
  Widget separator;       /* XmSeparator */
  Widget buttonBox;       /* XlButtonBox */
  Widget okButton;       /* XmPushButton */
  Widget cancelButton;       /* XmPushButton */
  Widget helpButton;       /* XmPushButton */
  Widget quickHelp;       /* XmLabel */


  static void companyChanged_CB(Widget,XtPointer,XtPointer);
  static void familyChanged_CB(Widget,XtPointer,XtPointer);
  static void sizeChanged_CB(Widget,XtPointer,XtPointer);
  static void fontSelected_CB(Widget,XtPointer,XtPointer);
  static void fontTextChanged_CB(Widget,XtPointer,XtPointer);
  static void fontSelectOk_CB(Widget,XtPointer,XtPointer);
  static void fontSelectCancel_CB(Widget,XtPointer,XtPointer);
  static void fontSelectHelp_CB(Widget,XtPointer,XtPointer);



  // override the following methods in class FontSelect

  virtual void companyChanged(Widget,XtPointer) = 0;
  virtual void familyChanged(Widget,XtPointer) = 0;
  virtual void sizeChanged(Widget,XtPointer) = 0;
  virtual void fontSelected(Widget,XtPointer) = 0;
  virtual void fontTextChanged(Widget,XtPointer) = 0;
  virtual void fontSelectOk(Widget,XtPointer) = 0;
  virtual void fontSelectCancel(Widget,XtPointer) = 0;
  virtual void fontSelectHelp(Widget,XtPointer) = 0;


public:
  FontSelect_base(Widget parent = NULL, ArgList args = NULL, Cardinal n = 0, char
*fbRes = NULL);

  Widget getTop() { return FontSelect; }
  Pixmap createPixmapFromData(char **data);
  Pixmap createPixmapFromFile(char *filename);
  static void manageWidget(Widget wg, XtPointer c, XtPointer call);
};

#endif /* Don't add stuff after this #endif */






