/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
/****************************************************************
 *
 *  $RCSfile: GlobalResEditor.h,v $
 *  $Date: 1999/08/27 15:31:04 $
 *  $Revision: 1.1.1.1.2.1 $
 *
 *  Copyright 1997, Dirk Laessig
 *  ALL RIGHTS RESERVED
 *  See the file Copyright for more information
 *
 *  Dirk Laessig
 *  Goettingstr. 5
 *  38106 Braunschweig
 *  Germany
 ****************************************************************/
/*
 * $Log: GlobalResEditor.h,v $
 * Revision 1.1.1.1.2.1  1999/08/27 15:31:04  dirk
 * Transform the copyright to GPL
 *
 * Revision 1.1.1.1  1998/04/24 23:45:18  lazy
 * Imported to CVS
 *
 * Revision 1.2  1997/09/02  22:24:08  lazy
 * It works.
 *
 */

// ----------------------------
// GlobalResEditor.h
//
// This file was automaticly generated by
// View Designer/X v1.1.0
//
// User: lazy@apfel.goetting5
// Date: Sun Jun 29 11:28:44 1997
//
// ----------------------------

#ifndef _GlobalResEditor_H_
#define _GlobalResEditor_H_

#include "GlobalResEditor_base.h"
#include "LresEditor.h"
#include "ColorSelect.h"
#include "FontSelect.h"

class Lproject;

class GlobalResEditor : public GlobalResEditor_base {
private:
  class GlobalResTextView : public ValueView {
  private:
    Widget text;
    Lproject *lproject;

  public:
    GlobalResTextView(Lproject *p, Widget wg) :
      ValueView(p) { lproject = p; text = wg; }

    Boolean apply();
    void getText(char *, unsigned long &);
    void setText(char *);
    void update(unsigned long) {}
    void act(char *) {}
  };
  
protected:
  virtual void do_apply(Widget,XtPointer);
  virtual void doExit(Widget,XtPointer);
  virtual void cutText(Widget,XtPointer);
  virtual void copyText(Widget,XtPointer);
  virtual void pasteText(Widget,XtPointer);
  virtual void do_onHelp(Widget,XtPointer);
  virtual void do_onContext(Widget,XtPointer);
  virtual void helpMe(Widget,XtPointer);
  virtual void importFile(Widget,XtPointer);
  virtual void do_fontChooser(Widget,XtPointer);
  virtual void do_ColorSelect(Widget,XtPointer);

  Ref<ColorSelect> colorSelect;
  Ref<FontSelect> fontSelect;
  Ref<GlobalResTextView> textView;

  Ref<Lproject> model;
  static RefArray<GlobalResEditor> allViews;

  GlobalResEditor(Lproject *);

  Boolean saveSize() { return True; }

public:
  static void showView(Lproject *);
  
  ~GlobalResEditor();
};


#endif /* Don't add stuff after this #endif */
