/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// -----------------------------------------------------
// GlobalResEditor_base.h
// 
// This file was automaticly generated by
// View Designer/X  v1.2
//
// User: lazy@apfel
// Date: Tue Jun  2 17:02:50 1998
//
// Don't edit this file, please !
// -----------------------------------------------------

#ifndef _GlobalResEditor_base_H_
#define _GlobalResEditor_base_H_

#include <X11/Intrinsic.h>
#include <lac/LicView.h>



// -----------------------------------------------------
// Class definition 
// class GlobalResEditor_base is a derived class of LicView
// -----------------------------------------------------

class GlobalResEditor_base : public LicView {
private:
  void createWidgets();
  void addRelations();
  void addCallbacks();

protected:
  Widget GlobalResEditor;
  Widget form;       /* XmForm */
  Widget menuBar;       /* XmCreateMenuBar */
  Widget fileMenuButton;       /* XmCascadeButton */
  Widget fileMenu;       /* XmCreatePulldownMenu */
  Widget fileImport;       /* XmPushButton */
  Widget fileApply;       /* XmPushButton */
  Widget XmSeparator;       /* XmSeparator */
  Widget fileClose;       /* XmPushButton */
  Widget editMenuButton;       /* XmCascadeButton */
  Widget editMenu;       /* XmCreatePulldownMenu */
  Widget editCut;       /* XmPushButton */
  Widget editCopy;       /* XmPushButton */
  Widget editPaste;       /* XmPushButton */
  Widget helpMenuButton;       /* XmCascadeButton */
  Widget helpMenu;       /* XmCreatePulldownMenu */
  Widget onHelp;       /* XmPushButton */
  Widget onContext;       /* XmPushButton */
  Widget helpHelp;       /* XmPushButton */
  Widget fileImportDialog;       /* XmCreateFileSelectionDialog */
  Widget scrolledWindow;       /* XmScrolledWindow */
  Widget text;       /* XmText */
  Widget quickHelpLabel;       /* XmLabel */
  Widget toolsRowColumn;       /* XmRowColumn */
  Widget fontChooserButton;       /* XmPushButton */
  Widget colorSelectButton;       /* XmPushButton */
  Widget applyButton;       /* XmPushButton */


  static void do_apply_CB(Widget,XtPointer,XtPointer);
  static void doExit_CB(Widget,XtPointer,XtPointer);
  static void cutText_CB(Widget,XtPointer,XtPointer);
  static void copyText_CB(Widget,XtPointer,XtPointer);
  static void pasteText_CB(Widget,XtPointer,XtPointer);
  static void do_onHelp_CB(Widget,XtPointer,XtPointer);
  static void do_onContext_CB(Widget,XtPointer,XtPointer);
  static void helpMe_CB(Widget,XtPointer,XtPointer);
  static void importFile_CB(Widget,XtPointer,XtPointer);
  static void do_fontChooser_CB(Widget,XtPointer,XtPointer);
  static void do_ColorSelect_CB(Widget,XtPointer,XtPointer);



  // override the following methods in class GlobalResEditor

  virtual void do_apply(Widget,XtPointer) = 0;
  virtual void doExit(Widget,XtPointer) = 0;
  virtual void cutText(Widget,XtPointer) = 0;
  virtual void copyText(Widget,XtPointer) = 0;
  virtual void pasteText(Widget,XtPointer) = 0;
  virtual void do_onHelp(Widget,XtPointer) = 0;
  virtual void do_onContext(Widget,XtPointer) = 0;
  virtual void helpMe(Widget,XtPointer) = 0;
  virtual void importFile(Widget,XtPointer) = 0;
  virtual void do_fontChooser(Widget,XtPointer) = 0;
  virtual void do_ColorSelect(Widget,XtPointer) = 0;


public:
  GlobalResEditor_base(Widget parent = NULL, ArgList args = NULL, Cardinal n = 0, char
*fbRes = NULL);

  Widget getTop() { return GlobalResEditor; }
  Pixmap createPixmapFromData(char **data);
  Pixmap createPixmapFromFile(char *filename);
  static void manageWidget(Widget wg, XtPointer c, XtPointer call);
};

#endif /* Don't add stuff after this #endif */






