/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// ---------------------------------------
// MenuEdit_base.C
//
// This file was automaticly generated by
// View Designer/X v1.2
//
// User: lazy@apfel
// Date: Tue Jun  2 17:02:47 1998
//
// Don't edit this file, please !
// ---------------------------------------


// Include class definition

#include "MenuEdit_base.h"

// Include X11 header
#include <X11/xpm.h>

// Include OSF/Motif header files
#include <Xm/Frame.h>
#include <X11/Shell.h>
#include <Xm/MainW.h>
#include <Xm/Form.h>
#include <Xm/Label.h>
#include <Xm/ArrowB.h>
#include <Xm/Frame.h>
#include <Xm/RowColumn.h>
#include <Xm/PushB.h>
#include <Xm/CascadeB.h>
#include <Xm/ToggleB.h>
#include <Xm/Separator.h>








#define RES_CONVERT(t,s) cvtResourceFromString(parent, t, s)


// -----------------------------------
// MenuEdit_base(parent,args,n)
// -----------------------------------

MenuEdit_base::MenuEdit_base(Widget p, ArgList f_args, Cardinal f_n, char *fbRes)
{
  Widget parent;
  Arg args[100];
  Cardinal n = 0;

  if(p) 
    parent = p;
  else
    parent = getTopLevel();

  if(fbRes) {
    XrmDatabase database, fallback;
    
    fallback = XrmGetStringDatabase(fbRes);
    database = XrmGetDatabase(XtDisplay(parent));
    
    XrmCombineDatabase(fallback, &database, FALSE);
  }

  if(!XtIsShell(parent)) {
    MenuEdit = XtCreateWidget("MenuEdit",xmFrameWidgetClass,
				       parent,f_args,f_n);
  } else { 
     XtSetArg(args[n], "iconPixmap", createPixmapFromFile("MenuEdit.xpm")); n++;

    popupShell = MenuEdit = XtCreatePopupShell("MenuEdit", topLevelShellWidgetClass,
			parent, args, n);
  }
  createWidgets();
  addCallbacks();
  addRelations();
}


// ----------------------------
// createWidgets()
// ----------------------------

void MenuEdit_base::createWidgets()
{
  Widget parent;           // the parent for every widget
  Arg args[100];           // resource list
  Cardinal n;              // number of resources

  // Now we create every Widget

  
  /* ---------- Creating Widget:    mainWindow -------------- */
  parent = MenuEdit;

  /* Building resource list */
  n = 0;


  /* Creating Widget */
  mainWindow = XtCreateWidget("mainWindow", xmMainWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(mainWindow);
  
  addQuickHelp(mainWindow);
  addHelpId(mainWindow,12);

  
  /* ---------- Creating Widget:    form -------------- */
  parent = mainWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 360); n++;
  XtSetArg(args[n], "width", 410); n++;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 31); n++;


  /* Creating Widget */
  form = XtCreateWidget("form", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(form);
  
  addQuickHelp(form);
  addHelpId(form,-1);

  
  /* ---------- Creating Widget:    Label1 -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 110); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "leftAttachment", 3); n++;
  XtSetArg(args[n], "leftOffset", 5); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 5); n++;


  /* Creating Widget */
  Label1 = XtCreateWidget("Label1", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(Label1);
  
  addQuickHelp(Label1);
  addHelpId(Label1,-1);

  
  /* ---------- Creating Widget:    Label2 -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 180); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 5); n++;
  XtSetArg(args[n], "topAttachment", 3); n++;
  XtSetArg(args[n], "topOffset", 10); n++;


  /* Creating Widget */
  Label2 = XtCreateWidget("Label2", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(Label2);
  
  addQuickHelp(Label2);
  addHelpId(Label2,-1);

  
  /* ---------- Creating Widget:    ArrowUp -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 30); n++;
  XtSetArg(args[n], "width", 30); n++;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 200); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 6); n++;
  XtSetArg(args[n], "topAttachment", 3); n++;
  XtSetArg(args[n], "topOffset", 5); n++;


  /* Creating Widget */
  ArrowUp = XtCreateWidget("ArrowUp", xmArrowButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(ArrowUp);
  
  addQuickHelp(ArrowUp);
  addHelpId(ArrowUp,-1);

  
  /* ---------- Creating Widget:    ArrowDown -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 30); n++;
  XtSetArg(args[n], "width", 30); n++;
  XtSetArg(args[n], "x", 40); n++;
  XtSetArg(args[n], "y", 200); n++;
  XtSetArg(args[n], "arrowDirection", 1); n++;
  XtSetArg(args[n], "leftAttachment", 3); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "topAttachment", 3); n++;
  XtSetArg(args[n], "topOffset", 5); n++;


  /* Creating Widget */
  ArrowDown = XtCreateWidget("ArrowDown", xmArrowButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(ArrowDown);
  
  addQuickHelp(ArrowDown);
  addHelpId(ArrowDown,-1);

  
  /* ---------- Creating Widget:    iconViewFrame -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "shadowThickness", 0); n++;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "bottomOffset", 3); n++;
  XtSetArg(args[n], "leftAttachment", 3); n++;
  XtSetArg(args[n], "leftOffset", 5); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 5); n++;
  XtSetArg(args[n], "topAttachment", 3); n++;
  XtSetArg(args[n], "topOffset", 3); n++;


  /* Creating Widget */
  iconViewFrame = XtCreateWidget("iconViewFrame", xmFrameWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(iconViewFrame);
  
  addQuickHelp(iconViewFrame);
  addHelpId(iconViewFrame,-1);

  
  /* ---------- Creating Widget:    rowColumn_1 -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 183); n++;
  XtSetArg(args[n], "width", 90); n++;
  XtSetArg(args[n], "x", 5); n++;
  XtSetArg(args[n], "y", 5); n++;
  XtSetArg(args[n], "marginHeight", 0); n++;
  XtSetArg(args[n], "marginWidth", 0); n++;
  XtSetArg(args[n], "numColumns", 1); n++;
  XtSetArg(args[n], "orientation", 1); n++;
  XtSetArg(args[n], "packing", 1); n++;
  XtSetArg(args[n], "resizeHeight", 1); n++;
  XtSetArg(args[n], "resizeWidth", 1); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 5); n++;
  XtSetArg(args[n], "resizable", 0); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 5); n++;


  /* Creating Widget */
  rowColumn_1 = XtCreateWidget("rowColumn_1", xmRowColumnWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(rowColumn_1);
  
  addQuickHelp(rowColumn_1);
  addHelpId(rowColumn_1,-1);

  
  /* ---------- Creating Widget:    Label3 -------------- */
  parent = rowColumn_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 249); n++;
  XtSetArg(args[n], "y", 127); n++;
  XtSetArg(args[n], "alignment", 0); n++;


  /* Creating Widget */
  Label3 = XtCreateWidget("Label3", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(Label3);
  
  addQuickHelp(Label3);
  addHelpId(Label3,-1);

  
  /* ---------- Creating Widget:    addLabelButton -------------- */
  parent = rowColumn_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 30); n++;
  XtSetArg(args[n], "width", 100); n++;
  XtSetArg(args[n], "x", 249); n++;
  XtSetArg(args[n], "y", 147); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "Label")); n++;
  XtSetArg(args[n], "marginHeight", 4); n++;
  XtSetArg(args[n], "marginWidth", 4); n++;


  /* Creating Widget */
  addLabelButton = XtCreateWidget("addLabelButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(addLabelButton);
  
  addQuickHelp(addLabelButton);
  addHelpId(addLabelButton,-1);

  
  /* ---------- Creating Widget:    addPushButtonLazy -------------- */
  parent = rowColumn_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 30); n++;
  XtSetArg(args[n], "width", 100); n++;
  XtSetArg(args[n], "x", 249); n++;
  XtSetArg(args[n], "y", 177); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "PushButton")); n++;
  XtSetArg(args[n], "marginHeight", 4); n++;
  XtSetArg(args[n], "marginWidth", 4); n++;


  /* Creating Widget */
  addPushButtonLazy = XtCreateWidget("addPushButtonLazy", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(addPushButtonLazy);
  
  addQuickHelp(addPushButtonLazy);
  addHelpId(addPushButtonLazy,-1);

  
  /* ---------- Creating Widget:    addToggleButtonButton -------------- */
  parent = rowColumn_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 30); n++;
  XtSetArg(args[n], "width", 100); n++;
  XtSetArg(args[n], "x", 249); n++;
  XtSetArg(args[n], "y", 207); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "ToggleButton")); n++;
  XtSetArg(args[n], "marginHeight", 4); n++;
  XtSetArg(args[n], "marginWidth", 4); n++;


  /* Creating Widget */
  addToggleButtonButton = XtCreateWidget("addToggleButtonButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(addToggleButtonButton);
  
  addQuickHelp(addToggleButtonButton);
  addHelpId(addToggleButtonButton,-1);

  
  /* ---------- Creating Widget:    addSeparatorButton -------------- */
  parent = rowColumn_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 30); n++;
  XtSetArg(args[n], "width", 100); n++;
  XtSetArg(args[n], "x", 249); n++;
  XtSetArg(args[n], "y", 237); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "Separator")); n++;
  XtSetArg(args[n], "marginHeight", 4); n++;
  XtSetArg(args[n], "marginWidth", 4); n++;


  /* Creating Widget */
  addSeparatorButton = XtCreateWidget("addSeparatorButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(addSeparatorButton);
  
  addQuickHelp(addSeparatorButton);
  addHelpId(addSeparatorButton,-1);

  
  /* ---------- Creating Widget:    addSubMenuButton -------------- */
  parent = rowColumn_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 30); n++;
  XtSetArg(args[n], "width", 100); n++;
  XtSetArg(args[n], "x", 249); n++;
  XtSetArg(args[n], "y", 267); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "SubMenu")); n++;
  XtSetArg(args[n], "marginHeight", 4); n++;
  XtSetArg(args[n], "marginWidth", 4); n++;


  /* Creating Widget */
  addSubMenuButton = XtCreateWidget("addSubMenuButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(addSubMenuButton);
  
  addQuickHelp(addSubMenuButton);
  addHelpId(addSubMenuButton,-1);

  
  /* ---------- Creating Widget:    quickHelp -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 310); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "bottomAttachment", 1); n++;
  XtSetArg(args[n], "bottomOffset", 1); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;


  /* Creating Widget */
  quickHelp = XtCreateWidget("quickHelp", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(quickHelp);
  
  addQuickHelp(quickHelp);
  addHelpId(quickHelp,-1);

  
  /* ---------- Creating Widget:    widBrowseMenuBar -------------- */
  parent = mainWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 20); n++;
  XtSetArg(args[n], "y", 10); n++;


  /* Creating Widget */
  widBrowseMenuBar = XmCreateMenuBar( parent, "widBrowseMenuBar", args, n);
  
  /* Manage the Widget */
  XtManageChild(widBrowseMenuBar);
  
  addQuickHelp(widBrowseMenuBar);
  addHelpId(widBrowseMenuBar,-1);

  
  /* ---------- Creating Widget:    fileButton -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileButton = XtCreateWidget("fileButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(fileButton);
  
  addQuickHelp(fileButton);
  addHelpId(fileButton,-1);

  
  /* ---------- Creating Widget:    fileMenu -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileMenu = XmCreatePulldownMenu( parent, "fileMenu", args, n);
  
  addQuickHelp(fileMenu);
  addHelpId(fileMenu,-1);

  
  /* ---------- Creating Widget:    loadButton -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  loadButton = XtCreateWidget("loadButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(loadButton);
  
  addQuickHelp(loadButton);
  addHelpId(loadButton,-1);

  
  /* ---------- Creating Widget:    loadParentButton -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "mnemonic", RES_CONVERT("KeySym", "P")); n++;


  /* Creating Widget */
  loadParentButton = XtCreateWidget("loadParentButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(loadParentButton);
  
  addQuickHelp(loadParentButton);
  addHelpId(loadParentButton,-1);

  
  /* ---------- Creating Widget:    closeButton -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "accelerator", "Ctrl<Key>c"); n++;
  XtSetArg(args[n], "acceleratorText", RES_CONVERT("XmString", "^C")); n++;


  /* Creating Widget */
  closeButton = XtCreateWidget("closeButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(closeButton);
  
  addQuickHelp(closeButton);
  addHelpId(closeButton,-1);

  
  /* ---------- Creating Widget:    viewButton -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "mnemonic", RES_CONVERT("KeySym", "V")); n++;


  /* Creating Widget */
  viewButton = XtCreateWidget("viewButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(viewButton);
  
  addQuickHelp(viewButton);
  addHelpId(viewButton,-1);

  
  /* ---------- Creating Widget:    viewMenu -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  viewMenu = XmCreatePulldownMenu( parent, "viewMenu", args, n);
  
  addQuickHelp(viewMenu);
  addHelpId(viewMenu,-1);

  
  /* ---------- Creating Widget:    smallIconButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  smallIconButton = XtCreateWidget("smallIconButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(smallIconButton);
  
  addQuickHelp(smallIconButton);
  addHelpId(smallIconButton,-1);

  
  /* ---------- Creating Widget:    withIconButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  withIconButton = XtCreateWidget("withIconButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(withIconButton);
  
  addQuickHelp(withIconButton);
  addHelpId(withIconButton,-1);

  
  /* ---------- Creating Widget:    withClassNameButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  withClassNameButton = XtCreateWidget("withClassNameButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(withClassNameButton);
  
  addQuickHelp(withClassNameButton);
  addHelpId(withClassNameButton,-1);

  
  /* ---------- Creating Widget:    widgetButton -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  widgetButton = XtCreateWidget("widgetButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(widgetButton);
  
  addQuickHelp(widgetButton);
  addHelpId(widgetButton,-1);

  
  /* ---------- Creating Widget:    widgetMenu -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  widgetMenu = XmCreatePulldownMenu( parent, "widgetMenu", args, n);
  
  addQuickHelp(widgetMenu);
  addHelpId(widgetMenu,-1);

  
  /* ---------- Creating Widget:    editButton -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  editButton = XtCreateWidget("editButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(editButton);
  
  addQuickHelp(editButton);
  addHelpId(editButton,-1);

  
  /* ---------- Creating Widget:    browseButton -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  browseButton = XtCreateWidget("browseButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(browseButton);
  
  addQuickHelp(browseButton);
  addHelpId(browseButton,-1);

  
  /* ---------- Creating Widget:    menuEditButton -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  menuEditButton = XtCreateWidget("menuEditButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(menuEditButton);
  
  addQuickHelp(menuEditButton);
  addHelpId(menuEditButton,-1);

  
  /* ---------- Creating Widget:    cutButton -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  cutButton = XtCreateWidget("cutButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(cutButton);
  
  addQuickHelp(cutButton);
  addHelpId(cutButton,-1);

  
  /* ---------- Creating Widget:    copyButton -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  copyButton = XtCreateWidget("copyButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(copyButton);
  
  addQuickHelp(copyButton);
  addHelpId(copyButton,-1);

  
  /* ---------- Creating Widget:    pasteButton -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  pasteButton = XtCreateWidget("pasteButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(pasteButton);
  
  addQuickHelp(pasteButton);
  addHelpId(pasteButton,-1);

  
  /* ---------- Creating Widget:    separator -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  separator = XtCreateWidget("separator", xmSeparatorWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(separator);
  
  addQuickHelp(separator);
  addHelpId(separator,-1);

  
  /* ---------- Creating Widget:    deleteButton -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  deleteButton = XtCreateWidget("deleteButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(deleteButton);
  
  addQuickHelp(deleteButton);
  addHelpId(deleteButton,-1);

  
  /* ---------- Creating Widget:    helpButton -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  helpButton = XtCreateWidget("helpButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(helpButton);
  
  addQuickHelp(helpButton);
  addHelpId(helpButton,-1);

  
  /* ---------- Creating Widget:    helpMenu -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  helpMenu = XmCreatePulldownMenu( parent, "helpMenu", args, n);
  
  addQuickHelp(helpMenu);
  addHelpId(helpMenu,-1);

  
  /* ---------- Creating Widget:    onHelp -------------- */
  parent = helpMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  onHelp = XtCreateWidget("onHelp", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(onHelp);
  
  addQuickHelp(onHelp);
  addHelpId(onHelp,-1);

  
  /* ---------- Creating Widget:    onContext -------------- */
  parent = helpMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "On Context")); n++;


  /* Creating Widget */
  onContext = XtCreateWidget("onContext", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(onContext);
  
  addQuickHelp(onContext);
  addHelpId(onContext,-1);

  
  /* ---------- Creating Widget:    onWidResEditor -------------- */
  parent = helpMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "On Window")); n++;
  XtSetArg(args[n], "mnemonic", RES_CONVERT("KeySym", "W")); n++;


  /* Creating Widget */
  onWidResEditor = XtCreateWidget("onWidResEditor", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(onWidResEditor);
  
  addQuickHelp(onWidResEditor);
  addHelpId(onWidResEditor,-1);

  
  /* ---------- Creating Widget:    optionsButton -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  optionsButton = XtCreateWidget("optionsButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(optionsButton);
  
  addQuickHelp(optionsButton);
  addHelpId(optionsButton,-1);

  
  /* ---------- Creating Widget:    optionsMenu -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  optionsMenu = XmCreatePulldownMenu( parent, "optionsMenu", args, n);
  
  addQuickHelp(optionsMenu);
  addHelpId(optionsMenu,-1);

  
  /* ---------- Creating Widget:    automaticLoadButton -------------- */
  parent = optionsMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  automaticLoadButton = XtCreateWidget("automaticLoadButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(automaticLoadButton);
  
  addQuickHelp(automaticLoadButton);
  addHelpId(automaticLoadButton,-1);


}



// ----------------------------
// addCallbacks()
// ----------------------------

void MenuEdit_base::addCallbacks()
{

  XtAddCallback( ArrowUp, "activateCallback",
                 moveUp_CB, this);

  XtAddCallback( ArrowDown, "activateCallback",
                 moveDown_CB, this);

  XtAddCallback( addLabelButton, "activateCallback",
                 addLabel_CB, this);

  XtAddCallback( addPushButtonLazy, "activateCallback",
                 addPushbutton_CB, this);

  XtAddCallback( addToggleButtonButton, "activateCallback",
                 addToggleButton_CB, this);

  XtAddCallback( addSeparatorButton, "activateCallback",
                 addSeparator_CB, this);

  XtAddCallback( addSubMenuButton, "activateCallback",
                 addSubMenu_CB, this);

  XtAddCallback( loadButton, "activateCallback",
                 do_load_CB, this);

  XtAddCallback( loadParentButton, "activateCallback",
                 do_loadParent_CB, this);

  XtAddCallback( closeButton, "activateCallback",
                 do_close_CB, this);

  XtAddCallback( smallIconButton, "valueChangedCallback",
                 do_smallIcon_CB, this);

  XtAddCallback( withIconButton, "valueChangedCallback",
                 do_withIcon_CB, this);

  XtAddCallback( withClassNameButton, "valueChangedCallback",
                 do_withClassName_CB, this);

  XtAddCallback( widgetMenu, "mapCallback",
                 do_widgetMenuMap_CB, this);

  XtAddCallback( onHelp, "activateCallback",
                 do_onHelp_CB, this);

  XtAddCallback( onContext, "activateCallback",
                 do_onContext_CB, this);

  XtAddCallback( onWidResEditor, "activateCallback",
                 do_help_CB, this);

  XtAddCallback( automaticLoadButton, "valueChangedCallback",
                 do_automaticLoad_CB, this);

}



// ----------------------------
// addRelations()
// ----------------------------

void MenuEdit_base::addRelations()
{
  XtVaSetValues(Label1, "leftWidget", rowColumn_1, NULL);

  XtVaSetValues(Label2, "topWidget", rowColumn_1, NULL);

  XtVaSetValues(ArrowUp, "topWidget", Label2, NULL);

  XtVaSetValues(ArrowDown, "leftWidget", ArrowUp, NULL);

  XtVaSetValues(ArrowDown, "topWidget", Label2, NULL);

  XtVaSetValues(iconViewFrame, "bottomWidget", quickHelp, NULL);

  XtVaSetValues(iconViewFrame, "leftWidget", rowColumn_1, NULL);

  XtVaSetValues(iconViewFrame, "topWidget", Label1, NULL);

  XtVaSetValues(widBrowseMenuBar, "menuHelpWidget", helpButton, NULL);

  XtVaSetValues(fileButton, "subMenuId", fileMenu, NULL);

  XtVaSetValues(viewButton, "subMenuId", viewMenu, NULL);

  XtVaSetValues(widgetButton, "subMenuId", widgetMenu, NULL);

  XtVaSetValues(helpButton, "subMenuId", helpMenu, NULL);

  XtVaSetValues(optionsButton, "subMenuId", optionsMenu, NULL);


}


// ----------------------------
// manageWidget()
// ----------------------------
void MenuEdit_base::manageWidget(Widget, XtPointer c, XtPointer)
{
  XtManageChild((Widget)c);
}


// ----------------------------
// createPixmapFromData()
// ----------------------------

Pixmap MenuEdit_base::createPixmapFromData(char **data)
{
  Pixmap pix, mask;
  XpmAttributes attr;

  memset(&attr, 0, sizeof(attr));
  attr.valuemask = XpmReturnPixels;

  if( !XpmCreatePixmapFromData(XtDisplay(LicView::getTopLevel()),
		               XRootWindowOfScreen(XtScreen(LicView::getTopLevel())),
			       data,
			       &pix, &mask, &attr) )
    return pix;
  return XmUNSPECIFIED_PIXMAP;
}

// ------------------------------------------
// createPixmapFromFile()
//
// Creating a pixmap by XpmRaedFileToPixmap()
// Uses XFILESEARCHPATH to find the pixmap
// default path: /usr/lib/X11/pixmaps/%N.xpm
// ------------------------------------------

Pixmap MenuEdit_base::createPixmapFromFile(char *name)
{
  String string;
  Pixmap pix, mask;
  XpmAttributes attr;

  string = XtResolvePathname(XtDisplay(LicView::getTopLevel()),
			     "pixmaps", name, "", NULL,
			     NULL, 0, NULL);
  if(string) {
    memset(&attr, 0, sizeof(attr));
    attr.valuemask = XpmReturnPixels;
    if( !XpmReadFileToPixmap(XtDisplay(LicView::getTopLevel()),
			     XRootWindowOfScreen(
			     XtScreen(LicView::getTopLevel())),
			     string,
			     &pix, &mask, &attr) )
      return pix;
    return XmUNSPECIFIED_PIXMAP;
    XtFree(string);
  }
  return XmUNSPECIFIED_PIXMAP;
}

// ---------------------------------------------------------
// Following class method are used as a callback.
// The method is calling a abstract virtual method, which
// must be overloaded in the derived class 'MenuEdit'
// ---------------------------------------------------------

void MenuEdit_base::moveUp_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->moveUp(wg,callData);
}

void MenuEdit_base::moveDown_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->moveDown(wg,callData);
}

void MenuEdit_base::addLabel_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->addLabel(wg,callData);
}

void MenuEdit_base::addPushbutton_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->addPushbutton(wg,callData);
}

void MenuEdit_base::addToggleButton_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->addToggleButton(wg,callData);
}

void MenuEdit_base::addSeparator_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->addSeparator(wg,callData);
}

void MenuEdit_base::addSubMenu_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->addSubMenu(wg,callData);
}

void MenuEdit_base::do_load_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->do_load(wg,callData);
}

void MenuEdit_base::do_loadParent_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->do_loadParent(wg,callData);
}

void MenuEdit_base::do_close_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->do_close(wg,callData);
}

void MenuEdit_base::do_smallIcon_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->do_smallIcon(wg,callData);
}

void MenuEdit_base::do_withIcon_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->do_withIcon(wg,callData);
}

void MenuEdit_base::do_withClassName_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->do_withClassName(wg,callData);
}

void MenuEdit_base::do_widgetMenuMap_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->do_widgetMenuMap(wg,callData);
}

void MenuEdit_base::do_onHelp_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->do_onHelp(wg,callData);
}

void MenuEdit_base::do_onContext_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->do_onContext(wg,callData);
}

void MenuEdit_base::do_help_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->do_help(wg,callData);
}

void MenuEdit_base::do_automaticLoad_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MenuEdit_base*)clientData)->do_automaticLoad(wg,callData);
}


