/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// -----------------------------------------------------
// ProjectSettings_base.h
// 
// This file was automaticly generated by
// View Designer/X  v1.2
//
// User: lazy@apfel
// Date: Tue Jun  2 17:02:48 1998
//
// Don't edit this file, please !
// -----------------------------------------------------

#ifndef _ProjectSettings_base_H_
#define _ProjectSettings_base_H_

#include <X11/Intrinsic.h>
#include <lac/LicView.h>



// -----------------------------------------------------
// Class definition 
// class ProjectSettings_base is a derived class of LicView
// -----------------------------------------------------

class ProjectSettings_base : public LicView {
private:
  void createWidgets();
  void addRelations();
  void addCallbacks();

protected:
  Widget ProjectSettings;
  Widget form;       /* XmForm */
  Widget xlCellTable_1;       /* XlCellTable */
  Widget PSNameLabel;       /* XmLabel */
  Widget PSNameText;       /* XmText */
  Widget applClassLabel;       /* XmLabel */
  Widget applClassText;       /* XmText */
  Widget PSLangMenu;       /* XmCreatePulldownMenu */
  Widget langLabel;       /* XmLabel */
  Widget PSLangOptionMenu;       /* XmCreateOptionMenu */
  Widget PSStartLabel;       /* XmLabel */
  Widget PSSourceDirLabel;       /* XmLabel */
  Widget PSSourceDirText;       /* XmText */
  Widget moreSourceFilesButton;       /* XmDrawnButton */
  Widget sourcePathButton;       /* XmDrawnButton */
  Widget PSSourceDirFileSB;       /* XmCreateFileSelectionDialog */
  Widget execFileLabel;       /* XmLabel */
  Widget execFileText;       /* XmText */
  Widget moreSourceLabel;       /* XmLabel */
  Widget moreSourceText;       /* XmText */
  Widget extraCompilerOptionLabel;       /* XmLabel */
  Widget extraCompilerOptionText;       /* XmText */
  Widget extraLinkerOptionLabel;       /* XmLabel */
  Widget extraLinkerOptionText;       /* XmText */
  Widget descriptionLabel;       /* XmLabel */
  Widget descriptionScrolledWindow;       /* XmScrolledWindow */
  Widget descriptionText;       /* XmText */
  Widget selectStartupInterface;       /* XmCreateSelectionDialog */
  Widget moreSourceFilesDialog;       /* XmCreateMessageDialog */
  Widget scrolledWindow_1;       /* XmScrolledWindow */
  Widget sourceFilesList;       /* XmList */
  Widget extraLibrariesText;       /* XmText */
  Widget extraLibrariesLabel;       /* XmLabel */
  Widget startupOptionMenu;       /* XmCreateOptionMenu */
  Widget separator;       /* XmSeparator */
  Widget xlButtonBox;       /* XlButtonBox */
  Widget psOkButton;       /* XmPushButton */
  Widget psCancelButton;       /* XmPushButton */
  Widget psHelpButton;       /* XmPushButton */
  Widget quickHelp;       /* XmLabel */


  static void do_loseFocus_CB(Widget,XtPointer,XtPointer);
  static void PSSourceDirChanged_CB(Widget,XtPointer,XtPointer);
  static void do_setStartupInterface_CB(Widget,XtPointer,XtPointer);
  static void do_mapMoreSourceFiles_CB(Widget,XtPointer,XtPointer);
  static void do_moreSourceFiles_CB(Widget,XtPointer,XtPointer);
  static void do_ok_CB(Widget,XtPointer,XtPointer);
  static void do_cancel_CB(Widget,XtPointer,XtPointer);
  static void do_help_CB(Widget,XtPointer,XtPointer);



  // override the following methods in class ProjectSettings

  virtual void do_loseFocus(Widget,XtPointer) = 0;
  virtual void PSSourceDirChanged(Widget,XtPointer) = 0;
  virtual void do_setStartupInterface(Widget,XtPointer) = 0;
  virtual void do_mapMoreSourceFiles(Widget,XtPointer) = 0;
  virtual void do_moreSourceFiles(Widget,XtPointer) = 0;
  virtual void do_ok(Widget,XtPointer) = 0;
  virtual void do_cancel(Widget,XtPointer) = 0;
  virtual void do_help(Widget,XtPointer) = 0;


public:
  ProjectSettings_base(Widget parent = NULL, ArgList args = NULL, Cardinal n = 0, char
*fbRes = NULL);

  Widget getTop() { return ProjectSettings; }
  Pixmap createPixmapFromData(char **data);
  Pixmap createPixmapFromFile(char *filename);
  static void manageWidget(Widget wg, XtPointer c, XtPointer call);
};

#endif /* Don't add stuff after this #endif */






