/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// ---------------------------------------
// ProjectSettings_base.C
//
// This file was automaticly generated by
// View Designer/X v1.2
//
// User: lazy@apfel
// Date: Tue Jun  2 17:02:48 1998
//
// Don't edit this file, please !
// ---------------------------------------


// Include class definition

#include "ProjectSettings_base.h"

// Include X11 header
#include <X11/xpm.h>

// Include OSF/Motif header files
#include <Xm/Frame.h>
#include <X11/Shell.h>
#include <Xm/Form.h>
#include <lwid/CellTable.h>
#include <Xm/Label.h>
#include <Xm/Text.h>
#include <Xm/RowColumn.h>
#include <Xm/DrawnB.h>
#include <Xm/FileSB.h>
#include <Xm/ScrolledW.h>
#include <Xm/SelectioB.h>
#include <Xm/MessageB.h>
#include <Xm/List.h>
#include <Xm/Separator.h>
#include <lwid/ButtonBox.h>
#include <Xm/PushB.h>








#define RES_CONVERT(t,s) cvtResourceFromString(parent, t, s)


// -----------------------------------
// ProjectSettings_base(parent,args,n)
// -----------------------------------

ProjectSettings_base::ProjectSettings_base(Widget p, ArgList f_args, Cardinal f_n, char *fbRes)
{
  Widget parent;
  Arg args[100];
  Cardinal n = 0;

  if(p) 
    parent = p;
  else
    parent = getTopLevel();

  if(fbRes) {
    XrmDatabase database, fallback;
    
    fallback = XrmGetStringDatabase(fbRes);
    database = XrmGetDatabase(XtDisplay(parent));
    
    XrmCombineDatabase(fallback, &database, FALSE);
  }

  if(!XtIsShell(parent)) {
    ProjectSettings = XtCreateWidget("ProjectSettings",xmFrameWidgetClass,
				       parent,f_args,f_n);
  } else { 
   
    popupShell = ProjectSettings = XtCreatePopupShell("ProjectSettings", topLevelShellWidgetClass,
			parent, args, n);
  }
  createWidgets();
  addCallbacks();
  addRelations();
}


// ----------------------------
// createWidgets()
// ----------------------------

void ProjectSettings_base::createWidgets()
{
  Widget parent;           // the parent for every widget
  Arg args[100];           // resource list
  Cardinal n;              // number of resources

  // Now we create every Widget

  
  /* ---------- Creating Widget:    form -------------- */
  parent = ProjectSettings;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 550); n++;
  XtSetArg(args[n], "width", 400); n++;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  form = XtCreateWidget("form", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(form);
  
  addQuickHelp(form);
  addHelpId(form,44);

  
  /* ---------- Creating Widget:    xlCellTable_1 -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "resizeColumn", 1); n++;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "bottomOffset", 1); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 1); n++;


  /* Creating Widget */
  xlCellTable_1 = XtCreateWidget("xlCellTable_1", xlCellTableWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(xlCellTable_1);
  
  addQuickHelp(xlCellTable_1);
  addHelpId(xlCellTable_1,-1);

  
  /* ---------- Creating Widget:    PSNameLabel -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 10); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "cellColumn", 0); n++;
  XtSetArg(args[n], "cellRow", 0); n++;
  XtSetArg(args[n], "horizontalAlignment", 2); n++;


  /* Creating Widget */
  PSNameLabel = XtCreateWidget("PSNameLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(PSNameLabel);
  
  addQuickHelp(PSNameLabel);
  addHelpId(PSNameLabel,-1);

  
  /* ---------- Creating Widget:    PSNameText -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 90); n++;
  XtSetArg(args[n], "y", 10); n++;
  XtSetArg(args[n], "maxLength", 1024); n++;
  XtSetArg(args[n], "cellColumn", 1); n++;
  XtSetArg(args[n], "cellRow", 0); n++;


  /* Creating Widget */
  PSNameText = XtCreateWidget("PSNameText", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(PSNameText);
  
  addQuickHelp(PSNameText);
  addHelpId(PSNameText,-1);

  
  /* ---------- Creating Widget:    applClassLabel -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 50); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "cellColumn", 0); n++;
  XtSetArg(args[n], "cellRow", 1); n++;
  XtSetArg(args[n], "horizontalAlignment", 2); n++;


  /* Creating Widget */
  applClassLabel = XtCreateWidget("applClassLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(applClassLabel);
  
  addQuickHelp(applClassLabel);
  addHelpId(applClassLabel,-1);

  
  /* ---------- Creating Widget:    applClassText -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 125); n++;
  XtSetArg(args[n], "y", 50); n++;
  XtSetArg(args[n], "maxLength", 1024); n++;
  XtSetArg(args[n], "cellColumn", 1); n++;
  XtSetArg(args[n], "cellRow", 1); n++;


  /* Creating Widget */
  applClassText = XtCreateWidget("applClassText", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(applClassText);
  
  addQuickHelp(applClassText);
  addHelpId(applClassText,-1);

  
  /* ---------- Creating Widget:    PSLangMenu -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 30); n++;
  XtSetArg(args[n], "y", 10); n++;


  /* Creating Widget */
  PSLangMenu = XmCreatePulldownMenu( parent, "PSLangMenu", args, n);
  
  addQuickHelp(PSLangMenu);
  addHelpId(PSLangMenu,-1);

  
  /* ---------- Creating Widget:    langLabel -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 130); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "cellColumn", 0); n++;
  XtSetArg(args[n], "cellRow", 2); n++;
  XtSetArg(args[n], "horizontalAlignment", 2); n++;


  /* Creating Widget */
  langLabel = XtCreateWidget("langLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(langLabel);
  
  addQuickHelp(langLabel);
  addHelpId(langLabel,-1);

  
  /* ---------- Creating Widget:    PSLangOptionMenu -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 130); n++;
  XtSetArg(args[n], "cellColumn", 1); n++;
  XtSetArg(args[n], "cellRow", 2); n++;
  XtSetArg(args[n], "horizontalAlignment", 0); n++;


  /* Creating Widget */
  PSLangOptionMenu = XmCreateOptionMenu( parent, "PSLangOptionMenu", args, n);
  
  /* Manage the Widget */
  XtManageChild(PSLangOptionMenu);
  
  addQuickHelp(PSLangOptionMenu);
  addHelpId(PSLangOptionMenu,-1);

  
  /* ---------- Creating Widget:    PSStartLabel -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 130); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "cellColumn", 0); n++;
  XtSetArg(args[n], "cellRow", 3); n++;
  XtSetArg(args[n], "horizontalAlignment", 2); n++;


  /* Creating Widget */
  PSStartLabel = XtCreateWidget("PSStartLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(PSStartLabel);
  
  addQuickHelp(PSStartLabel);
  addHelpId(PSStartLabel,-1);

  
  /* ---------- Creating Widget:    PSSourceDirLabel -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "cellColumn", 0); n++;
  XtSetArg(args[n], "cellRow", 4); n++;
  XtSetArg(args[n], "horizontalAlignment", 2); n++;


  /* Creating Widget */
  PSSourceDirLabel = XtCreateWidget("PSSourceDirLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(PSSourceDirLabel);
  
  addQuickHelp(PSSourceDirLabel);
  addHelpId(PSSourceDirLabel,-1);

  
  /* ---------- Creating Widget:    PSSourceDirText -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 125); n++;
  XtSetArg(args[n], "y", 90); n++;
  XtSetArg(args[n], "maxLength", 1024); n++;
  XtSetArg(args[n], "cellColumn", 1); n++;
  XtSetArg(args[n], "cellRow", 4); n++;


  /* Creating Widget */
  PSSourceDirText = XtCreateWidget("PSSourceDirText", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(PSSourceDirText);
  
  addQuickHelp(PSSourceDirText);
  addHelpId(PSSourceDirText,-1);

  
  /* ---------- Creating Widget:    moreSourceFilesButton -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "pushButtonEnabled", 1); n++;
  XtSetArg(args[n], "cellColumn", 2); n++;
  XtSetArg(args[n], "cellRow", 6); n++;
  XtSetArg(args[n], "horizontalAlignment", 1); n++;
  XtSetArg(args[n], "verticalAlignment", 1); n++;


  /* Creating Widget */
  moreSourceFilesButton = XtCreateWidget("moreSourceFilesButton", xmDrawnButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(moreSourceFilesButton);
  
  addQuickHelp(moreSourceFilesButton);
  addHelpId(moreSourceFilesButton,-1);

  
  /* ---------- Creating Widget:    sourcePathButton -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "pushButtonEnabled", 1); n++;
  XtSetArg(args[n], "cellColumn", 2); n++;
  XtSetArg(args[n], "cellRow", 4); n++;
  XtSetArg(args[n], "horizontalAlignment", 1); n++;
  XtSetArg(args[n], "verticalAlignment", 1); n++;


  /* Creating Widget */
  sourcePathButton = XtCreateWidget("sourcePathButton", xmDrawnButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(sourcePathButton);
  
  addQuickHelp(sourcePathButton);
  addHelpId(sourcePathButton,-1);

  
  /* ---------- Creating Widget:    PSSourceDirFileSB -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 250); n++;
  XtSetArg(args[n], "y", 180); n++;
  XtSetArg(args[n], "autoUnmanage", 1); n++;
  XtSetArg(args[n], "fileTypeMask", 1); n++;


  /* Creating Widget */
  PSSourceDirFileSB = XmCreateFileSelectionDialog( parent, "PSSourceDirFileSB", args, n);
  
  addQuickHelp(PSSourceDirFileSB);
  addHelpId(PSSourceDirFileSB,-1);

  
  /* ---------- Creating Widget:    execFileLabel -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "cellColumn", 0); n++;
  XtSetArg(args[n], "cellRow", 5); n++;
  XtSetArg(args[n], "horizontalAlignment", 2); n++;


  /* Creating Widget */
  execFileLabel = XtCreateWidget("execFileLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(execFileLabel);
  
  addQuickHelp(execFileLabel);
  addHelpId(execFileLabel,-1);

  
  /* ---------- Creating Widget:    execFileText -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 70); n++;
  XtSetArg(args[n], "y", 170); n++;
  XtSetArg(args[n], "maxLength", 1024); n++;
  XtSetArg(args[n], "cellColumn", 1); n++;
  XtSetArg(args[n], "cellRow", 5); n++;
  XtSetArg(args[n], "horizontalAlignment", 3); n++;


  /* Creating Widget */
  execFileText = XtCreateWidget("execFileText", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(execFileText);
  
  addQuickHelp(execFileText);
  addHelpId(execFileText,-1);

  
  /* ---------- Creating Widget:    moreSourceLabel -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 80); n++;
  XtSetArg(args[n], "y", 180); n++;
  XtSetArg(args[n], "cellColumn", 0); n++;
  XtSetArg(args[n], "cellRow", 6); n++;
  XtSetArg(args[n], "horizontalAlignment", 2); n++;


  /* Creating Widget */
  moreSourceLabel = XtCreateWidget("moreSourceLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(moreSourceLabel);
  
  addQuickHelp(moreSourceLabel);
  addHelpId(moreSourceLabel,-1);

  
  /* ---------- Creating Widget:    moreSourceText -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 80); n++;
  XtSetArg(args[n], "y", 170); n++;
  XtSetArg(args[n], "cellColumn", 1); n++;
  XtSetArg(args[n], "cellRow", 6); n++;


  /* Creating Widget */
  moreSourceText = XtCreateWidget("moreSourceText", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(moreSourceText);
  
  addQuickHelp(moreSourceText);
  addHelpId(moreSourceText,-1);

  
  /* ---------- Creating Widget:    extraCompilerOptionLabel -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 50); n++;
  XtSetArg(args[n], "y", 260); n++;
  XtSetArg(args[n], "cellColumn", 0); n++;
  XtSetArg(args[n], "cellRow", 7); n++;
  XtSetArg(args[n], "horizontalAlignment", 2); n++;


  /* Creating Widget */
  extraCompilerOptionLabel = XtCreateWidget("extraCompilerOptionLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(extraCompilerOptionLabel);
  
  addQuickHelp(extraCompilerOptionLabel);
  addHelpId(extraCompilerOptionLabel,-1);

  
  /* ---------- Creating Widget:    extraCompilerOptionText -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 100); n++;
  XtSetArg(args[n], "y", 290); n++;
  XtSetArg(args[n], "cellColumn", 1); n++;
  XtSetArg(args[n], "cellRow", 7); n++;


  /* Creating Widget */
  extraCompilerOptionText = XtCreateWidget("extraCompilerOptionText", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(extraCompilerOptionText);
  
  addQuickHelp(extraCompilerOptionText);
  addHelpId(extraCompilerOptionText,-1);

  
  /* ---------- Creating Widget:    extraLinkerOptionLabel -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 50); n++;
  XtSetArg(args[n], "y", 250); n++;
  XtSetArg(args[n], "cellColumn", 0); n++;
  XtSetArg(args[n], "cellRow", 8); n++;
  XtSetArg(args[n], "horizontalAlignment", 2); n++;


  /* Creating Widget */
  extraLinkerOptionLabel = XtCreateWidget("extraLinkerOptionLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(extraLinkerOptionLabel);
  
  addQuickHelp(extraLinkerOptionLabel);
  addHelpId(extraLinkerOptionLabel,-1);

  
  /* ---------- Creating Widget:    extraLinkerOptionText -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 60); n++;
  XtSetArg(args[n], "y", 260); n++;
  XtSetArg(args[n], "cellColumn", 1); n++;
  XtSetArg(args[n], "cellRow", 8); n++;


  /* Creating Widget */
  extraLinkerOptionText = XtCreateWidget("extraLinkerOptionText", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(extraLinkerOptionText);
  
  addQuickHelp(extraLinkerOptionText);
  addHelpId(extraLinkerOptionText,-1);

  
  /* ---------- Creating Widget:    descriptionLabel -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 30); n++;
  XtSetArg(args[n], "x", 53); n++;
  XtSetArg(args[n], "y", 333); n++;
  XtSetArg(args[n], "cellColumn", 0); n++;
  XtSetArg(args[n], "cellRow", 10); n++;
  XtSetArg(args[n], "horizontalAlignment", 2); n++;
  XtSetArg(args[n], "verticalAlignment", 0); n++;


  /* Creating Widget */
  descriptionLabel = XtCreateWidget("descriptionLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(descriptionLabel);
  
  addQuickHelp(descriptionLabel);
  addHelpId(descriptionLabel,-1);

  
  /* ---------- Creating Widget:    descriptionScrolledWindow -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 70); n++;
  XtSetArg(args[n], "y", 280); n++;
  XtSetArg(args[n], "cellColumn", 1); n++;
  XtSetArg(args[n], "cellRow", 10); n++;


  /* Creating Widget */
  descriptionScrolledWindow = XtCreateWidget("descriptionScrolledWindow", xmScrolledWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(descriptionScrolledWindow);
  
  addQuickHelp(descriptionScrolledWindow);
  addHelpId(descriptionScrolledWindow,-1);

  
  /* ---------- Creating Widget:    descriptionText -------------- */
  parent = descriptionScrolledWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 20); n++;
  XtSetArg(args[n], "y", 10); n++;
  XtSetArg(args[n], "editMode", 0); n++;
  XtSetArg(args[n], "scrollHorizontal", 0); n++;
  XtSetArg(args[n], "wordWrap", 1); n++;


  /* Creating Widget */
  descriptionText = XtCreateWidget("descriptionText", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(descriptionText);
  
  addQuickHelp(descriptionText);
  addHelpId(descriptionText,-1);

  
  /* ---------- Creating Widget:    selectStartupInterface -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "dialogTitle", RES_CONVERT("XmString", "Select Startup Interface")); n++;
  XtSetArg(args[n], "listLabelString", RES_CONVERT("XmString", "Interfaces:")); n++;
  XtSetArg(args[n], "selectionLabelString", RES_CONVERT("XmString", "Startup Interface")); n++;


  /* Creating Widget */
  selectStartupInterface = XmCreateSelectionDialog( parent, "selectStartupInterface", args, n);
  
  addQuickHelp(selectStartupInterface);
  addHelpId(selectStartupInterface,-1);

  
  /* ---------- Creating Widget:    moreSourceFilesDialog -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 270); n++;
  XtSetArg(args[n], "width", 260); n++;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "dialogTitle", RES_CONVERT("XmString", "Select Additional Source Files")); n++;
  XtSetArg(args[n], "messageString", RES_CONVERT("XmString", "Sources in Source Directory:")); n++;


  /* Creating Widget */
  moreSourceFilesDialog = XmCreateMessageDialog( parent, "moreSourceFilesDialog", args, n);
  
  addQuickHelp(moreSourceFilesDialog);
  addHelpId(moreSourceFilesDialog,-1);

  
  /* ---------- Creating Widget:    scrolledWindow_1 -------------- */
  parent = moreSourceFilesDialog;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 100); n++;
  XtSetArg(args[n], "width", 100); n++;
  XtSetArg(args[n], "x", 50); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  scrolledWindow_1 = XtCreateWidget("scrolledWindow_1", xmScrolledWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(scrolledWindow_1);
  
  addQuickHelp(scrolledWindow_1);
  addHelpId(scrolledWindow_1,-1);

  
  /* ---------- Creating Widget:    sourceFilesList -------------- */
  parent = scrolledWindow_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 90); n++;
  XtSetArg(args[n], "width", 200); n++;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "selectionPolicy", 1); n++;


  /* Creating Widget */
  sourceFilesList = XtCreateWidget("sourceFilesList", xmListWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(sourceFilesList);
  
  addQuickHelp(sourceFilesList);
  addHelpId(sourceFilesList,-1);

  
  /* ---------- Creating Widget:    extraLibrariesText -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 150); n++;
  XtSetArg(args[n], "y", 300); n++;
  XtSetArg(args[n], "cellColumn", 1); n++;
  XtSetArg(args[n], "cellRow", 9); n++;


  /* Creating Widget */
  extraLibrariesText = XtCreateWidget("extraLibrariesText", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(extraLibrariesText);
  
  addQuickHelp(extraLibrariesText);
  addHelpId(extraLibrariesText,-1);

  
  /* ---------- Creating Widget:    extraLibrariesLabel -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 50); n++;
  XtSetArg(args[n], "y", 250); n++;
  XtSetArg(args[n], "cellColumn", 0); n++;
  XtSetArg(args[n], "cellRow", 9); n++;
  XtSetArg(args[n], "horizontalAlignment", 2); n++;


  /* Creating Widget */
  extraLibrariesLabel = XtCreateWidget("extraLibrariesLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(extraLibrariesLabel);
  
  addQuickHelp(extraLibrariesLabel);
  addHelpId(extraLibrariesLabel,-1);

  
  /* ---------- Creating Widget:    startupOptionMenu -------------- */
  parent = xlCellTable_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 160); n++;
  XtSetArg(args[n], "y", 100); n++;
  XtSetArg(args[n], "cellColumn", 1); n++;
  XtSetArg(args[n], "cellRow", 3); n++;
  XtSetArg(args[n], "horizontalAlignment", 0); n++;


  /* Creating Widget */
  startupOptionMenu = XmCreateOptionMenu( parent, "startupOptionMenu", args, n);
  
  /* Manage the Widget */
  XtManageChild(startupOptionMenu);
  
  addQuickHelp(startupOptionMenu);
  addHelpId(startupOptionMenu,-1);

  
  /* ---------- Creating Widget:    separator -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "bottomOffset", 1); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;


  /* Creating Widget */
  separator = XtCreateWidget("separator", xmSeparatorWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(separator);
  
  addQuickHelp(separator);
  addHelpId(separator,-1);

  
  /* ---------- Creating Widget:    xlButtonBox -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "entryMarginWidth", 10); n++;
  XtSetArg(args[n], "spacing", 5); n++;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "bottomOffset", 1); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 10); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 10); n++;


  /* Creating Widget */
  xlButtonBox = XtCreateWidget("xlButtonBox", xlButtonBoxWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(xlButtonBox);
  
  addQuickHelp(xlButtonBox);
  addHelpId(xlButtonBox,-1);

  
  /* ---------- Creating Widget:    psOkButton -------------- */
  parent = xlButtonBox;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 29); n++;
  XtSetArg(args[n], "width", 80); n++;
  XtSetArg(args[n], "x", 5); n++;
  XtSetArg(args[n], "y", 5); n++;


  /* Creating Widget */
  psOkButton = XtCreateWidget("psOkButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(psOkButton);
  
  addQuickHelp(psOkButton);
  addHelpId(psOkButton,-1);

  
  /* ---------- Creating Widget:    psCancelButton -------------- */
  parent = xlButtonBox;

  /* Building resource list */
  n = 0;


  /* Creating Widget */
  psCancelButton = XtCreateWidget("psCancelButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(psCancelButton);
  
  addQuickHelp(psCancelButton);
  addHelpId(psCancelButton,-1);

  
  /* ---------- Creating Widget:    psHelpButton -------------- */
  parent = xlButtonBox;

  /* Building resource list */
  n = 0;


  /* Creating Widget */
  psHelpButton = XtCreateWidget("psHelpButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(psHelpButton);
  
  addQuickHelp(psHelpButton);
  addHelpId(psHelpButton,-1);

  
  /* ---------- Creating Widget:    quickHelp -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "bottomAttachment", 1); n++;
  XtSetArg(args[n], "bottomOffset", 1); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;


  /* Creating Widget */
  quickHelp = XtCreateWidget("quickHelp", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(quickHelp);
  
  addQuickHelp(quickHelp);
  addHelpId(quickHelp,-1);


}



// ----------------------------
// addCallbacks()
// ----------------------------

void ProjectSettings_base::addCallbacks()
{

  XtAddCallback( PSNameText, "losingFocusCallback",
                 do_loseFocus_CB, this);

  XtAddCallback( moreSourceFilesButton, "activateCallback",
                 manageWidget, (XtPointer)moreSourceFilesDialog); 

  XtAddCallback( sourcePathButton, "activateCallback",
                 manageWidget, (XtPointer)PSSourceDirFileSB); 

  XtAddCallback( PSSourceDirFileSB, "okCallback",
                 PSSourceDirChanged_CB, this);

  XtAddCallback( selectStartupInterface, "okCallback",
                 do_setStartupInterface_CB, this);

  XtAddCallback( moreSourceFilesDialog, "mapCallback",
                 do_mapMoreSourceFiles_CB, this);

  XtAddCallback( moreSourceFilesDialog, "okCallback",
                 do_moreSourceFiles_CB, this);

  XtAddCallback( psOkButton, "activateCallback",
                 do_ok_CB, this);

  XtAddCallback( psCancelButton, "activateCallback",
                 do_cancel_CB, this);

  XtAddCallback( psHelpButton, "activateCallback",
                 do_help_CB, this);

}



// ----------------------------
// addRelations()
// ----------------------------

void ProjectSettings_base::addRelations()
{
  XtVaSetValues(xlCellTable_1, "bottomWidget", separator, NULL);

  XtVaSetValues(separator, "bottomWidget", xlButtonBox, NULL);

  XtVaSetValues(xlButtonBox, "bottomWidget", quickHelp, NULL);


}


// ----------------------------
// manageWidget()
// ----------------------------
void ProjectSettings_base::manageWidget(Widget, XtPointer c, XtPointer)
{
  XtManageChild((Widget)c);
}


// ----------------------------
// createPixmapFromData()
// ----------------------------

Pixmap ProjectSettings_base::createPixmapFromData(char **data)
{
  Pixmap pix, mask;
  XpmAttributes attr;

  memset(&attr, 0, sizeof(attr));
  attr.valuemask = XpmReturnPixels;

  if( !XpmCreatePixmapFromData(XtDisplay(LicView::getTopLevel()),
		               XRootWindowOfScreen(XtScreen(LicView::getTopLevel())),
			       data,
			       &pix, &mask, &attr) )
    return pix;
  return XmUNSPECIFIED_PIXMAP;
}

// ------------------------------------------
// createPixmapFromFile()
//
// Creating a pixmap by XpmRaedFileToPixmap()
// Uses XFILESEARCHPATH to find the pixmap
// default path: /usr/lib/X11/pixmaps/%N.xpm
// ------------------------------------------

Pixmap ProjectSettings_base::createPixmapFromFile(char *name)
{
  String string;
  Pixmap pix, mask;
  XpmAttributes attr;

  string = XtResolvePathname(XtDisplay(LicView::getTopLevel()),
			     "pixmaps", name, "", NULL,
			     NULL, 0, NULL);
  if(string) {
    memset(&attr, 0, sizeof(attr));
    attr.valuemask = XpmReturnPixels;
    if( !XpmReadFileToPixmap(XtDisplay(LicView::getTopLevel()),
			     XRootWindowOfScreen(
			     XtScreen(LicView::getTopLevel())),
			     string,
			     &pix, &mask, &attr) )
      return pix;
    return XmUNSPECIFIED_PIXMAP;
    XtFree(string);
  }
  return XmUNSPECIFIED_PIXMAP;
}

// ---------------------------------------------------------
// Following class method are used as a callback.
// The method is calling a abstract virtual method, which
// must be overloaded in the derived class 'ProjectSettings'
// ---------------------------------------------------------

void ProjectSettings_base::do_loseFocus_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ProjectSettings_base*)clientData)->do_loseFocus(wg,callData);
}

void ProjectSettings_base::PSSourceDirChanged_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ProjectSettings_base*)clientData)->PSSourceDirChanged(wg,callData);
}

void ProjectSettings_base::do_setStartupInterface_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ProjectSettings_base*)clientData)->do_setStartupInterface(wg,callData);
}

void ProjectSettings_base::do_mapMoreSourceFiles_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ProjectSettings_base*)clientData)->do_mapMoreSourceFiles(wg,callData);
}

void ProjectSettings_base::do_moreSourceFiles_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ProjectSettings_base*)clientData)->do_moreSourceFiles(wg,callData);
}

void ProjectSettings_base::do_ok_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ProjectSettings_base*)clientData)->do_ok(wg,callData);
}

void ProjectSettings_base::do_cancel_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ProjectSettings_base*)clientData)->do_cancel(wg,callData);
}

void ProjectSettings_base::do_help_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ProjectSettings_base*)clientData)->do_help(wg,callData);
}


