/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// ---------------------------------------
// TextEdit_base.C
//
// This file was automaticly generated by
// View Designer/X v1.2
//
// User: lazy@apfel
// Date: Tue Jun  2 17:02:47 1998
//
// Don't edit this file, please !
// ---------------------------------------


// Include class definition

#include "TextEdit_base.h"

// Include X11 header
#include <X11/xpm.h>

// Include OSF/Motif header files
#include <Xm/Frame.h>
#include <X11/Shell.h>
#include <Xm/Form.h>
#include <Xm/RowColumn.h>
#include <Xm/CascadeB.h>
#include <Xm/PushB.h>
#include <Xm/Separator.h>
#include <Xm/FileSB.h>
#include <Xm/ScrolledW.h>
#include <Xm/Text.h>
#include <Xm/Label.h>








#define RES_CONVERT(t,s) cvtResourceFromString(parent, t, s)


// -----------------------------------
// TextEdit_base(parent,args,n)
// -----------------------------------

TextEdit_base::TextEdit_base(Widget p, ArgList f_args, Cardinal f_n, char *fbRes)
{
  Widget parent;
  Arg args[100];
  Cardinal n = 0;

  if(p) 
    parent = p;
  else
    parent = getTopLevel();

  if(fbRes) {
    XrmDatabase database, fallback;
    
    fallback = XrmGetStringDatabase(fbRes);
    database = XrmGetDatabase(XtDisplay(parent));
    
    XrmCombineDatabase(fallback, &database, FALSE);
  }

  if(!XtIsShell(parent)) {
    TextEdit = XtCreateWidget("TextEdit",xmFrameWidgetClass,
				       parent,f_args,f_n);
  } else { 
     XtSetArg(args[n], "iconPixmap", createPixmapFromFile("TextEdit.xpm")); n++;

    popupShell = TextEdit = XtCreatePopupShell("TextEdit", topLevelShellWidgetClass,
			parent, args, n);
  }
  createWidgets();
  addCallbacks();
  addRelations();
}


// ----------------------------
// createWidgets()
// ----------------------------

void TextEdit_base::createWidgets()
{
  Widget parent;           // the parent for every widget
  Arg args[100];           // resource list
  Cardinal n;              // number of resources

  // Now we create every Widget

  
  /* ---------- Creating Widget:    form -------------- */
  parent = TextEdit;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 247); n++;
  XtSetArg(args[n], "width", 502); n++;
  XtSetArg(args[n], "x", 420); n++;
  XtSetArg(args[n], "y", 340); n++;


  /* Creating Widget */
  form = XtCreateWidget("form", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(form);
  
  addQuickHelp(form);
  addHelpId(form,13);

  
  /* ---------- Creating Widget:    menuBar -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 31); n++;
  XtSetArg(args[n], "width", 500); n++;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 1); n++;


  /* Creating Widget */
  menuBar = XmCreateMenuBar( parent, "menuBar", args, n);
  
  /* Manage the Widget */
  XtManageChild(menuBar);
  
  addQuickHelp(menuBar);
  addHelpId(menuBar,-1);

  
  /* ---------- Creating Widget:    fileMenuButton -------------- */
  parent = menuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileMenuButton = XtCreateWidget("fileMenuButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(fileMenuButton);
  
  addQuickHelp(fileMenuButton);
  addHelpId(fileMenuButton,-1);

  
  /* ---------- Creating Widget:    fileMenu -------------- */
  parent = menuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileMenu = XmCreatePulldownMenu( parent, "fileMenu", args, n);
  
  addQuickHelp(fileMenu);
  addHelpId(fileMenu,-1);

  
  /* ---------- Creating Widget:    fileImport -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileImport = XtCreateWidget("fileImport", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(fileImport);
  
  addQuickHelp(fileImport);
  addHelpId(fileImport,-1);

  
  /* ---------- Creating Widget:    fileExport -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileExport = XtCreateWidget("fileExport", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(fileExport);
  
  addQuickHelp(fileExport);
  addHelpId(fileExport,-1);

  
  /* ---------- Creating Widget:    XmSeparator -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  XmSeparator = XtCreateWidget("XmSeparator", xmSeparatorWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(XmSeparator);
  
  addQuickHelp(XmSeparator);
  addHelpId(XmSeparator,-1);

  
  /* ---------- Creating Widget:    fileCloseAndSave -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileCloseAndSave = XtCreateWidget("fileCloseAndSave", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(fileCloseAndSave);
  
  addQuickHelp(fileCloseAndSave);
  addHelpId(fileCloseAndSave,-1);

  
  /* ---------- Creating Widget:    fileClose -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileClose = XtCreateWidget("fileClose", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(fileClose);
  
  addQuickHelp(fileClose);
  addHelpId(fileClose,-1);

  
  /* ---------- Creating Widget:    editMenuButton -------------- */
  parent = menuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  editMenuButton = XtCreateWidget("editMenuButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(editMenuButton);
  
  addQuickHelp(editMenuButton);
  addHelpId(editMenuButton,-1);

  
  /* ---------- Creating Widget:    editMenu -------------- */
  parent = menuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  editMenu = XmCreatePulldownMenu( parent, "editMenu", args, n);
  
  addQuickHelp(editMenu);
  addHelpId(editMenu,-1);

  
  /* ---------- Creating Widget:    editCut -------------- */
  parent = editMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  editCut = XtCreateWidget("editCut", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(editCut);
  
  addQuickHelp(editCut);
  addHelpId(editCut,-1);

  
  /* ---------- Creating Widget:    editCopy -------------- */
  parent = editMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  editCopy = XtCreateWidget("editCopy", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(editCopy);
  
  addQuickHelp(editCopy);
  addHelpId(editCopy,-1);

  
  /* ---------- Creating Widget:    editPaste -------------- */
  parent = editMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  editPaste = XtCreateWidget("editPaste", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(editPaste);
  
  addQuickHelp(editPaste);
  addHelpId(editPaste,-1);

  
  /* ---------- Creating Widget:    helpMenuButton -------------- */
  parent = menuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  helpMenuButton = XtCreateWidget("helpMenuButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(helpMenuButton);
  
  addQuickHelp(helpMenuButton);
  addHelpId(helpMenuButton,-1);

  
  /* ---------- Creating Widget:    helpMenu -------------- */
  parent = menuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  helpMenu = XmCreatePulldownMenu( parent, "helpMenu", args, n);
  
  addQuickHelp(helpMenu);
  addHelpId(helpMenu,-1);

  
  /* ---------- Creating Widget:    onHelp -------------- */
  parent = helpMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  onHelp = XtCreateWidget("onHelp", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(onHelp);
  
  addQuickHelp(onHelp);
  addHelpId(onHelp,-1);

  
  /* ---------- Creating Widget:    onContext -------------- */
  parent = helpMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  onContext = XtCreateWidget("onContext", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(onContext);
  
  addQuickHelp(onContext);
  addHelpId(onContext,-1);

  
  /* ---------- Creating Widget:    helpHelp -------------- */
  parent = helpMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  helpHelp = XtCreateWidget("helpHelp", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(helpHelp);
  
  addQuickHelp(helpHelp);
  addHelpId(helpHelp,-1);

  
  /* ---------- Creating Widget:    fileImportDialog -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 140); n++;
  XtSetArg(args[n], "y", 70); n++;
  XtSetArg(args[n], "autoUnmanage", 1); n++;


  /* Creating Widget */
  fileImportDialog = XmCreateFileSelectionDialog( parent, "fileImportDialog", args, n);
  
  addQuickHelp(fileImportDialog);
  addHelpId(fileImportDialog,-1);

  
  /* ---------- Creating Widget:    fileExportDialog -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 170); n++;
  XtSetArg(args[n], "y", 70); n++;
  XtSetArg(args[n], "autoUnmanage", 1); n++;


  /* Creating Widget */
  fileExportDialog = XmCreateFileSelectionDialog( parent, "fileExportDialog", args, n);
  
  addQuickHelp(fileExportDialog);
  addHelpId(fileExportDialog,-1);

  
  /* ---------- Creating Widget:    scrolledWindow -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 193); n++;
  XtSetArg(args[n], "width", 500); n++;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 30); n++;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;
  XtSetArg(args[n], "topAttachment", 3); n++;
  XtSetArg(args[n], "topOffset", 0); n++;


  /* Creating Widget */
  scrolledWindow = XtCreateWidget("scrolledWindow", xmScrolledWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(scrolledWindow);
  
  addQuickHelp(scrolledWindow);
  addHelpId(scrolledWindow,-1);

  
  /* ---------- Creating Widget:    text -------------- */
  parent = scrolledWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 50); n++;
  XtSetArg(args[n], "y", 20); n++;
  XtSetArg(args[n], "editMode", 0); n++;


  /* Creating Widget */
  text = XtCreateWidget("text", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(text);
  
  addQuickHelp(text);
  addHelpId(text,-1);

  
  /* ---------- Creating Widget:    quickHelpLabel -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 20); n++;
  XtSetArg(args[n], "width", 490); n++;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 210); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "bottomAttachment", 1); n++;
  XtSetArg(args[n], "bottomOffset", 1); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;


  /* Creating Widget */
  quickHelpLabel = XtCreateWidget("quickHelpLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(quickHelpLabel);
  
  addQuickHelp(quickHelpLabel);
  addHelpId(quickHelpLabel,-1);


}



// ----------------------------
// addCallbacks()
// ----------------------------

void TextEdit_base::addCallbacks()
{

  XtAddCallback( fileImport, "activateCallback",
                 manageWidget, (XtPointer)fileImportDialog); 

  XtAddCallback( fileExport, "activateCallback",
                 manageWidget, (XtPointer)fileExportDialog); 

  XtAddCallback( fileCloseAndSave, "activateCallback",
                 saveAndExit_CB, this);

  XtAddCallback( fileClose, "activateCallback",
                 doExit_CB, this);

  XtAddCallback( editCut, "activateCallback",
                 cutText_CB, this);

  XtAddCallback( editCopy, "activateCallback",
                 copyText_CB, this);

  XtAddCallback( editPaste, "activateCallback",
                 pasteText_CB, this);

  XtAddCallback( onHelp, "activateCallback",
                 do_onHelp_CB, this);

  XtAddCallback( onContext, "activateCallback",
                 do_onContext_CB, this);

  XtAddCallback( helpHelp, "activateCallback",
                 helpMe_CB, this);

  XtAddCallback( fileImportDialog, "okCallback",
                 importFile_CB, this);

  XtAddCallback( fileExportDialog, "okCallback",
                 exportFile_CB, this);

}



// ----------------------------
// addRelations()
// ----------------------------

void TextEdit_base::addRelations()
{
  XtVaSetValues(menuBar, "menuHelpWidget", helpMenuButton, NULL);

  XtVaSetValues(fileMenuButton, "subMenuId", fileMenu, NULL);

  XtVaSetValues(editMenuButton, "subMenuId", editMenu, NULL);

  XtVaSetValues(helpMenuButton, "subMenuId", helpMenu, NULL);

  XtVaSetValues(scrolledWindow, "bottomWidget", quickHelpLabel, NULL);

  XtVaSetValues(scrolledWindow, "topWidget", menuBar, NULL);


}


// ----------------------------
// manageWidget()
// ----------------------------
void TextEdit_base::manageWidget(Widget, XtPointer c, XtPointer)
{
  XtManageChild((Widget)c);
}


// ----------------------------
// createPixmapFromData()
// ----------------------------

Pixmap TextEdit_base::createPixmapFromData(char **data)
{
  Pixmap pix, mask;
  XpmAttributes attr;

  memset(&attr, 0, sizeof(attr));
  attr.valuemask = XpmReturnPixels;

  if( !XpmCreatePixmapFromData(XtDisplay(LicView::getTopLevel()),
		               XRootWindowOfScreen(XtScreen(LicView::getTopLevel())),
			       data,
			       &pix, &mask, &attr) )
    return pix;
  return XmUNSPECIFIED_PIXMAP;
}

// ------------------------------------------
// createPixmapFromFile()
//
// Creating a pixmap by XpmRaedFileToPixmap()
// Uses XFILESEARCHPATH to find the pixmap
// default path: /usr/lib/X11/pixmaps/%N.xpm
// ------------------------------------------

Pixmap TextEdit_base::createPixmapFromFile(char *name)
{
  String string;
  Pixmap pix, mask;
  XpmAttributes attr;

  string = XtResolvePathname(XtDisplay(LicView::getTopLevel()),
			     "pixmaps", name, "", NULL,
			     NULL, 0, NULL);
  if(string) {
    memset(&attr, 0, sizeof(attr));
    attr.valuemask = XpmReturnPixels;
    if( !XpmReadFileToPixmap(XtDisplay(LicView::getTopLevel()),
			     XRootWindowOfScreen(
			     XtScreen(LicView::getTopLevel())),
			     string,
			     &pix, &mask, &attr) )
      return pix;
    return XmUNSPECIFIED_PIXMAP;
    XtFree(string);
  }
  return XmUNSPECIFIED_PIXMAP;
}

// ---------------------------------------------------------
// Following class method are used as a callback.
// The method is calling a abstract virtual method, which
// must be overloaded in the derived class 'TextEdit'
// ---------------------------------------------------------

void TextEdit_base::saveAndExit_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextEdit_base*)clientData)->saveAndExit(wg,callData);
}

void TextEdit_base::doExit_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextEdit_base*)clientData)->doExit(wg,callData);
}

void TextEdit_base::cutText_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextEdit_base*)clientData)->cutText(wg,callData);
}

void TextEdit_base::copyText_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextEdit_base*)clientData)->copyText(wg,callData);
}

void TextEdit_base::pasteText_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextEdit_base*)clientData)->pasteText(wg,callData);
}

void TextEdit_base::do_onHelp_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextEdit_base*)clientData)->do_onHelp(wg,callData);
}

void TextEdit_base::do_onContext_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextEdit_base*)clientData)->do_onContext(wg,callData);
}

void TextEdit_base::helpMe_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextEdit_base*)clientData)->helpMe(wg,callData);
}

void TextEdit_base::importFile_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextEdit_base*)clientData)->importFile(wg,callData);
}

void TextEdit_base::exportFile_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextEdit_base*)clientData)->exportFile(wg,callData);
}


