/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// ---------------------------------------
// TransformDialog_base.C
//
// This file was automaticly generated by
// View Designer/X v1.2
//
// User: lazy@apfel
// Date: Tue Jun  2 17:02:50 1998
//
// Don't edit this file, please !
// ---------------------------------------


// Include class definition

#include "TransformDialog_base.h"

// Include X11 header
#include <X11/xpm.h>

// Include OSF/Motif header files
#include <Xm/Frame.h>
#include <X11/Shell.h>
#include <Xm/MessageB.h>
#include <Xm/RowColumn.h>
#include <Xm/PushB.h>








#define RES_CONVERT(t,s) cvtResourceFromString(parent, t, s)


// -----------------------------------
// TransformDialog_base(parent,args,n)
// -----------------------------------

TransformDialog_base::TransformDialog_base(Widget p, ArgList f_args, Cardinal f_n, char *fbRes)
{
  Widget parent;
  Arg args[100];
  Cardinal n = 0;

  if(p) 
    parent = p;
  else
    parent = getTopLevel();

  if(fbRes) {
    XrmDatabase database, fallback;
    
    fallback = XrmGetStringDatabase(fbRes);
    database = XrmGetDatabase(XtDisplay(parent));
    
    XrmCombineDatabase(fallback, &database, FALSE);
  }

  if(!XtIsShell(parent)) {
    TransformDialog = XtCreateWidget("TransformDialog",xmFrameWidgetClass,
				       parent,f_args,f_n);
  } else { 
   
    popupShell = TransformDialog = XtCreatePopupShell("TransformDialog", topLevelShellWidgetClass,
			parent, args, n);
  }
  createWidgets();
  addCallbacks();
  addRelations();
}


// ----------------------------
// createWidgets()
// ----------------------------

void TransformDialog_base::createWidgets()
{
  Widget parent;           // the parent for every widget
  Arg args[100];           // resource list
  Cardinal n;              // number of resources

  // Now we create every Widget

  
  /* ---------- Creating Widget:    messageBox -------------- */
  parent = TransformDialog;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "okLabelString", RES_CONVERT("XmString", "Transform")); n++;


  /* Creating Widget */
  messageBox = XtCreateWidget("messageBox", xmMessageBoxWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(messageBox);
  
  addQuickHelp(messageBox);
  addHelpId(messageBox,47);

  
  /* ---------- Creating Widget:    widgetClassOptionMenu -------------- */
  parent = messageBox;

  /* Building resource list */
  n = 0;


  /* Creating Widget */
  widgetClassOptionMenu = XmCreateOptionMenu( parent, "widgetClassOptionMenu", args, n);
  
  /* Manage the Widget */
  XtManageChild(widgetClassOptionMenu);
  
  addQuickHelp(widgetClassOptionMenu);
  addHelpId(widgetClassOptionMenu,-1);

  
  /* ---------- Creating Widget:    pulldownMenu -------------- */
  parent = widgetClassOptionMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 150); n++;
  XtSetArg(args[n], "y", 10); n++;
  XtSetArg(args[n], "numColumns", 4); n++;
  XtSetArg(args[n], "orientation", 1); n++;
  XtSetArg(args[n], "packing", 2); n++;


  /* Creating Widget */
  pulldownMenu = XmCreatePulldownMenu( parent, "pulldownMenu", args, n);
  
  addQuickHelp(pulldownMenu);
  addHelpId(pulldownMenu,-1);

  
  /* ---------- Creating Widget:    pushButton -------------- */
  parent = pulldownMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  pushButton = XtCreateWidget("pushButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(pushButton);
  
  addQuickHelp(pushButton);
  addHelpId(pushButton,-1);


}



// ----------------------------
// addCallbacks()
// ----------------------------

void TransformDialog_base::addCallbacks()
{

  XtAddCallback( messageBox, "cancelCallback",
                 do_cancel_CB, this);

  XtAddCallback( messageBox, "okCallback",
                 do_ok_CB, this);

}



// ----------------------------
// addRelations()
// ----------------------------

void TransformDialog_base::addRelations()
{
  XtVaSetValues(widgetClassOptionMenu, "subMenuId", pulldownMenu, NULL);


}


// ----------------------------
// manageWidget()
// ----------------------------
void TransformDialog_base::manageWidget(Widget, XtPointer c, XtPointer)
{
  XtManageChild((Widget)c);
}


// ----------------------------
// createPixmapFromData()
// ----------------------------

Pixmap TransformDialog_base::createPixmapFromData(char **data)
{
  Pixmap pix, mask;
  XpmAttributes attr;

  memset(&attr, 0, sizeof(attr));
  attr.valuemask = XpmReturnPixels;

  if( !XpmCreatePixmapFromData(XtDisplay(LicView::getTopLevel()),
		               XRootWindowOfScreen(XtScreen(LicView::getTopLevel())),
			       data,
			       &pix, &mask, &attr) )
    return pix;
  return XmUNSPECIFIED_PIXMAP;
}

// ------------------------------------------
// createPixmapFromFile()
//
// Creating a pixmap by XpmRaedFileToPixmap()
// Uses XFILESEARCHPATH to find the pixmap
// default path: /usr/lib/X11/pixmaps/%N.xpm
// ------------------------------------------

Pixmap TransformDialog_base::createPixmapFromFile(char *name)
{
  String string;
  Pixmap pix, mask;
  XpmAttributes attr;

  string = XtResolvePathname(XtDisplay(LicView::getTopLevel()),
			     "pixmaps", name, "", NULL,
			     NULL, 0, NULL);
  if(string) {
    memset(&attr, 0, sizeof(attr));
    attr.valuemask = XpmReturnPixels;
    if( !XpmReadFileToPixmap(XtDisplay(LicView::getTopLevel()),
			     XRootWindowOfScreen(
			     XtScreen(LicView::getTopLevel())),
			     string,
			     &pix, &mask, &attr) )
      return pix;
    return XmUNSPECIFIED_PIXMAP;
    XtFree(string);
  }
  return XmUNSPECIFIED_PIXMAP;
}

// ---------------------------------------------------------
// Following class method are used as a callback.
// The method is calling a abstract virtual method, which
// must be overloaded in the derived class 'TransformDialog'
// ---------------------------------------------------------

void TransformDialog_base::do_cancel_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TransformDialog_base*)clientData)->do_cancel(wg,callData);
}

void TransformDialog_base::do_ok_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TransformDialog_base*)clientData)->do_ok(wg,callData);
}


