/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// ---------------------------------------
// WidBrowseView_base.C
//
// This file was automaticly generated by
// View Designer/X v1.2
//
// User: lazy@apfel
// Date: Tue Jun  2 17:02:48 1998
//
// Don't edit this file, please !
// ---------------------------------------


// Include class definition

#include "WidBrowseView_base.h"

// Include X11 header
#include <X11/xpm.h>

// Include OSF/Motif header files
#include <Xm/Frame.h>
#include <X11/Shell.h>
#include <Xm/MainW.h>
#include <Xm/RowColumn.h>
#include <Xm/CascadeB.h>
#include <Xm/PushB.h>
#include <Xm/ToggleB.h>
#include <Xm/Separator.h>
#include <Xm/Form.h>
#include <Xm/Label.h>
#include <Xm/Frame.h>








#define RES_CONVERT(t,s) cvtResourceFromString(parent, t, s)


// -----------------------------------
// WidBrowseView_base(parent,args,n)
// -----------------------------------

WidBrowseView_base::WidBrowseView_base(Widget p, ArgList f_args, Cardinal f_n, char *fbRes)
{
  Widget parent;
  Arg args[100];
  Cardinal n = 0;

  if(p) 
    parent = p;
  else
    parent = getTopLevel();

  if(fbRes) {
    XrmDatabase database, fallback;
    
    fallback = XrmGetStringDatabase(fbRes);
    database = XrmGetDatabase(XtDisplay(parent));
    
    XrmCombineDatabase(fallback, &database, FALSE);
  }

  if(!XtIsShell(parent)) {
    WidBrowseView = XtCreateWidget("WidBrowseView",xmFrameWidgetClass,
				       parent,f_args,f_n);
  } else { 
     XtSetArg(args[n], "iconPixmap", createPixmapFromFile("BrowserLogo.xpm")); n++;

    popupShell = WidBrowseView = XtCreatePopupShell("WidBrowseView", topLevelShellWidgetClass,
			parent, args, n);
  }
  createWidgets();
  addCallbacks();
  addRelations();
}


// ----------------------------
// createWidgets()
// ----------------------------

void WidBrowseView_base::createWidgets()
{
  Widget parent;           // the parent for every widget
  Arg args[100];           // resource list
  Cardinal n;              // number of resources

  // Now we create every Widget

  
  /* ---------- Creating Widget:    widBrowseMainWindow -------------- */
  parent = WidBrowseView;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 370); n++;
  XtSetArg(args[n], "width", 333); n++;
  XtSetArg(args[n], "x", 100); n++;
  XtSetArg(args[n], "y", 80); n++;


  /* Creating Widget */
  widBrowseMainWindow = XtCreateWidget("widBrowseMainWindow", xmMainWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(widBrowseMainWindow);
  
  addQuickHelp(widBrowseMainWindow);
  addHelpId(widBrowseMainWindow,38);

  
  /* ---------- Creating Widget:    widBrowseMenuBar -------------- */
  parent = widBrowseMainWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 20); n++;
  XtSetArg(args[n], "y", 10); n++;


  /* Creating Widget */
  widBrowseMenuBar = XmCreateMenuBar( parent, "widBrowseMenuBar", args, n);
  
  /* Manage the Widget */
  XtManageChild(widBrowseMenuBar);
  
  addQuickHelp(widBrowseMenuBar);
  addHelpId(widBrowseMenuBar,-1);

  
  /* ---------- Creating Widget:    fileButton -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileButton = XtCreateWidget("fileButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(fileButton);
  
  addQuickHelp(fileButton);
  addHelpId(fileButton,-1);

  
  /* ---------- Creating Widget:    fileMenu -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileMenu = XmCreatePulldownMenu( parent, "fileMenu", args, n);
  
  addQuickHelp(fileMenu);
  addHelpId(fileMenu,-1);

  
  /* ---------- Creating Widget:    loadButton -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  loadButton = XtCreateWidget("loadButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(loadButton);
  
  addQuickHelp(loadButton);
  addHelpId(loadButton,-1);

  
  /* ---------- Creating Widget:    loadParentButton -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "mnemonic", RES_CONVERT("KeySym", "P")); n++;


  /* Creating Widget */
  loadParentButton = XtCreateWidget("loadParentButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(loadParentButton);
  
  addQuickHelp(loadParentButton);
  addHelpId(loadParentButton,-1);

  
  /* ---------- Creating Widget:    closeButton -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "accelerator", "Ctrl<Key>c"); n++;
  XtSetArg(args[n], "acceleratorText", RES_CONVERT("XmString", "^C")); n++;


  /* Creating Widget */
  closeButton = XtCreateWidget("closeButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(closeButton);
  
  addQuickHelp(closeButton);
  addHelpId(closeButton,-1);

  
  /* ---------- Creating Widget:    viewButton -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "mnemonic", RES_CONVERT("KeySym", "V")); n++;


  /* Creating Widget */
  viewButton = XtCreateWidget("viewButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(viewButton);
  
  addQuickHelp(viewButton);
  addHelpId(viewButton,-1);

  
  /* ---------- Creating Widget:    viewMenu -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  viewMenu = XmCreatePulldownMenu( parent, "viewMenu", args, n);
  
  addQuickHelp(viewMenu);
  addHelpId(viewMenu,-1);

  
  /* ---------- Creating Widget:    smallIconButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  smallIconButton = XtCreateWidget("smallIconButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(smallIconButton);
  
  addQuickHelp(smallIconButton);
  addHelpId(smallIconButton,-1);

  
  /* ---------- Creating Widget:    withIconButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  withIconButton = XtCreateWidget("withIconButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(withIconButton);
  
  addQuickHelp(withIconButton);
  addHelpId(withIconButton,-1);

  
  /* ---------- Creating Widget:    withClassNameButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  withClassNameButton = XtCreateWidget("withClassNameButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(withClassNameButton);
  
  addQuickHelp(withClassNameButton);
  addHelpId(withClassNameButton,-1);

  
  /* ---------- Creating Widget:    widgetButton -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  widgetButton = XtCreateWidget("widgetButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(widgetButton);
  
  addQuickHelp(widgetButton);
  addHelpId(widgetButton,-1);

  
  /* ---------- Creating Widget:    widgetMenu -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  widgetMenu = XmCreatePulldownMenu( parent, "widgetMenu", args, n);
  
  addQuickHelp(widgetMenu);
  addHelpId(widgetMenu,-1);

  
  /* ---------- Creating Widget:    editButton -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  editButton = XtCreateWidget("editButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(editButton);
  
  addQuickHelp(editButton);
  addHelpId(editButton,-1);

  
  /* ---------- Creating Widget:    browseButton -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  browseButton = XtCreateWidget("browseButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(browseButton);
  
  addQuickHelp(browseButton);
  addHelpId(browseButton,-1);

  
  /* ---------- Creating Widget:    menuEditButton -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  menuEditButton = XtCreateWidget("menuEditButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(menuEditButton);
  
  addQuickHelp(menuEditButton);
  addHelpId(menuEditButton,-1);

  
  /* ---------- Creating Widget:    cutButton -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  cutButton = XtCreateWidget("cutButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(cutButton);
  
  addQuickHelp(cutButton);
  addHelpId(cutButton,-1);

  
  /* ---------- Creating Widget:    copyButton -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  copyButton = XtCreateWidget("copyButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(copyButton);
  
  addQuickHelp(copyButton);
  addHelpId(copyButton,-1);

  
  /* ---------- Creating Widget:    pasteButton -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  pasteButton = XtCreateWidget("pasteButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(pasteButton);
  
  addQuickHelp(pasteButton);
  addHelpId(pasteButton,-1);

  
  /* ---------- Creating Widget:    separator -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  separator = XtCreateWidget("separator", xmSeparatorWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(separator);
  
  addQuickHelp(separator);
  addHelpId(separator,-1);

  
  /* ---------- Creating Widget:    deleteButton -------------- */
  parent = widgetMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  deleteButton = XtCreateWidget("deleteButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(deleteButton);
  
  addQuickHelp(deleteButton);
  addHelpId(deleteButton,-1);

  
  /* ---------- Creating Widget:    createButton -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;


  /* Creating Widget */
  createButton = XtCreateWidget("createButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(createButton);
  
  addQuickHelp(createButton);
  addHelpId(createButton,-1);

  
  /* ---------- Creating Widget:    helpButton -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  helpButton = XtCreateWidget("helpButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(helpButton);
  
  addQuickHelp(helpButton);
  addHelpId(helpButton,-1);

  
  /* ---------- Creating Widget:    helpMenu -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  helpMenu = XmCreatePulldownMenu( parent, "helpMenu", args, n);
  
  addQuickHelp(helpMenu);
  addHelpId(helpMenu,-1);

  
  /* ---------- Creating Widget:    onHelp -------------- */
  parent = helpMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  onHelp = XtCreateWidget("onHelp", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(onHelp);
  
  addQuickHelp(onHelp);
  addHelpId(onHelp,-1);

  
  /* ---------- Creating Widget:    onContext -------------- */
  parent = helpMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "On Context")); n++;


  /* Creating Widget */
  onContext = XtCreateWidget("onContext", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(onContext);
  
  addQuickHelp(onContext);
  addHelpId(onContext,-1);

  
  /* ---------- Creating Widget:    onWidResEditor -------------- */
  parent = helpMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "On Window")); n++;
  XtSetArg(args[n], "mnemonic", RES_CONVERT("KeySym", "W")); n++;


  /* Creating Widget */
  onWidResEditor = XtCreateWidget("onWidResEditor", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(onWidResEditor);
  
  addQuickHelp(onWidResEditor);
  addHelpId(onWidResEditor,-1);

  
  /* ---------- Creating Widget:    optionsButton -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  optionsButton = XtCreateWidget("optionsButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(optionsButton);
  
  addQuickHelp(optionsButton);
  addHelpId(optionsButton,-1);

  
  /* ---------- Creating Widget:    optionsMenu -------------- */
  parent = widBrowseMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  optionsMenu = XmCreatePulldownMenu( parent, "optionsMenu", args, n);
  
  addQuickHelp(optionsMenu);
  addHelpId(optionsMenu,-1);

  
  /* ---------- Creating Widget:    automaticLoadButton -------------- */
  parent = optionsMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  automaticLoadButton = XtCreateWidget("automaticLoadButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(automaticLoadButton);
  
  addQuickHelp(automaticLoadButton);
  addHelpId(automaticLoadButton,-1);

  
  /* ---------- Creating Widget:    widBrowseForm -------------- */
  parent = widBrowseMainWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 340); n++;
  XtSetArg(args[n], "width", 333); n++;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 20); n++;


  /* Creating Widget */
  widBrowseForm = XtCreateWidget("widBrowseForm", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(widBrowseForm);
  
  addQuickHelp(widBrowseForm);
  addHelpId(widBrowseForm,-1);

  
  /* ---------- Creating Widget:    quickHelp -------------- */
  parent = widBrowseForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 20); n++;
  XtSetArg(args[n], "y", 310); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "bottomAttachment", 1); n++;
  XtSetArg(args[n], "bottomOffset", 1); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;


  /* Creating Widget */
  quickHelp = XtCreateWidget("quickHelp", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(quickHelp);
  
  addQuickHelp(quickHelp);
  addHelpId(quickHelp,-1);

  
  /* ---------- Creating Widget:    treeFrame -------------- */
  parent = widBrowseForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 313); n++;
  XtSetArg(args[n], "width", 325); n++;
  XtSetArg(args[n], "x", 30); n++;
  XtSetArg(args[n], "y", 20); n++;
  XtSetArg(args[n], "shadowThickness", 0); n++;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "bottomOffset", 4); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 4); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 4); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 4); n++;


  /* Creating Widget */
  treeFrame = XtCreateWidget("treeFrame", xmFrameWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(treeFrame);
  
  addQuickHelp(treeFrame);
  addHelpId(treeFrame,-1);


}



// ----------------------------
// addCallbacks()
// ----------------------------

void WidBrowseView_base::addCallbacks()
{

  XtAddCallback( loadButton, "activateCallback",
                 do_load_CB, this);

  XtAddCallback( loadParentButton, "activateCallback",
                 do_loadParent_CB, this);

  XtAddCallback( closeButton, "activateCallback",
                 do_close_CB, this);

  XtAddCallback( smallIconButton, "valueChangedCallback",
                 do_smallIcon_CB, this);

  XtAddCallback( withIconButton, "valueChangedCallback",
                 do_withIcon_CB, this);

  XtAddCallback( withClassNameButton, "valueChangedCallback",
                 do_withClassName_CB, this);

  XtAddCallback( widgetMenu, "mapCallback",
                 do_widgetMenuMap_CB, this);

  XtAddCallback( onHelp, "activateCallback",
                 do_onHelp_CB, this);

  XtAddCallback( onContext, "activateCallback",
                 do_onContext_CB, this);

  XtAddCallback( onWidResEditor, "activateCallback",
                 do_help_CB, this);

  XtAddCallback( automaticLoadButton, "valueChangedCallback",
                 do_automaticLoad_CB, this);

}



// ----------------------------
// addRelations()
// ----------------------------

void WidBrowseView_base::addRelations()
{
  XtVaSetValues(widBrowseMenuBar, "menuHelpWidget", helpButton, NULL);

  XtVaSetValues(fileButton, "subMenuId", fileMenu, NULL);

  XtVaSetValues(viewButton, "subMenuId", viewMenu, NULL);

  XtVaSetValues(widgetButton, "subMenuId", widgetMenu, NULL);

  XtVaSetValues(helpButton, "subMenuId", helpMenu, NULL);

  XtVaSetValues(optionsButton, "subMenuId", optionsMenu, NULL);

  XtVaSetValues(treeFrame, "bottomWidget", quickHelp, NULL);


}


// ----------------------------
// manageWidget()
// ----------------------------
void WidBrowseView_base::manageWidget(Widget, XtPointer c, XtPointer)
{
  XtManageChild((Widget)c);
}


// ----------------------------
// createPixmapFromData()
// ----------------------------

Pixmap WidBrowseView_base::createPixmapFromData(char **data)
{
  Pixmap pix, mask;
  XpmAttributes attr;

  memset(&attr, 0, sizeof(attr));
  attr.valuemask = XpmReturnPixels;

  if( !XpmCreatePixmapFromData(XtDisplay(LicView::getTopLevel()),
		               XRootWindowOfScreen(XtScreen(LicView::getTopLevel())),
			       data,
			       &pix, &mask, &attr) )
    return pix;
  return XmUNSPECIFIED_PIXMAP;
}

// ------------------------------------------
// createPixmapFromFile()
//
// Creating a pixmap by XpmRaedFileToPixmap()
// Uses XFILESEARCHPATH to find the pixmap
// default path: /usr/lib/X11/pixmaps/%N.xpm
// ------------------------------------------

Pixmap WidBrowseView_base::createPixmapFromFile(char *name)
{
  String string;
  Pixmap pix, mask;
  XpmAttributes attr;

  string = XtResolvePathname(XtDisplay(LicView::getTopLevel()),
			     "pixmaps", name, "", NULL,
			     NULL, 0, NULL);
  if(string) {
    memset(&attr, 0, sizeof(attr));
    attr.valuemask = XpmReturnPixels;
    if( !XpmReadFileToPixmap(XtDisplay(LicView::getTopLevel()),
			     XRootWindowOfScreen(
			     XtScreen(LicView::getTopLevel())),
			     string,
			     &pix, &mask, &attr) )
      return pix;
    return XmUNSPECIFIED_PIXMAP;
    XtFree(string);
  }
  return XmUNSPECIFIED_PIXMAP;
}

// ---------------------------------------------------------
// Following class method are used as a callback.
// The method is calling a abstract virtual method, which
// must be overloaded in the derived class 'WidBrowseView'
// ---------------------------------------------------------

void WidBrowseView_base::do_load_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidBrowseView_base*)clientData)->do_load(wg,callData);
}

void WidBrowseView_base::do_loadParent_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidBrowseView_base*)clientData)->do_loadParent(wg,callData);
}

void WidBrowseView_base::do_close_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidBrowseView_base*)clientData)->do_close(wg,callData);
}

void WidBrowseView_base::do_smallIcon_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidBrowseView_base*)clientData)->do_smallIcon(wg,callData);
}

void WidBrowseView_base::do_withIcon_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidBrowseView_base*)clientData)->do_withIcon(wg,callData);
}

void WidBrowseView_base::do_withClassName_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidBrowseView_base*)clientData)->do_withClassName(wg,callData);
}

void WidBrowseView_base::do_widgetMenuMap_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidBrowseView_base*)clientData)->do_widgetMenuMap(wg,callData);
}

void WidBrowseView_base::do_onHelp_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidBrowseView_base*)clientData)->do_onHelp(wg,callData);
}

void WidBrowseView_base::do_onContext_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidBrowseView_base*)clientData)->do_onContext(wg,callData);
}

void WidBrowseView_base::do_help_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidBrowseView_base*)clientData)->do_help(wg,callData);
}

void WidBrowseView_base::do_automaticLoad_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidBrowseView_base*)clientData)->do_automaticLoad(wg,callData);
}


