/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// -----------------------------------------------------
// WidBrowseView_base.h
// 
// This file was automaticly generated by
// View Designer/X  v1.2
//
// User: lazy@apfel
// Date: Tue Jun  2 17:02:48 1998
//
// Don't edit this file, please !
// -----------------------------------------------------

#ifndef _WidBrowseView_base_H_
#define _WidBrowseView_base_H_

#include <X11/Intrinsic.h>
#include <lac/LicView.h>



// -----------------------------------------------------
// Class definition 
// class WidBrowseView_base is a derived class of LicView
// -----------------------------------------------------

class WidBrowseView_base : public LicView {
private:
  void createWidgets();
  void addRelations();
  void addCallbacks();

protected:
  Widget WidBrowseView;
  Widget widBrowseMainWindow;       /* XmMainWindow */
  Widget widBrowseMenuBar;       /* XmCreateMenuBar */
  Widget fileButton;       /* XmCascadeButton */
  Widget fileMenu;       /* XmCreatePulldownMenu */
  Widget loadButton;       /* XmPushButton */
  Widget loadParentButton;       /* XmPushButton */
  Widget closeButton;       /* XmPushButton */
  Widget viewButton;       /* XmCascadeButton */
  Widget viewMenu;       /* XmCreatePulldownMenu */
  Widget smallIconButton;       /* XmToggleButton */
  Widget withIconButton;       /* XmToggleButton */
  Widget withClassNameButton;       /* XmToggleButton */
  Widget widgetButton;       /* XmCascadeButton */
  Widget widgetMenu;       /* XmCreatePulldownMenu */
  Widget editButton;       /* XmPushButton */
  Widget browseButton;       /* XmPushButton */
  Widget menuEditButton;       /* XmPushButton */
  Widget cutButton;       /* XmPushButton */
  Widget copyButton;       /* XmPushButton */
  Widget pasteButton;       /* XmPushButton */
  Widget separator;       /* XmSeparator */
  Widget deleteButton;       /* XmPushButton */
  Widget createButton;       /* XmCascadeButton */
  Widget helpButton;       /* XmCascadeButton */
  Widget helpMenu;       /* XmCreatePulldownMenu */
  Widget onHelp;       /* XmPushButton */
  Widget onContext;       /* XmPushButton */
  Widget onWidResEditor;       /* XmPushButton */
  Widget optionsButton;       /* XmCascadeButton */
  Widget optionsMenu;       /* XmCreatePulldownMenu */
  Widget automaticLoadButton;       /* XmToggleButton */
  Widget widBrowseForm;       /* XmForm */
  Widget quickHelp;       /* XmLabel */
  Widget treeFrame;       /* XmFrame */


  static void do_load_CB(Widget,XtPointer,XtPointer);
  static void do_loadParent_CB(Widget,XtPointer,XtPointer);
  static void do_close_CB(Widget,XtPointer,XtPointer);
  static void do_smallIcon_CB(Widget,XtPointer,XtPointer);
  static void do_withIcon_CB(Widget,XtPointer,XtPointer);
  static void do_withClassName_CB(Widget,XtPointer,XtPointer);
  static void do_widgetMenuMap_CB(Widget,XtPointer,XtPointer);
  static void do_onHelp_CB(Widget,XtPointer,XtPointer);
  static void do_onContext_CB(Widget,XtPointer,XtPointer);
  static void do_help_CB(Widget,XtPointer,XtPointer);
  static void do_automaticLoad_CB(Widget,XtPointer,XtPointer);



  // override the following methods in class WidBrowseView

  virtual void do_load(Widget,XtPointer) = 0;
  virtual void do_loadParent(Widget,XtPointer) = 0;
  virtual void do_close(Widget,XtPointer) = 0;
  virtual void do_smallIcon(Widget,XtPointer) = 0;
  virtual void do_withIcon(Widget,XtPointer) = 0;
  virtual void do_withClassName(Widget,XtPointer) = 0;
  virtual void do_widgetMenuMap(Widget,XtPointer) = 0;
  virtual void do_onHelp(Widget,XtPointer) = 0;
  virtual void do_onContext(Widget,XtPointer) = 0;
  virtual void do_help(Widget,XtPointer) = 0;
  virtual void do_automaticLoad(Widget,XtPointer) = 0;


public:
  WidBrowseView_base(Widget parent = NULL, ArgList args = NULL, Cardinal n = 0, char
*fbRes = NULL);

  Widget getTop() { return WidBrowseView; }
  Pixmap createPixmapFromData(char **data);
  Pixmap createPixmapFromFile(char *filename);
  static void manageWidget(Widget wg, XtPointer c, XtPointer call);
};

#endif /* Don't add stuff after this #endif */






