/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// ---------------------------------------
// WidgetPalette_base.C
//
// This file was automaticly generated by
// View Designer/X v1.2
//
// User: lazy@apfel
// Date: Tue Jun  2 17:02:47 1998
//
// Don't edit this file, please !
// ---------------------------------------


// Include class definition

#include "WidgetPalette_base.h"

// Include X11 header
#include <X11/xpm.h>

// Include OSF/Motif header files
#include <Xm/Frame.h>
#include <X11/Shell.h>
#include <Xm/Form.h>
#include <Xm/Label.h>
#include <Xm/RowColumn.h>
#include <Xm/CascadeB.h>
#include <Xm/PushB.h>
#include <Xm/ToggleB.h>
#include <Xm/Separator.h>
#include <Xm/ScrollBar.h>
#include <Xm/Frame.h>
#include <Xm/PanedW.h>








#define RES_CONVERT(t,s) cvtResourceFromString(parent, t, s)


// -----------------------------------
// WidgetPalette_base(parent,args,n)
// -----------------------------------

WidgetPalette_base::WidgetPalette_base(Widget p, ArgList f_args, Cardinal f_n, char *fbRes)
{
  Widget parent;
  Arg args[100];
  Cardinal n = 0;

  if(p) 
    parent = p;
  else
    parent = getTopLevel();

  if(fbRes) {
    XrmDatabase database, fallback;
    
    fallback = XrmGetStringDatabase(fbRes);
    database = XrmGetDatabase(XtDisplay(parent));
    
    XrmCombineDatabase(fallback, &database, FALSE);
  }

  if(!XtIsShell(parent)) {
    WidgetPalette = XtCreateWidget("WidgetPalette",xmFrameWidgetClass,
				       parent,f_args,f_n);
  } else { 
     XtSetArg(args[n], "iconPixmap", createPixmapFromFile("WidgetPalette.xpm")); n++;
  XtSetArg(args[n], "title", "Widget Class Palette"); n++;

    popupShell = WidgetPalette = XtCreatePopupShell("WidgetPalette", topLevelShellWidgetClass,
			parent, args, n);
  }
  createWidgets();
  addCallbacks();
  addRelations();
}


// ----------------------------
// createWidgets()
// ----------------------------

void WidgetPalette_base::createWidgets()
{
  Widget parent;           // the parent for every widget
  Arg args[100];           // resource list
  Cardinal n;              // number of resources

  // Now we create every Widget

  
  /* ---------- Creating Widget:    WidgetCreateForm -------------- */
  parent = WidgetPalette;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 595); n++;
  XtSetArg(args[n], "width", 349); n++;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", -30); n++;
  XtSetArg(args[n], "defaultPosition", 0); n++;


  /* Creating Widget */
  WidgetCreateForm = XtCreateWidget("WidgetCreateForm", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(WidgetCreateForm);
  
  addQuickHelp(WidgetCreateForm);
  addHelpId(WidgetCreateForm,14);

  
  /* ---------- Creating Widget:    quickHelp -------------- */
  parent = WidgetCreateForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", -30); n++;
  XtSetArg(args[n], "y", 100); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "bottomAttachment", 1); n++;
  XtSetArg(args[n], "bottomOffset", 1); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 5); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 5); n++;


  /* Creating Widget */
  quickHelp = XtCreateWidget("quickHelp", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(quickHelp);
  
  addQuickHelp(quickHelp);
  addHelpId(quickHelp,-1);

  
  /* ---------- Creating Widget:    menuBar_1 -------------- */
  parent = WidgetCreateForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 35); n++;
  XtSetArg(args[n], "width", 347); n++;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 1); n++;


  /* Creating Widget */
  menuBar_1 = XmCreateMenuBar( parent, "menuBar_1", args, n);
  
  /* Manage the Widget */
  XtManageChild(menuBar_1);
  
  addQuickHelp(menuBar_1);
  addHelpId(menuBar_1,-1);

  
  /* ---------- Creating Widget:    fileButton -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileButton = XtCreateWidget("fileButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(fileButton);
  
  addQuickHelp(fileButton);
  addHelpId(fileButton,-1);

  
  /* ---------- Creating Widget:    fileMenu -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileMenu = XmCreatePulldownMenu( parent, "fileMenu", args, n);
  
  addQuickHelp(fileMenu);
  addHelpId(fileMenu,-1);

  
  /* ---------- Creating Widget:    fileClose -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileClose = XtCreateWidget("fileClose", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(fileClose);
  
  addQuickHelp(fileClose);
  addHelpId(fileClose,-1);

  
  /* ---------- Creating Widget:    viewButton -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  viewButton = XtCreateWidget("viewButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(viewButton);
  
  addQuickHelp(viewButton);
  addHelpId(viewButton,-1);

  
  /* ---------- Creating Widget:    viewMenu -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  viewMenu = XmCreatePulldownMenu( parent, "viewMenu", args, n);
  
  addQuickHelp(viewMenu);
  addHelpId(viewMenu,-1);

  
  /* ---------- Creating Widget:    withNamesButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  withNamesButton = XtCreateWidget("withNamesButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(withNamesButton);
  
  addQuickHelp(withNamesButton);
  addHelpId(withNamesButton,-1);

  
  /* ---------- Creating Widget:    withIconsButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  withIconsButton = XtCreateWidget("withIconsButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(withIconsButton);
  
  addQuickHelp(withIconsButton);
  addHelpId(withIconsButton,-1);

  
  /* ---------- Creating Widget:    separator -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  separator = XtCreateWidget("separator", xmSeparatorWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(separator);
  
  addQuickHelp(separator);
  addHelpId(separator,-1);

  
  /* ---------- Creating Widget:    shellsButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  shellsButton = XtCreateWidget("shellsButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(shellsButton);
  
  addQuickHelp(shellsButton);
  addHelpId(shellsButton,-1);

  
  /* ---------- Creating Widget:    managersButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  managersButton = XtCreateWidget("managersButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(managersButton);
  
  addQuickHelp(managersButton);
  addHelpId(managersButton,-1);

  
  /* ---------- Creating Widget:    primitivesButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  primitivesButton = XtCreateWidget("primitivesButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(primitivesButton);
  
  addQuickHelp(primitivesButton);
  addHelpId(primitivesButton,-1);

  
  /* ---------- Creating Widget:    dialogsButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  dialogsButton = XtCreateWidget("dialogsButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(dialogsButton);
  
  addQuickHelp(dialogsButton);
  addHelpId(dialogsButton,-1);

  
  /* ---------- Creating Widget:    optionsButton -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  optionsButton = XtCreateWidget("optionsButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(optionsButton);
  
  addQuickHelp(optionsButton);
  addHelpId(optionsButton,-1);

  
  /* ---------- Creating Widget:    optionsMenu -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  optionsMenu = XmCreatePulldownMenu( parent, "optionsMenu", args, n);
  
  addQuickHelp(optionsMenu);
  addHelpId(optionsMenu,-1);

  
  /* ---------- Creating Widget:    createOnClickButton -------------- */
  parent = optionsMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  createOnClickButton = XtCreateWidget("createOnClickButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(createOnClickButton);
  
  addQuickHelp(createOnClickButton);
  addHelpId(createOnClickButton,-1);

  
  /* ---------- Creating Widget:    asChildOfSelectedButton -------------- */
  parent = optionsMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  asChildOfSelectedButton = XtCreateWidget("asChildOfSelectedButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(asChildOfSelectedButton);
  
  addQuickHelp(asChildOfSelectedButton);
  addHelpId(asChildOfSelectedButton,-1);

  
  /* ---------- Creating Widget:    helpButton -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "mnemonic", RES_CONVERT("KeySym", "H")); n++;


  /* Creating Widget */
  helpButton = XtCreateWidget("helpButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(helpButton);
  
  addQuickHelp(helpButton);
  addHelpId(helpButton,-1);

  
  /* ---------- Creating Widget:    helpMenu -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  helpMenu = XmCreatePulldownMenu( parent, "helpMenu", args, n);
  
  addQuickHelp(helpMenu);
  addHelpId(helpMenu,-1);

  
  /* ---------- Creating Widget:    onHelp -------------- */
  parent = helpMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  onHelp = XtCreateWidget("onHelp", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(onHelp);
  
  addQuickHelp(onHelp);
  addHelpId(onHelp,-1);

  
  /* ---------- Creating Widget:    onContext -------------- */
  parent = helpMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  onContext = XtCreateWidget("onContext", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(onContext);
  
  addQuickHelp(onContext);
  addHelpId(onContext,-1);

  
  /* ---------- Creating Widget:    helpHelp -------------- */
  parent = helpMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  helpHelp = XtCreateWidget("helpHelp", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(helpHelp);
  
  addQuickHelp(helpHelp);
  addHelpId(helpHelp,-1);

  
  /* ---------- Creating Widget:    scrollBar -------------- */
  parent = WidgetCreateForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "bottomOffset", 0); n++;
  XtSetArg(args[n], "leftAttachment", 0); n++;
  XtSetArg(args[n], "resizable", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 3); n++;
  XtSetArg(args[n], "topAttachment", 3); n++;
  XtSetArg(args[n], "topOffset", 3); n++;


  /* Creating Widget */
  scrollBar = XtCreateWidget("scrollBar", xmScrollBarWidgetClass,
			parent, args, n);
  
  addQuickHelp(scrollBar);
  addHelpId(scrollBar,-1);

  
  /* ---------- Creating Widget:    frame -------------- */
  parent = WidgetCreateForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "shadowThickness", 2); n++;
  XtSetArg(args[n], "shadowType", 7); n++;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "bottomOffset", 0); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 3); n++;
  XtSetArg(args[n], "resizable", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 3); n++;
  XtSetArg(args[n], "topAttachment", 3); n++;
  XtSetArg(args[n], "topOffset", 3); n++;


  /* Creating Widget */
  frame = XtCreateWidget("frame", xmFrameWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(frame);
  
  addQuickHelp(frame);
  addHelpId(frame,-1);

  
  /* ---------- Creating Widget:    form -------------- */
  parent = frame;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  form = XtCreateWidget("form", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(form);
  
  addQuickHelp(form);
  addHelpId(form,-1);

  
  /* ---------- Creating Widget:    WidgetPanedWindow -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "marginHeight", 0); n++;
  XtSetArg(args[n], "marginWidth", 0); n++;
  XtSetArg(args[n], "spacing", 2); n++;
  XtSetArg(args[n], "bottomAttachment", 1); n++;
  XtSetArg(args[n], "bottomOffset", 0); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 0); n++;
  XtSetArg(args[n], "resizable", 0); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 0); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 0); n++;


  /* Creating Widget */
  WidgetPanedWindow = XtCreateWidget("WidgetPanedWindow", xmPanedWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(WidgetPanedWindow);
  
  addQuickHelp(WidgetPanedWindow);
  addHelpId(WidgetPanedWindow,-1);

  
  /* ---------- Creating Widget:    ShellForm -------------- */
  parent = WidgetPanedWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 96); n++;
  XtSetArg(args[n], "width", 325); n++;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "paneMinimum", 50); n++;


  /* Creating Widget */
  ShellForm = XtCreateWidget("ShellForm", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(ShellForm);
  
  addQuickHelp(ShellForm);
  addHelpId(ShellForm,-1);

  
  /* ---------- Creating Widget:    ShellLabel -------------- */
  parent = ShellForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 20); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "Shells:")); n++;
  XtSetArg(args[n], "bottomAttachment", 0); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 0); n++;
  XtSetArg(args[n], "resizable", 1); n++;
  XtSetArg(args[n], "rightAttachment", 0); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 0); n++;


  /* Creating Widget */
  ShellLabel = XtCreateWidget("ShellLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(ShellLabel);
  
  addQuickHelp(ShellLabel);
  addHelpId(ShellLabel,-1);

  
  /* ---------- Creating Widget:    ManagerForm -------------- */
  parent = WidgetPanedWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 85); n++;
  XtSetArg(args[n], "width", 325); n++;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 102); n++;
  XtSetArg(args[n], "paneMinimum", 50); n++;


  /* Creating Widget */
  ManagerForm = XtCreateWidget("ManagerForm", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(ManagerForm);
  
  addQuickHelp(ManagerForm);
  addHelpId(ManagerForm,-1);

  
  /* ---------- Creating Widget:    ManagerLabel -------------- */
  parent = ManagerForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 20); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "Managers:")); n++;
  XtSetArg(args[n], "bottomAttachment", 0); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 0); n++;
  XtSetArg(args[n], "resizable", 1); n++;
  XtSetArg(args[n], "rightAttachment", 0); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 0); n++;


  /* Creating Widget */
  ManagerLabel = XtCreateWidget("ManagerLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(ManagerLabel);
  
  addQuickHelp(ManagerLabel);
  addHelpId(ManagerLabel,-1);

  
  /* ---------- Creating Widget:    PrimitiveForm -------------- */
  parent = WidgetPanedWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "paneMinimum", 50); n++;


  /* Creating Widget */
  PrimitiveForm = XtCreateWidget("PrimitiveForm", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(PrimitiveForm);
  
  addQuickHelp(PrimitiveForm);
  addHelpId(PrimitiveForm,-1);

  
  /* ---------- Creating Widget:    PrimitiveLabel -------------- */
  parent = PrimitiveForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 20); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "Primitives:")); n++;
  XtSetArg(args[n], "bottomAttachment", 0); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 0); n++;
  XtSetArg(args[n], "resizable", 1); n++;
  XtSetArg(args[n], "rightAttachment", 0); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 0); n++;


  /* Creating Widget */
  PrimitiveLabel = XtCreateWidget("PrimitiveLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(PrimitiveLabel);
  
  addQuickHelp(PrimitiveLabel);
  addHelpId(PrimitiveLabel,-1);

  
  /* ---------- Creating Widget:    DialogForm -------------- */
  parent = WidgetPanedWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "paneMinimum", 50); n++;


  /* Creating Widget */
  DialogForm = XtCreateWidget("DialogForm", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(DialogForm);
  
  addQuickHelp(DialogForm);
  addHelpId(DialogForm,-1);

  
  /* ---------- Creating Widget:    DialogLabel -------------- */
  parent = DialogForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 20); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "Dialogs:")); n++;
  XtSetArg(args[n], "bottomAttachment", 0); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 0); n++;
  XtSetArg(args[n], "resizable", 1); n++;
  XtSetArg(args[n], "rightAttachment", 0); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 0); n++;


  /* Creating Widget */
  DialogLabel = XtCreateWidget("DialogLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(DialogLabel);
  
  addQuickHelp(DialogLabel);
  addHelpId(DialogLabel,-1);


}



// ----------------------------
// addCallbacks()
// ----------------------------

void WidgetPalette_base::addCallbacks()
{

  XtAddCallback( fileClose, "activateCallback",
                 do_close_CB, this);

  XtAddCallback( viewMenu, "entryCallback",
                 do_viewEntry_CB, this);

  XtAddCallback( optionsMenu, "entryCallback",
                 do_optionsEntry_CB, this);

  XtAddCallback( onHelp, "activateCallback",
                 do_onHelp_CB, this);

  XtAddCallback( onContext, "activateCallback",
                 do_onContext_CB, this);

  XtAddCallback( helpHelp, "activateCallback",
                 do_help_CB, this);

}



// ----------------------------
// addRelations()
// ----------------------------

void WidgetPalette_base::addRelations()
{
  XtVaSetValues(menuBar_1, "menuHelpWidget", helpButton, NULL);

  XtVaSetValues(fileButton, "subMenuId", fileMenu, NULL);

  XtVaSetValues(viewButton, "subMenuId", viewMenu, NULL);

  XtVaSetValues(optionsButton, "subMenuId", optionsMenu, NULL);

  XtVaSetValues(helpButton, "subMenuId", helpMenu, NULL);

  XtVaSetValues(scrollBar, "bottomWidget", quickHelp, NULL);

  XtVaSetValues(scrollBar, "topWidget", menuBar_1, NULL);

  XtVaSetValues(frame, "bottomWidget", quickHelp, NULL);

  XtVaSetValues(frame, "topWidget", menuBar_1, NULL);


}


// ----------------------------
// manageWidget()
// ----------------------------
void WidgetPalette_base::manageWidget(Widget, XtPointer c, XtPointer)
{
  XtManageChild((Widget)c);
}


// ----------------------------
// createPixmapFromData()
// ----------------------------

Pixmap WidgetPalette_base::createPixmapFromData(char **data)
{
  Pixmap pix, mask;
  XpmAttributes attr;

  memset(&attr, 0, sizeof(attr));
  attr.valuemask = XpmReturnPixels;

  if( !XpmCreatePixmapFromData(XtDisplay(LicView::getTopLevel()),
		               XRootWindowOfScreen(XtScreen(LicView::getTopLevel())),
			       data,
			       &pix, &mask, &attr) )
    return pix;
  return XmUNSPECIFIED_PIXMAP;
}

// ------------------------------------------
// createPixmapFromFile()
//
// Creating a pixmap by XpmRaedFileToPixmap()
// Uses XFILESEARCHPATH to find the pixmap
// default path: /usr/lib/X11/pixmaps/%N.xpm
// ------------------------------------------

Pixmap WidgetPalette_base::createPixmapFromFile(char *name)
{
  String string;
  Pixmap pix, mask;
  XpmAttributes attr;

  string = XtResolvePathname(XtDisplay(LicView::getTopLevel()),
			     "pixmaps", name, "", NULL,
			     NULL, 0, NULL);
  if(string) {
    memset(&attr, 0, sizeof(attr));
    attr.valuemask = XpmReturnPixels;
    if( !XpmReadFileToPixmap(XtDisplay(LicView::getTopLevel()),
			     XRootWindowOfScreen(
			     XtScreen(LicView::getTopLevel())),
			     string,
			     &pix, &mask, &attr) )
      return pix;
    return XmUNSPECIFIED_PIXMAP;
    XtFree(string);
  }
  return XmUNSPECIFIED_PIXMAP;
}

// ---------------------------------------------------------
// Following class method are used as a callback.
// The method is calling a abstract virtual method, which
// must be overloaded in the derived class 'WidgetPalette'
// ---------------------------------------------------------

void WidgetPalette_base::do_close_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidgetPalette_base*)clientData)->do_close(wg,callData);
}

void WidgetPalette_base::do_viewEntry_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidgetPalette_base*)clientData)->do_viewEntry(wg,callData);
}

void WidgetPalette_base::do_optionsEntry_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidgetPalette_base*)clientData)->do_optionsEntry(wg,callData);
}

void WidgetPalette_base::do_onHelp_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidgetPalette_base*)clientData)->do_onHelp(wg,callData);
}

void WidgetPalette_base::do_onContext_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidgetPalette_base*)clientData)->do_onContext(wg,callData);
}

void WidgetPalette_base::do_help_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidgetPalette_base*)clientData)->do_help(wg,callData);
}


