/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// -----------------------------------------------------
// WidgetPalette_base.h
// 
// This file was automaticly generated by
// View Designer/X  v1.2
//
// User: lazy@apfel
// Date: Tue Jun  2 17:02:47 1998
//
// Don't edit this file, please !
// -----------------------------------------------------

#ifndef _WidgetPalette_base_H_
#define _WidgetPalette_base_H_

#include <X11/Intrinsic.h>
#include <lac/LicView.h>



// -----------------------------------------------------
// Class definition 
// class WidgetPalette_base is a derived class of LicView
// -----------------------------------------------------

class WidgetPalette_base : public LicView {
private:
  void createWidgets();
  void addRelations();
  void addCallbacks();

protected:
  Widget WidgetPalette;
  Widget WidgetCreateForm;       /* XmForm */
  Widget quickHelp;       /* XmLabel */
  Widget menuBar_1;       /* XmCreateMenuBar */
  Widget fileButton;       /* XmCascadeButton */
  Widget fileMenu;       /* XmCreatePulldownMenu */
  Widget fileClose;       /* XmPushButton */
  Widget viewButton;       /* XmCascadeButton */
  Widget viewMenu;       /* XmCreatePulldownMenu */
  Widget withNamesButton;       /* XmToggleButton */
  Widget withIconsButton;       /* XmToggleButton */
  Widget separator;       /* XmSeparator */
  Widget shellsButton;       /* XmToggleButton */
  Widget managersButton;       /* XmToggleButton */
  Widget primitivesButton;       /* XmToggleButton */
  Widget dialogsButton;       /* XmToggleButton */
  Widget optionsButton;       /* XmCascadeButton */
  Widget optionsMenu;       /* XmCreatePulldownMenu */
  Widget createOnClickButton;       /* XmToggleButton */
  Widget asChildOfSelectedButton;       /* XmToggleButton */
  Widget helpButton;       /* XmCascadeButton */
  Widget helpMenu;       /* XmCreatePulldownMenu */
  Widget onHelp;       /* XmPushButton */
  Widget onContext;       /* XmPushButton */
  Widget helpHelp;       /* XmPushButton */
  Widget scrollBar;       /* XmScrollBar */
  Widget frame;       /* XmDrawingArea */
  Widget form;       /* XmForm */
  Widget WidgetPanedWindow;       /* XmPanedWindow */
  Widget ShellForm;       /* XmForm */
  Widget ShellLabel;       /* XmLabel */
  Widget ManagerForm;       /* XmForm */
  Widget ManagerLabel;       /* XmLabel */
  Widget PrimitiveForm;       /* XmForm */
  Widget PrimitiveLabel;       /* XmLabel */
  Widget DialogForm;       /* XmForm */
  Widget DialogLabel;       /* XmLabel */


  static void do_close_CB(Widget,XtPointer,XtPointer);
  static void do_viewEntry_CB(Widget,XtPointer,XtPointer);
  static void do_optionsEntry_CB(Widget,XtPointer,XtPointer);
  static void do_onHelp_CB(Widget,XtPointer,XtPointer);
  static void do_onContext_CB(Widget,XtPointer,XtPointer);
  static void do_help_CB(Widget,XtPointer,XtPointer);



  // override the following methods in class WidgetPalette

  virtual void do_close(Widget,XtPointer) = 0;
  virtual void do_viewEntry(Widget,XtPointer) = 0;
  virtual void do_optionsEntry(Widget,XtPointer) = 0;
  virtual void do_onHelp(Widget,XtPointer) = 0;
  virtual void do_onContext(Widget,XtPointer) = 0;
  virtual void do_help(Widget,XtPointer) = 0;


public:
  WidgetPalette_base(Widget parent = NULL, ArgList args = NULL, Cardinal n = 0, char
*fbRes = NULL);

  Widget getTop() { return WidgetPalette; }
  Pixmap createPixmapFromData(char **data);
  Pixmap createPixmapFromFile(char *filename);
  static void manageWidget(Widget wg, XtPointer c, XtPointer call);
};

#endif /* Don't add stuff after this #endif */






