/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// -----------------------------------------------------
// WidResEditor_base.h
// 
// This file was automaticly generated by
// View Designer/X  v1.2
//
// User: lazy@apfel
// Date: Tue Jun  2 17:02:48 1998
//
// Don't edit this file, please !
// -----------------------------------------------------

#ifndef _WidResEditor_base_H_
#define _WidResEditor_base_H_

#include <X11/Intrinsic.h>
#include <lac/LicView.h>



// -----------------------------------------------------
// Class definition 
// class WidResEditor_base is a derived class of LicView
// -----------------------------------------------------

class WidResEditor_base : public LicView {
private:
  void createWidgets();
  void addRelations();
  void addCallbacks();

protected:
  Widget WidResEditor;
  Widget widResMainWindow;       /* XmMainWindow */
  Widget widResMenuBar;       /* XmCreateMenuBar */
  Widget fileButton;       /* XmCascadeButton */
  Widget fileMenu;       /* XmCreatePulldownMenu */
  Widget loadButton;       /* XmPushButton */
  Widget applyButton;       /* XmPushButton */
  Widget applyToButton;       /* XmCascadeButton */
  Widget applyToMenu;       /* XmCreatePulldownMenu */
  Widget selectedButton;       /* XmPushButton */
  Widget meAndSiblingsButton;       /* XmPushButton */
  Widget meAndChildrenButton;       /* XmPushButton */
  Widget meAndAllButton;       /* XmPushButton */
  Widget unhandledResources;       /* XmPushButton */
  Widget separator;       /* XmSeparator */
  Widget closeButton;       /* XmPushButton */
  Widget viewButton;       /* XmCascadeButton */
  Widget viewMenu;       /* XmCreatePulldownMenu */
  Widget coreButton;       /* XmToggleButton */
  Widget specificButton;       /* XmToggleButton */
  Widget constraintButton;       /* XmToggleButton */
  Widget callbackButton;       /* XmToggleButton */
  Widget extraButton;       /* XmToggleButton */
  Widget userButton;       /* XmToggleButton */
  Widget optionsButton;       /* XmCascadeButton */
  Widget optionsMenu;       /* XmCreatePulldownMenu */
  Widget automaticLoad;       /* XmToggleButton */
  Widget withSource;       /* XmToggleButton */
  Widget helpButton;       /* XmCascadeButton */
  Widget helpMenu;       /* XmCreatePulldownMenu */
  Widget onHelp;       /* XmPushButton */
  Widget onContext;       /* XmPushButton */
  Widget onWidResEditor;       /* XmPushButton */
  Widget widResForm;       /* XmForm */
  Widget xlButtonBox_1;       /* XlButtonBox */
  Widget applyButton2;       /* XmPushButton */
  Widget closeButton2;       /* XmPushButton */
  Widget helpButton2;       /* XmPushButton */
  Widget scrolledWindow_1;       /* XmScrolledWindow */
  Widget categoryLabel;       /* XmLabel */
  Widget currentCategoryLabel;       /* XmLabel */
  Widget automaticLoadLabel;       /* XmLabel */
  Widget quickHelp;       /* XmLabel */
  Widget messageDialog;       /* XmCreateMessageDialog */
  Widget scrolledWindow;       /* XmScrolledWindow */
  Widget list;       /* XmList */


  static void do_load_CB(Widget,XtPointer,XtPointer);
  static void do_apply_CB(Widget,XtPointer,XtPointer);
  static void do_close_CB(Widget,XtPointer,XtPointer);
  static void do_viewChanged_CB(Widget,XtPointer,XtPointer);
  static void do_automaticLoad_CB(Widget,XtPointer,XtPointer);
  static void do_withSource_CB(Widget,XtPointer,XtPointer);
  static void do_onHelp_CB(Widget,XtPointer,XtPointer);
  static void do_onContext_CB(Widget,XtPointer,XtPointer);
  static void do_help_CB(Widget,XtPointer,XtPointer);



  // override the following methods in class WidResEditor

  virtual void do_load(Widget,XtPointer) = 0;
  virtual void do_apply(Widget,XtPointer) = 0;
  virtual void do_close(Widget,XtPointer) = 0;
  virtual void do_viewChanged(Widget,XtPointer) = 0;
  virtual void do_automaticLoad(Widget,XtPointer) = 0;
  virtual void do_withSource(Widget,XtPointer) = 0;
  virtual void do_onHelp(Widget,XtPointer) = 0;
  virtual void do_onContext(Widget,XtPointer) = 0;
  virtual void do_help(Widget,XtPointer) = 0;


public:
  WidResEditor_base(Widget parent = NULL, ArgList args = NULL, Cardinal n = 0, char
*fbRes = NULL);

  Widget getTop() { return WidResEditor; }
  Pixmap createPixmapFromData(char **data);
  Pixmap createPixmapFromFile(char *filename);
  static void manageWidget(Widget wg, XtPointer c, XtPointer call);
};

#endif /* Don't add stuff after this #endif */






