/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// ---------------------------------------
// WidResEditor_base.C
//
// This file was automaticly generated by
// View Designer/X v1.2
//
// User: lazy@apfel
// Date: Tue Jun  2 17:02:48 1998
//
// Don't edit this file, please !
// ---------------------------------------


// Include class definition

#include "WidResEditor_base.h"

// Include X11 header
#include <X11/xpm.h>

// Include OSF/Motif header files
#include <Xm/Frame.h>
#include <X11/Shell.h>
#include <Xm/MainW.h>
#include <Xm/RowColumn.h>
#include <Xm/CascadeB.h>
#include <Xm/PushB.h>
#include <Xm/Separator.h>
#include <Xm/ToggleB.h>
#include <Xm/Form.h>
#include <lwid/ButtonBox.h>
#include <Xm/ScrolledW.h>
#include <Xm/Label.h>
#include <Xm/MessageB.h>
#include <Xm/List.h>








#define RES_CONVERT(t,s) cvtResourceFromString(parent, t, s)


// -----------------------------------
// WidResEditor_base(parent,args,n)
// -----------------------------------

WidResEditor_base::WidResEditor_base(Widget p, ArgList f_args, Cardinal f_n, char *fbRes)
{
  Widget parent;
  Arg args[100];
  Cardinal n = 0;

  if(p) 
    parent = p;
  else
    parent = getTopLevel();

  if(fbRes) {
    XrmDatabase database, fallback;
    
    fallback = XrmGetStringDatabase(fbRes);
    database = XrmGetDatabase(XtDisplay(parent));
    
    XrmCombineDatabase(fallback, &database, FALSE);
  }

  if(!XtIsShell(parent)) {
    WidResEditor = XtCreateWidget("WidResEditor",xmFrameWidgetClass,
				       parent,f_args,f_n);
  } else { 
   
    popupShell = WidResEditor = XtCreatePopupShell("WidResEditor", topLevelShellWidgetClass,
			parent, args, n);
  }
  createWidgets();
  addCallbacks();
  addRelations();
}


// ----------------------------
// createWidgets()
// ----------------------------

void WidResEditor_base::createWidgets()
{
  Widget parent;           // the parent for every widget
  Arg args[100];           // resource list
  Cardinal n;              // number of resources

  // Now we create every Widget

  
  /* ---------- Creating Widget:    widResMainWindow -------------- */
  parent = WidResEditor;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 446); n++;
  XtSetArg(args[n], "width", 537); n++;
  XtSetArg(args[n], "x", 330); n++;
  XtSetArg(args[n], "y", 330); n++;


  /* Creating Widget */
  widResMainWindow = XtCreateWidget("widResMainWindow", xmMainWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(widResMainWindow);
  
  addQuickHelp(widResMainWindow);
  addHelpId(widResMainWindow,3);

  
  /* ---------- Creating Widget:    widResMenuBar -------------- */
  parent = widResMainWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  widResMenuBar = XmCreateMenuBar( parent, "widResMenuBar", args, n);
  
  /* Manage the Widget */
  XtManageChild(widResMenuBar);
  
  addQuickHelp(widResMenuBar);
  addHelpId(widResMenuBar,-1);

  
  /* ---------- Creating Widget:    fileButton -------------- */
  parent = widResMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileButton = XtCreateWidget("fileButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(fileButton);
  
  addQuickHelp(fileButton);
  addHelpId(fileButton,-1);

  
  /* ---------- Creating Widget:    fileMenu -------------- */
  parent = widResMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileMenu = XmCreatePulldownMenu( parent, "fileMenu", args, n);
  
  addQuickHelp(fileMenu);
  addHelpId(fileMenu,-1);

  
  /* ---------- Creating Widget:    loadButton -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "acceleratorText", RES_CONVERT("XmString", "^L")); n++;


  /* Creating Widget */
  loadButton = XtCreateWidget("loadButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(loadButton);
  
  addQuickHelp(loadButton);
  addHelpId(loadButton,-1);

  
  /* ---------- Creating Widget:    applyButton -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  applyButton = XtCreateWidget("applyButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(applyButton);
  
  addQuickHelp(applyButton);
  addHelpId(applyButton,-1);

  
  /* ---------- Creating Widget:    applyToButton -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  applyToButton = XtCreateWidget("applyToButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  addQuickHelp(applyToButton);
  addHelpId(applyToButton,-1);

  
  /* ---------- Creating Widget:    applyToMenu -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  applyToMenu = XmCreatePulldownMenu( parent, "applyToMenu", args, n);
  
  addQuickHelp(applyToMenu);
  addHelpId(applyToMenu,-1);

  
  /* ---------- Creating Widget:    selectedButton -------------- */
  parent = applyToMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  selectedButton = XtCreateWidget("selectedButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(selectedButton);
  
  addQuickHelp(selectedButton);
  addHelpId(selectedButton,-1);

  
  /* ---------- Creating Widget:    meAndSiblingsButton -------------- */
  parent = applyToMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  meAndSiblingsButton = XtCreateWidget("meAndSiblingsButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(meAndSiblingsButton);
  
  addQuickHelp(meAndSiblingsButton);
  addHelpId(meAndSiblingsButton,-1);

  
  /* ---------- Creating Widget:    meAndChildrenButton -------------- */
  parent = applyToMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  meAndChildrenButton = XtCreateWidget("meAndChildrenButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(meAndChildrenButton);
  
  addQuickHelp(meAndChildrenButton);
  addHelpId(meAndChildrenButton,-1);

  
  /* ---------- Creating Widget:    meAndAllButton -------------- */
  parent = applyToMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  meAndAllButton = XtCreateWidget("meAndAllButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(meAndAllButton);
  
  addQuickHelp(meAndAllButton);
  addHelpId(meAndAllButton,-1);

  
  /* ---------- Creating Widget:    unhandledResources -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  unhandledResources = XtCreateWidget("unhandledResources", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(unhandledResources);
  
  addQuickHelp(unhandledResources);
  addHelpId(unhandledResources,-1);

  
  /* ---------- Creating Widget:    separator -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  separator = XtCreateWidget("separator", xmSeparatorWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(separator);
  
  addQuickHelp(separator);
  addHelpId(separator,-1);

  
  /* ---------- Creating Widget:    closeButton -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  closeButton = XtCreateWidget("closeButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(closeButton);
  
  addQuickHelp(closeButton);
  addHelpId(closeButton,-1);

  
  /* ---------- Creating Widget:    viewButton -------------- */
  parent = widResMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  viewButton = XtCreateWidget("viewButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(viewButton);
  
  addQuickHelp(viewButton);
  addHelpId(viewButton,-1);

  
  /* ---------- Creating Widget:    viewMenu -------------- */
  parent = widResMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "radioBehavior", 1); n++;


  /* Creating Widget */
  viewMenu = XmCreatePulldownMenu( parent, "viewMenu", args, n);
  
  addQuickHelp(viewMenu);
  addHelpId(viewMenu,-1);

  
  /* ---------- Creating Widget:    coreButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "acceleratorText", RES_CONVERT("XmString", "^1")); n++;
  XtSetArg(args[n], "set", 1); n++;


  /* Creating Widget */
  coreButton = XtCreateWidget("coreButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(coreButton);
  
  addQuickHelp(coreButton);
  addHelpId(coreButton,-1);

  
  /* ---------- Creating Widget:    specificButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  specificButton = XtCreateWidget("specificButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(specificButton);
  
  addQuickHelp(specificButton);
  addHelpId(specificButton,-1);

  
  /* ---------- Creating Widget:    constraintButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  constraintButton = XtCreateWidget("constraintButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(constraintButton);
  
  addQuickHelp(constraintButton);
  addHelpId(constraintButton,-1);

  
  /* ---------- Creating Widget:    callbackButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  callbackButton = XtCreateWidget("callbackButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(callbackButton);
  
  addQuickHelp(callbackButton);
  addHelpId(callbackButton,-1);

  
  /* ---------- Creating Widget:    extraButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  extraButton = XtCreateWidget("extraButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(extraButton);
  
  addQuickHelp(extraButton);
  addHelpId(extraButton,-1);

  
  /* ---------- Creating Widget:    userButton -------------- */
  parent = viewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "accelerator", "Ctrl<Key>6"); n++;
  XtSetArg(args[n], "acceleratorText", RES_CONVERT("XmString", "^6")); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "User")); n++;
  XtSetArg(args[n], "mnemonic", RES_CONVERT("KeySym", "U")); n++;


  /* Creating Widget */
  userButton = XtCreateWidget("userButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  addQuickHelp(userButton);
  addHelpId(userButton,-1);

  
  /* ---------- Creating Widget:    optionsButton -------------- */
  parent = widResMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  optionsButton = XtCreateWidget("optionsButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(optionsButton);
  
  addQuickHelp(optionsButton);
  addHelpId(optionsButton,-1);

  
  /* ---------- Creating Widget:    optionsMenu -------------- */
  parent = widResMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  optionsMenu = XmCreatePulldownMenu( parent, "optionsMenu", args, n);
  
  addQuickHelp(optionsMenu);
  addHelpId(optionsMenu,-1);

  
  /* ---------- Creating Widget:    automaticLoad -------------- */
  parent = optionsMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "mnemonic", RES_CONVERT("KeySym", "t")); n++;


  /* Creating Widget */
  automaticLoad = XtCreateWidget("automaticLoad", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(automaticLoad);
  
  addQuickHelp(automaticLoad);
  addHelpId(automaticLoad,-1);

  
  /* ---------- Creating Widget:    withSource -------------- */
  parent = optionsMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "mnemonic", RES_CONVERT("KeySym", "S")); n++;


  /* Creating Widget */
  withSource = XtCreateWidget("withSource", xmToggleButtonWidgetClass,
			parent, args, n);
  
  addQuickHelp(withSource);
  addHelpId(withSource,-1);

  
  /* ---------- Creating Widget:    helpButton -------------- */
  parent = widResMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  helpButton = XtCreateWidget("helpButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(helpButton);
  
  addQuickHelp(helpButton);
  addHelpId(helpButton,-1);

  
  /* ---------- Creating Widget:    helpMenu -------------- */
  parent = widResMenuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  helpMenu = XmCreatePulldownMenu( parent, "helpMenu", args, n);
  
  addQuickHelp(helpMenu);
  addHelpId(helpMenu,-1);

  
  /* ---------- Creating Widget:    onHelp -------------- */
  parent = helpMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  onHelp = XtCreateWidget("onHelp", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(onHelp);
  
  addQuickHelp(onHelp);
  addHelpId(onHelp,-1);

  
  /* ---------- Creating Widget:    onContext -------------- */
  parent = helpMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "On Context")); n++;


  /* Creating Widget */
  onContext = XtCreateWidget("onContext", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(onContext);
  
  addQuickHelp(onContext);
  addHelpId(onContext,-1);

  
  /* ---------- Creating Widget:    onWidResEditor -------------- */
  parent = helpMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "On Window")); n++;
  XtSetArg(args[n], "mnemonic", RES_CONVERT("KeySym", "W")); n++;


  /* Creating Widget */
  onWidResEditor = XtCreateWidget("onWidResEditor", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(onWidResEditor);
  
  addQuickHelp(onWidResEditor);
  addHelpId(onWidResEditor,-1);

  
  /* ---------- Creating Widget:    widResForm -------------- */
  parent = widResMainWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 415); n++;
  XtSetArg(args[n], "width", 537); n++;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 16); n++;


  /* Creating Widget */
  widResForm = XtCreateWidget("widResForm", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(widResForm);
  
  addQuickHelp(widResForm);
  addHelpId(widResForm,-1);

  
  /* ---------- Creating Widget:    xlButtonBox_1 -------------- */
  parent = widResForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "entryMarginHeight", 5); n++;
  XtSetArg(args[n], "entryMarginWidth", 10); n++;
  XtSetArg(args[n], "spacing", 5); n++;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "bottomOffset", 0); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;


  /* Creating Widget */
  xlButtonBox_1 = XtCreateWidget("xlButtonBox_1", xlButtonBoxWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(xlButtonBox_1);
  
  addQuickHelp(xlButtonBox_1);
  addHelpId(xlButtonBox_1,-1);

  
  /* ---------- Creating Widget:    applyButton2 -------------- */
  parent = xlButtonBox_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  applyButton2 = XtCreateWidget("applyButton2", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(applyButton2);
  
  addQuickHelp(applyButton2);
  addHelpId(applyButton2,-1);

  
  /* ---------- Creating Widget:    closeButton2 -------------- */
  parent = xlButtonBox_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 20); n++;
  XtSetArg(args[n], "y", 20); n++;


  /* Creating Widget */
  closeButton2 = XtCreateWidget("closeButton2", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(closeButton2);
  
  addQuickHelp(closeButton2);
  addHelpId(closeButton2,-1);

  
  /* ---------- Creating Widget:    helpButton2 -------------- */
  parent = xlButtonBox_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 50); n++;
  XtSetArg(args[n], "y", 20); n++;


  /* Creating Widget */
  helpButton2 = XtCreateWidget("helpButton2", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(helpButton2);
  
  addQuickHelp(helpButton2);
  addHelpId(helpButton2,-1);

  
  /* ---------- Creating Widget:    scrolledWindow_1 -------------- */
  parent = widResForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 336); n++;
  XtSetArg(args[n], "width", 527); n++;
  XtSetArg(args[n], "x", 20); n++;
  XtSetArg(args[n], "y", 10); n++;
  XtSetArg(args[n], "scrollingPolicy", 0); n++;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 5); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 5); n++;
  XtSetArg(args[n], "topAttachment", 3); n++;
  XtSetArg(args[n], "topOffset", 1); n++;


  /* Creating Widget */
  scrolledWindow_1 = XtCreateWidget("scrolledWindow_1", xmScrolledWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(scrolledWindow_1);
  
  addQuickHelp(scrolledWindow_1);
  addHelpId(scrolledWindow_1,-1);

  
  /* ---------- Creating Widget:    categoryLabel -------------- */
  parent = widResForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 260); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 7); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 4); n++;


  /* Creating Widget */
  categoryLabel = XtCreateWidget("categoryLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(categoryLabel);
  
  addQuickHelp(categoryLabel);
  addHelpId(categoryLabel,-1);

  
  /* ---------- Creating Widget:    currentCategoryLabel -------------- */
  parent = widResForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 17); n++;
  XtSetArg(args[n], "width", 120); n++;
  XtSetArg(args[n], "x", 65); n++;
  XtSetArg(args[n], "y", 4); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "Core")); n++;
  XtSetArg(args[n], "leftAttachment", 3); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 4); n++;


  /* Creating Widget */
  currentCategoryLabel = XtCreateWidget("currentCategoryLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(currentCategoryLabel);
  
  addQuickHelp(currentCategoryLabel);
  addHelpId(currentCategoryLabel,-1);

  
  /* ---------- Creating Widget:    automaticLoadLabel -------------- */
  parent = widResForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 260); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "labelString", RES_CONVERT("XmString", "Automatic Load: On")); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 5); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 4); n++;


  /* Creating Widget */
  automaticLoadLabel = XtCreateWidget("automaticLoadLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(automaticLoadLabel);
  
  addQuickHelp(automaticLoadLabel);
  addHelpId(automaticLoadLabel,-1);

  
  /* ---------- Creating Widget:    quickHelp -------------- */
  parent = widResForm;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 260); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "alignment", 0); n++;
  XtSetArg(args[n], "bottomAttachment", 1); n++;
  XtSetArg(args[n], "bottomOffset", 1); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;


  /* Creating Widget */
  quickHelp = XtCreateWidget("quickHelp", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(quickHelp);
  
  addQuickHelp(quickHelp);
  addHelpId(quickHelp,-1);

  
  /* ---------- Creating Widget:    messageDialog -------------- */
  parent = widResMainWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "messageString", RES_CONVERT("XmString", "This list displays resources which are\nnot editable by VDX.")); n++;


  /* Creating Widget */
  messageDialog = XmCreateMessageDialog( parent, "messageDialog", args, n);
  
  addQuickHelp(messageDialog);
  addHelpId(messageDialog,48);

  
  /* ---------- Creating Widget:    scrolledWindow -------------- */
  parent = messageDialog;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  scrolledWindow = XtCreateWidget("scrolledWindow", xmScrolledWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(scrolledWindow);
  
  addQuickHelp(scrolledWindow);
  addHelpId(scrolledWindow,-1);

  
  /* ---------- Creating Widget:    list -------------- */
  parent = scrolledWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "visibleItemCount", 10); n++;


  /* Creating Widget */
  list = XtCreateWidget("list", xmListWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(list);
  
  addQuickHelp(list);
  addHelpId(list,-1);


}



// ----------------------------
// addCallbacks()
// ----------------------------

void WidResEditor_base::addCallbacks()
{

  XtAddCallback( loadButton, "activateCallback",
                 do_load_CB, this);

  XtAddCallback( applyButton, "activateCallback",
                 do_apply_CB, this);

  XtAddCallback( unhandledResources, "activateCallback",
                 manageWidget, (XtPointer)messageDialog); 

  XtAddCallback( closeButton, "activateCallback",
                 do_close_CB, this);

  XtAddCallback( viewMenu, "entryCallback",
                 do_viewChanged_CB, this);

  XtAddCallback( automaticLoad, "valueChangedCallback",
                 do_automaticLoad_CB, this);

  XtAddCallback( withSource, "valueChangedCallback",
                 do_withSource_CB, this);

  XtAddCallback( onHelp, "activateCallback",
                 do_onHelp_CB, this);

  XtAddCallback( onContext, "activateCallback",
                 do_onContext_CB, this);

  XtAddCallback( onWidResEditor, "activateCallback",
                 do_help_CB, this);

  XtAddCallback( applyButton2, "activateCallback",
                 do_apply_CB, this);

  XtAddCallback( closeButton2, "activateCallback",
                 do_close_CB, this);

  XtAddCallback( helpButton2, "activateCallback",
                 do_help_CB, this);

}



// ----------------------------
// addRelations()
// ----------------------------

void WidResEditor_base::addRelations()
{
  XtVaSetValues(widResMenuBar, "menuHelpWidget", helpButton, NULL);

  XtVaSetValues(fileButton, "subMenuId", fileMenu, NULL);

  XtVaSetValues(applyToButton, "subMenuId", applyToMenu, NULL);

  XtVaSetValues(viewButton, "subMenuId", viewMenu, NULL);

  XtVaSetValues(optionsButton, "subMenuId", optionsMenu, NULL);

  XtVaSetValues(helpButton, "subMenuId", helpMenu, NULL);

  XtVaSetValues(xlButtonBox_1, "bottomWidget", quickHelp, NULL);

  XtVaSetValues(scrolledWindow_1, "bottomWidget", xlButtonBox_1, NULL);

  XtVaSetValues(scrolledWindow_1, "topWidget", categoryLabel, NULL);

  XtVaSetValues(currentCategoryLabel, "leftWidget", categoryLabel, NULL);


}


// ----------------------------
// manageWidget()
// ----------------------------
void WidResEditor_base::manageWidget(Widget, XtPointer c, XtPointer)
{
  XtManageChild((Widget)c);
}


// ----------------------------
// createPixmapFromData()
// ----------------------------

Pixmap WidResEditor_base::createPixmapFromData(char **data)
{
  Pixmap pix, mask;
  XpmAttributes attr;

  memset(&attr, 0, sizeof(attr));
  attr.valuemask = XpmReturnPixels;

  if( !XpmCreatePixmapFromData(XtDisplay(LicView::getTopLevel()),
		               XRootWindowOfScreen(XtScreen(LicView::getTopLevel())),
			       data,
			       &pix, &mask, &attr) )
    return pix;
  return XmUNSPECIFIED_PIXMAP;
}

// ------------------------------------------
// createPixmapFromFile()
//
// Creating a pixmap by XpmRaedFileToPixmap()
// Uses XFILESEARCHPATH to find the pixmap
// default path: /usr/lib/X11/pixmaps/%N.xpm
// ------------------------------------------

Pixmap WidResEditor_base::createPixmapFromFile(char *name)
{
  String string;
  Pixmap pix, mask;
  XpmAttributes attr;

  string = XtResolvePathname(XtDisplay(LicView::getTopLevel()),
			     "pixmaps", name, "", NULL,
			     NULL, 0, NULL);
  if(string) {
    memset(&attr, 0, sizeof(attr));
    attr.valuemask = XpmReturnPixels;
    if( !XpmReadFileToPixmap(XtDisplay(LicView::getTopLevel()),
			     XRootWindowOfScreen(
			     XtScreen(LicView::getTopLevel())),
			     string,
			     &pix, &mask, &attr) )
      return pix;
    return XmUNSPECIFIED_PIXMAP;
    XtFree(string);
  }
  return XmUNSPECIFIED_PIXMAP;
}

// ---------------------------------------------------------
// Following class method are used as a callback.
// The method is calling a abstract virtual method, which
// must be overloaded in the derived class 'WidResEditor'
// ---------------------------------------------------------

void WidResEditor_base::do_load_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidResEditor_base*)clientData)->do_load(wg,callData);
}

void WidResEditor_base::do_apply_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidResEditor_base*)clientData)->do_apply(wg,callData);
}

void WidResEditor_base::do_close_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidResEditor_base*)clientData)->do_close(wg,callData);
}

void WidResEditor_base::do_viewChanged_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidResEditor_base*)clientData)->do_viewChanged(wg,callData);
}

void WidResEditor_base::do_automaticLoad_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidResEditor_base*)clientData)->do_automaticLoad(wg,callData);
}

void WidResEditor_base::do_withSource_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidResEditor_base*)clientData)->do_withSource(wg,callData);
}

void WidResEditor_base::do_onHelp_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidResEditor_base*)clientData)->do_onHelp(wg,callData);
}

void WidResEditor_base::do_onContext_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidResEditor_base*)clientData)->do_onContext(wg,callData);
}

void WidResEditor_base::do_help_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((WidResEditor_base*)clientData)->do_help(wg,callData);
}


