/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
/* ------------------------------------------ */
/* CalcWindow.h                                  */
/*                                            */
/* This file was automaticly generated by     */
/* View Designer/X                            */ 
/*                                            */
/* ------------------------------------------ */

#ifndef _CalcWindow_H_
#define _CalcWindow_H_


/* Include the base module */

#include "CalcWindow_base.h"


/* ------------------------------------------ */
/*                                            */
/* Edit the following structure to add        */
/* associated data                            */
/*                                            */
/* ------------------------------------------ */

typedef struct _CalcWindow {
	CalcWindow_base base;             /* The widgets */
} CalcWindow;



/* ------------------------------------------ */
/* initialization function of this module     */
/* ------------------------------------------ */

extern CalcWindow *createCalcWindow(
#if NeedFunctionPrototypes
	Widget,	ArgList, Cardinal
#endif
);


/* ------------------------------------------ */
/* Methods, you have to implement             */
/* ------------------------------------------ */

extern void do_addition(
#if NeedFunctionPrototypes
    	CalcWindow*, Widget, XtPointer
#endif
);




#endif /* Don't add stuff after this #endif */
