/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
/* --------------------------------------- */
/* The Mainprogramm                        */
/*                                         */
/* This file was automaticly generated by  */
/* View Designer/X                         */
/*                                         */
/* --------------------------------------- */


#include <stdio.h>
#include "vcmisc.h"
#include "CalcWindow.h"

char *fallback = 
#include "Calcy_res.h"
;


/* --------------------------------------- */
/* main()                                  */
/* --------------------------------------- */

void main(argc, argv)
     int argc;
     char **argv;
{
  CalcWindow *mw;

  vcinit("Calcy", argc, argv, fallback);       


  mw = createCalcWindow(NULL,NULL,0);        /* Create startup view */

  XtPopup(mw->base.popupShell, XtGrabNone);  /* Popup startup view  */


  vcrun();                                   /* run mainloop        */
}
