/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// ----------------------------
// TextWindow.h
// ----------------------------

#ifndef _TextWindow_H_
#define _TextWindow_H_

#include "TextWindow_base.h"
#include <limits.h>

// some kind of preprocessor code to be sure that MY_PATH_MAX
// has the right value

#ifdef PATH_MAX
#if PATH_MAX > 4096              // to big
#define MY_PATH_MAX 4096
#else
#define MY_PATH_MAX PATH_MAX
#endif  // PATH_MAX > 4096
#else
#define MY_PATH_MAX 4096
#endif  // PATH_MAX


// class TextWindow. Parts of this class were generated by VDX.
// We added our own stuff.

class TextWindow : public TextWindow_base {
protected:
  virtual void do_save(Widget,XtPointer);
  virtual void do_cut(Widget,XtPointer);
  virtual void do_copy(Widget,XtPointer);
  virtual void do_paste(Widget,XtPointer);
  virtual void text_changed(Widget,XtPointer);
  virtual void do_exit(Widget,XtPointer);
  virtual void do_open(Widget,XtPointer);
  virtual void do_saveAs(Widget,XtPointer);

  Boolean hasChanged;
  char filename[MY_PATH_MAX];

  // helpful methods
  void updateTitleBar();
  Boolean saveFile(char *fname);
  void getFSBfilename(Widget, char buf[MY_PATH_MAX]);

  // the window mananger callback
  static void wmDelete(Widget, XtPointer, XtPointer);

public:
  TextWindow(Widget parent = NULL, ArgList args = NULL, Cardinal n = 0);

  Boolean loadFile(char *fname);
};


TextWindow *createTextWindow(Widget parent, ArgList args, Cardinal n);

#endif /* Don't add stuff after this #endif */
