/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// ---------------------------------------
// TextWindow_base.C
// This file was automaticly generated by
// View Designer/X
// 
// Don't edit this file, please !
// ---------------------------------------


// Include class definition

#include "TextWindow_base.h"

// Include X11 header
#include <X11/xpm.h>

// Include OSF/Motif header files
#include <Xm/Frame.h>
#include <X11/Shell.h>
#include <Xm/MainW.h>
#include <Xm/RowColumn.h>
#include <Xm/CascadeB.h>
#include <Xm/PushB.h>
#include <Xm/Text.h>
#include <Xm/MessageB.h>
#include <Xm/FileSB.h>








#define RES_CONVERT(t,s) cvtResourceFromString(parent, t, s)


// -----------------------------------
// TextWindow_base(parent,args,n)
// -----------------------------------

TextWindow_base::TextWindow_base(Widget p, ArgList f_args, Cardinal f_n)
{
  Widget parent;
  Arg args[100];
  Cardinal n = 0;

  if(p) 
    parent = p;
  else
    parent = getTopLevel();

  if(p) {
    TextWindow = XtCreateWidget("TextWindow",xmFrameWidgetClass,
				       parent,f_args,f_n);
  } else { 
   
    popupShell = TextWindow = XtCreatePopupShell("TextWindow", topLevelShellWidgetClass,
			parent, args, n);
  }
  createWidgets();
  addCallbacks();
  addRelations();
}


// ----------------------------
// createWidgets()
// ----------------------------

void TextWindow_base::createWidgets()
{
  Widget parent;           // the parent for every widget
  Arg args[100];           // resource list
  Cardinal n;              // number of resources

  // Now we create every Widget

  
  /* ---------- Creating Widget:    mainWindow -------------- */
  parent = TextWindow;

  /* Building resource list */
  n = 0;


  /* Creating Widget */
  mainWindow = XtCreateWidget("mainWindow", xmMainWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(mainWindow);
  


  
  /* ---------- Creating Widget:    menuBar -------------- */
  parent = mainWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 60); n++;
  XtSetArg(args[n], "y", 10); n++;


  /* Creating Widget */
  menuBar = XmCreateMenuBar( parent, "menuBar", args, n);
  
  /* Manage the Widget */
  XtManageChild(menuBar);
  


  
  /* ---------- Creating Widget:    fileButton -------------- */
  parent = menuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileButton = XtCreateWidget("fileButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(fileButton);
  


  
  /* ---------- Creating Widget:    fileMenu -------------- */
  parent = menuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  fileMenu = XmCreatePulldownMenu( parent, "fileMenu", args, n);
  


  
  /* ---------- Creating Widget:    openButton -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  openButton = XtCreateWidget("openButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(openButton);
  


  
  /* ---------- Creating Widget:    saveButton -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  saveButton = XtCreateWidget("saveButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(saveButton);
  


  
  /* ---------- Creating Widget:    saveAsButton -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  saveAsButton = XtCreateWidget("saveAsButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(saveAsButton);
  


  
  /* ---------- Creating Widget:    exitButton -------------- */
  parent = fileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  exitButton = XtCreateWidget("exitButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(exitButton);
  


  
  /* ---------- Creating Widget:    editButton -------------- */
  parent = menuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  editButton = XtCreateWidget("editButton", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(editButton);
  


  
  /* ---------- Creating Widget:    editMenu -------------- */
  parent = menuBar;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  editMenu = XmCreatePulldownMenu( parent, "editMenu", args, n);
  


  
  /* ---------- Creating Widget:    cutButton -------------- */
  parent = editMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  cutButton = XtCreateWidget("cutButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(cutButton);
  


  
  /* ---------- Creating Widget:    copyButton -------------- */
  parent = editMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  copyButton = XtCreateWidget("copyButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(copyButton);
  


  
  /* ---------- Creating Widget:    pasteButton -------------- */
  parent = editMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  pasteButton = XtCreateWidget("pasteButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(pasteButton);
  


  
  /* ---------- Creating Widget:    textWidget -------------- */
  parent = mainWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 20); n++;
  XtSetArg(args[n], "columns", 60); n++;
  XtSetArg(args[n], "editMode", XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], "rows", 20); n++;


  /* Creating Widget */
  textWidget = XtCreateWidget("textWidget", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(textWidget);
  


  
  /* ---------- Creating Widget:    exitDialog -------------- */
  parent = mainWindow;

  /* Building resource list */
  n = 0;


  /* Creating Widget */
  exitDialog = XmCreateQuestionDialog( parent, "exitDialog", args, n);
  


  
  /* ---------- Creating Widget:    fileOpenDialog -------------- */
  parent = mainWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "autoUnmanage", 1); n++;


  /* Creating Widget */
  fileOpenDialog = XmCreateFileSelectionDialog( parent, "fileOpenDialog", args, n);
  


  
  /* ---------- Creating Widget:    fileSaveAsDialog -------------- */
  parent = mainWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "autoUnmanage", 1); n++;


  /* Creating Widget */
  fileSaveAsDialog = XmCreateFileSelectionDialog( parent, "fileSaveAsDialog", args, n);
  


  
  /* ---------- Creating Widget:    noHelpDialog -------------- */
  parent = mainWindow;

  /* Building resource list */
  n = 0;


  /* Creating Widget */
  noHelpDialog = XmCreateWarningDialog( parent, "noHelpDialog", args, n);
  



}



// ----------------------------
// addCallbacks()
// ----------------------------

void TextWindow_base::addCallbacks()
{

  XtAddCallback( mainWindow, "helpCallback",
                 manageWidget, (XtPointer)noHelpDialog); 

  XtAddCallback( openButton, "activateCallback",
                 manageWidget, (XtPointer)fileOpenDialog); 

  XtAddCallback( saveButton, "activateCallback",
                 do_save_CB, this);

  XtAddCallback( saveAsButton, "activateCallback",
                 manageWidget, (XtPointer)fileSaveAsDialog); 

  XtAddCallback( exitButton, "activateCallback",
                 manageWidget, (XtPointer)exitDialog); 

  XtAddCallback( cutButton, "activateCallback",
                 do_cut_CB, this);

  XtAddCallback( copyButton, "activateCallback",
                 do_copy_CB, this);

  XtAddCallback( pasteButton, "activateCallback",
                 do_paste_CB, this);

  XtAddCallback( textWidget, "valueChangedCallback",
                 text_changed_CB, this);

  XtAddCallback( exitDialog, "okCallback",
                 do_exit_CB, this);

  XtAddCallback( fileOpenDialog, "okCallback",
                 do_open_CB, this);

  XtAddCallback( fileSaveAsDialog, "okCallback",
                 do_saveAs_CB, this);

}



// ----------------------------
// addRelations()
// ----------------------------

void TextWindow_base::addRelations()
{
  XtVaSetValues(fileButton, "subMenuId", fileMenu, NULL);

  XtVaSetValues(editButton, "subMenuId", editMenu, NULL);


}


// ----------------------------
// manageWidget()
// ----------------------------
void TextWindow_base::manageWidget(Widget, XtPointer c, XtPointer)
{
  XtManageChild((Widget)c);
}


// ----------------------------
// createPixmapFromData()
// ----------------------------

Pixmap TextWindow_base::createPixmapFromData(char **data)
{
  Pixmap pix, mask;
  XpmAttributes attr;

  memset(&attr, 0, sizeof(attr));
  attr.valuemask = XpmReturnPixels;

  if( !XpmCreatePixmapFromData(XtDisplay(VcView::getTopLevel()),
		               XRootWindowOfScreen(XtScreen(VcView::getTopLevel())),
			       data,
			       &pix, &mask, &attr) )
    return pix;
  return XmUNSPECIFIED_PIXMAP;
}

// ------------------------------------------
// createPixmapFromFile()
//
// Creating a pixmap by XpmReadFileToPixmap()
// Uses XFILESEARCHPATH to find the pixmap
// default path: /usr/lib/X11/pixmaps/%N.xpm
// ------------------------------------------

Pixmap TextWindow_base::createPixmapFromFile(char *name)
{
  String string;
  Pixmap pix, mask;
  XpmAttributes attr;

  string = XtResolvePathname(XtDisplay(VcView::getTopLevel()),
			     "pixmaps", name, "", NULL,
			     NULL, 0, NULL);
  if(string) {
    memset(&attr, 0, sizeof(attr));
    attr.valuemask = XpmReturnPixels;
    if( !XpmReadFileToPixmap(XtDisplay(VcView::getTopLevel()),
			     XRootWindowOfScreen(
			     XtScreen(VcView::getTopLevel())),
			     string,
			     &pix, &mask, &attr) )
      return pix;
    return XmUNSPECIFIED_PIXMAP;
    XtFree(string);
  }
  return XmUNSPECIFIED_PIXMAP;
}

// ---------------------------------------------------------
// Following class methods are used as a callback.
// The method is calling a abstract virtual method, which
// must be overloaded in the derived class 'TextWindow'
// ---------------------------------------------------------

void TextWindow_base::do_save_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextWindow_base*)clientData)->do_save(wg,callData);
}

void TextWindow_base::do_cut_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextWindow_base*)clientData)->do_cut(wg,callData);
}

void TextWindow_base::do_copy_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextWindow_base*)clientData)->do_copy(wg,callData);
}

void TextWindow_base::do_paste_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextWindow_base*)clientData)->do_paste(wg,callData);
}

void TextWindow_base::text_changed_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextWindow_base*)clientData)->text_changed(wg,callData);
}

void TextWindow_base::do_exit_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextWindow_base*)clientData)->do_exit(wg,callData);
}

void TextWindow_base::do_open_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextWindow_base*)clientData)->do_open(wg,callData);
}

void TextWindow_base::do_saveAs_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((TextWindow_base*)clientData)->do_saveAs(wg,callData);
}


