/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// ---------------------------------------
// HelpView_base.C
//
// This file was automaticly generated by
// View Designer/X v1.1.beta
//
// User: lazy@apfel.goetting5
// Date: Sun Mar  9 17:54:22 1997
// 
// Don't edit this file, please !
// ---------------------------------------


// Include class definition

#include "HelpView_base.h"

// Include X11 header
#include <X11/xpm.h>

// Include OSF/Motif header files
#include <Xm/Frame.h>
#include <X11/Shell.h>
#include <Xm/Form.h>
#include <Xm/ScrolledW.h>
#include <Xm/Text.h>
#include <Xm/Separator.h>
#include <Xm/PushB.h>








#define RES_CONVERT(t,s) cvtResourceFromString(parent, t, s)


// -----------------------------------
// HelpView_base(parent,args,n)
// -----------------------------------

HelpView_base::HelpView_base(Widget p, ArgList f_args, Cardinal f_n)
{
  Widget parent;
  Arg args[100];
  Cardinal n = 0;

  if(p) 
    parent = p;
  else
    parent = getTopLevel();

  if(p) {
    HelpView = XtCreateWidget("HelpView",xmFrameWidgetClass,
				       parent,f_args,f_n);
  } else { 
   
    popupShell = HelpView = XtCreatePopupShell("HelpView", topLevelShellWidgetClass,
			parent, args, n);
  }
  createWidgets();
  addCallbacks();
  addRelations();
}


// ----------------------------
// createWidgets()
// ----------------------------

void HelpView_base::createWidgets()
{
  Widget parent;           // the parent for every widget
  Arg args[100];           // resource list
  Cardinal n;              // number of resources

  // Now we create every Widget

  
  /* ---------- Creating Widget:    form_1 -------------- */
  parent = HelpView;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 325); n++;
  XtSetArg(args[n], "width", 400); n++;
  XtSetArg(args[n], "x", 50); n++;
  XtSetArg(args[n], "y", 80); n++;


  /* Creating Widget */
  form_1 = XtCreateWidget("form_1", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(form_1);
  


  
  /* ---------- Creating Widget:    scrolledWindow_1 -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 269); n++;
  XtSetArg(args[n], "width", 390); n++;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 10); n++;
  XtSetArg(args[n], "bottomAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "bottomOffset", 5); n++;
  XtSetArg(args[n], "leftAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "leftOffset", 5); n++;
  XtSetArg(args[n], "rightAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "rightOffset", 5); n++;
  XtSetArg(args[n], "topAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "topOffset", 5); n++;


  /* Creating Widget */
  scrolledWindow_1 = XtCreateWidget("scrolledWindow_1", xmScrolledWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(scrolledWindow_1);
  


  
  /* ---------- Creating Widget:    text -------------- */
  parent = scrolledWindow_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 70); n++;
  XtSetArg(args[n], "y", 30); n++;
  XtSetArg(args[n], "cursorPositionVisible", 0); n++;
  XtSetArg(args[n], "editMode", XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], "editable", 0); n++;
  XtSetArg(args[n], "fontList", RES_CONVERT("FontList", "-adobe-times-medium-r-normal--14-140-75-75-p-74-iso8859-1")); n++;
  XtSetArg(args[n], "scrollHorizontal", 0); n++;
  XtSetArg(args[n], "wordWrap", 1); n++;


  /* Creating Widget */
  text = XtCreateWidget("text", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(text);
  


  
  /* ---------- Creating Widget:    separator_1 -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 10); n++;
  XtSetArg(args[n], "width", 398); n++;
  XtSetArg(args[n], "x", 20); n++;
  XtSetArg(args[n], "y", 290); n++;
  XtSetArg(args[n], "bottomAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "bottomOffset", 5); n++;
  XtSetArg(args[n], "leftAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;


  /* Creating Widget */
  separator_1 = XtCreateWidget("separator_1", xmSeparatorWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(separator_1);
  


  
  /* ---------- Creating Widget:    pushButton_1 -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "width", 100); n++;
  XtSetArg(args[n], "x", 150); n++;
  XtSetArg(args[n], "y", 300); n++;
  XtSetArg(args[n], "fontList", RES_CONVERT("FontList", "-adobe-new century schoolbook-bold-r-normal--12-120-75-75-p-0-iso8859-1")); n++;
  XtSetArg(args[n], "bottomAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "bottomOffset", 5); n++;
  XtSetArg(args[n], "leftAttachment", XmATTACH_POSITION); n++;
  XtSetArg(args[n], "leftOffset", -50); n++;
  XtSetArg(args[n], "leftPosition", 50); n++;


  /* Creating Widget */
  pushButton_1 = XtCreateWidget("pushButton_1", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(pushButton_1);
  



}



// ----------------------------
// addCallbacks()
// ----------------------------

void HelpView_base::addCallbacks()
{

  XtAddCallback( pushButton_1, "activateCallback",
                 close_window_CB, this);

}



// ----------------------------
// addRelations()
// ----------------------------

void HelpView_base::addRelations()
{
  XtVaSetValues(scrolledWindow_1, "bottomWidget", separator_1, NULL);

  XtVaSetValues(separator_1, "bottomWidget", pushButton_1, NULL);


}


// ----------------------------
// manageWidget()
// ----------------------------
void HelpView_base::manageWidget(Widget, XtPointer c, XtPointer)
{
  XtManageChild((Widget)c);
}


// ----------------------------
// createPixmapFromData()
// ----------------------------

Pixmap HelpView_base::createPixmapFromData(char **data)
{
  Pixmap pix, mask;
  XpmAttributes attr;

  memset(&attr, 0, sizeof(attr));
  attr.valuemask = XpmReturnPixels;

  if( !XpmCreatePixmapFromData(XtDisplay(VcView::getTopLevel()),
		               XRootWindowOfScreen(XtScreen(VcView::getTopLevel())),
			       data,
			       &pix, &mask, &attr) )
    return pix;
  return XmUNSPECIFIED_PIXMAP;
}

// ------------------------------------------
// createPixmapFromFile()
//
// Creating a pixmap by XpmReadFileToPixmap()
// Uses XFILESEARCHPATH to find the pixmap
// default path: /usr/lib/X11/pixmaps/%N.xpm
// ------------------------------------------

Pixmap HelpView_base::createPixmapFromFile(char *name)
{
  String string;
  Pixmap pix, mask;
  XpmAttributes attr;

  string = XtResolvePathname(XtDisplay(VcView::getTopLevel()),
			     "pixmaps", name, "", NULL,
			     NULL, 0, NULL);
  if(string) {
    memset(&attr, 0, sizeof(attr));
    attr.valuemask = XpmReturnPixels;
    if( !XpmReadFileToPixmap(XtDisplay(VcView::getTopLevel()),
			     XRootWindowOfScreen(
			     XtScreen(VcView::getTopLevel())),
			     string,
			     &pix, &mask, &attr) )
      return pix;
    return XmUNSPECIFIED_PIXMAP;
    XtFree(string);
  }
  return XmUNSPECIFIED_PIXMAP;
}

// ---------------------------------------------------------
// Following class methods are used as a callback.
// The method is calling a abstract virtual method, which
// must be overloaded in the derived class 'HelpView'
// ---------------------------------------------------------

void HelpView_base::close_window_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((HelpView_base*)clientData)->close_window(wg,callData);
}


