/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// -----------------------------------------------------
// HelpView_base.h
// 
// This file was automaticly generated by
// View Designer/X v1.1.beta
//
// User: lazy@apfel.goetting5
// Date: Sun Mar  9 17:54:22 1997
// 
// Don't edit this file, please !
// -----------------------------------------------------

#ifndef _HelpView_base_H_
#define _HelpView_base_H_

#include <X11/Intrinsic.h>
#include "VcView.h"



// -----------------------------------------------------
// Class definition 
// class HelpView_base is a derived class of VcView
// -----------------------------------------------------

class HelpView_base : public VcView {
private:
  void createWidgets();
  void addRelations();
  void addCallbacks();

protected:
  Widget HelpView;
  Widget form_1;      /* XmForm */
  Widget scrolledWindow_1;      /* XmScrolledWindow */
  Widget text;      /* XmText */
  Widget separator_1;      /* XmSeparator */
  Widget pushButton_1;      /* XmPushButton */


  static void close_window_CB(Widget,XtPointer,XtPointer);



  // override the following methods in class HelpView

  virtual void close_window(Widget,XtPointer) = 0;


public:
  HelpView_base(Widget parent = NULL, ArgList args = NULL, Cardinal n = 0);

  Widget getTop() { return HelpView; }
  Pixmap createPixmapFromData(char **data);
  Pixmap createPixmapFromFile(char *filename);
  static void manageWidget(Widget wg, XtPointer c, XtPointer call);
};

#endif /* Don't add stuff after this #endif */






