/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// ---------------------------------------
// ItemView_base.C
//
// This file was automaticly generated by
// View Designer/X v1.1.beta
//
// User: lazy@apfel.goetting5
// Date: Sun Mar  9 17:54:22 1997
// 
// Don't edit this file, please !
// ---------------------------------------


// Include class definition

#include "ItemView_base.h"

// Include X11 header
#include <X11/xpm.h>

// Include OSF/Motif header files
#include <Xm/Frame.h>
#include <X11/Shell.h>
#include <Xm/Form.h>
#include <Xm/RowColumn.h>
#include <Xm/PushB.h>
#include <Xm/Separator.h>
#include <Xm/Label.h>
#include <Xm/Text.h>
#include <Xm/ScrolledW.h>
#include <Xm/Frame.h>
#include <Xm/ToggleB.h>








#define RES_CONVERT(t,s) cvtResourceFromString(parent, t, s)


// -----------------------------------
// ItemView_base(parent,args,n)
// -----------------------------------

ItemView_base::ItemView_base(Widget p, ArgList f_args, Cardinal f_n)
{
  Widget parent;
  Arg args[100];
  Cardinal n = 0;

  if(p) 
    parent = p;
  else
    parent = getTopLevel();

  if(p) {
    ItemView = XtCreateWidget("ItemView",xmFrameWidgetClass,
				       parent,f_args,f_n);
  } else { 
     XtSetArg(args[n], "buttonFontList", RES_CONVERT("ButtonRenderTable", "-adobe-new century schoolbook-bold-r-normal--12-120-75-75-p-0-iso8859-1")); n++;
  XtSetArg(args[n], "labelFontList", RES_CONVERT("LabelRenderTable", "-adobe-new century schoolbook-bold-r-normal--12-120-75-75-p-0-iso8859-1")); n++;
  XtSetArg(args[n], "textFontList", RES_CONVERT("TextRenderTable", "-adobe-courier-medium-r-normal--12-120-75-75-m-70-iso8859-1_fmath")); n++;

    popupShell = ItemView = XtCreatePopupShell("ItemView", topLevelShellWidgetClass,
			parent, args, n);
  }
  createWidgets();
  addCallbacks();
  addRelations();
}


// ----------------------------
// createWidgets()
// ----------------------------

void ItemView_base::createWidgets()
{
  Widget parent;           // the parent for every widget
  Arg args[100];           // resource list
  Cardinal n;              // number of resources

  // Now we create every Widget

  
  /* ---------- Creating Widget:    form_1 -------------- */
  parent = ItemView;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 330); n++;
  XtSetArg(args[n], "width", 400); n++;
  XtSetArg(args[n], "x", 260); n++;
  XtSetArg(args[n], "y", 130); n++;


  /* Creating Widget */
  form_1 = XtCreateWidget("form_1", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(form_1);
  


  
  /* ---------- Creating Widget:    rowColumn_1 -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 31); n++;
  XtSetArg(args[n], "width", 390); n++;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 270); n++;
  XtSetArg(args[n], "entryAlignment", XmALIGNMENT_CENTER); n++;
  XtSetArg(args[n], "marginHeight", 5); n++;
  XtSetArg(args[n], "marginWidth", 5); n++;
  XtSetArg(args[n], "orientation", XmHORIZONTAL); n++;
  XtSetArg(args[n], "packing", XmPACK_COLUMN); n++;
  XtSetArg(args[n], "bottomAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "bottomOffset", 5); n++;
  XtSetArg(args[n], "leftAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "leftOffset", 5); n++;
  XtSetArg(args[n], "rightAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "rightOffset", 5); n++;


  /* Creating Widget */
  rowColumn_1 = XtCreateWidget("rowColumn_1", xmRowColumnWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(rowColumn_1);
  


  
  /* ---------- Creating Widget:    okButton -------------- */
  parent = rowColumn_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 20); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  okButton = XtCreateWidget("okButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(okButton);
  


  
  /* ---------- Creating Widget:    cancelButton -------------- */
  parent = rowColumn_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  cancelButton = XtCreateWidget("cancelButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(cancelButton);
  


  
  /* ---------- Creating Widget:    helpButton -------------- */
  parent = rowColumn_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  helpButton = XtCreateWidget("helpButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(helpButton);
  


  
  /* ---------- Creating Widget:    separator_1 -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 10); n++;
  XtSetArg(args[n], "width", 398); n++;
  XtSetArg(args[n], "x", 1); n++;
  XtSetArg(args[n], "y", 284); n++;
  XtSetArg(args[n], "bottomAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "leftAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;


  /* Creating Widget */
  separator_1 = XtCreateWidget("separator_1", xmSeparatorWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(separator_1);
  


  
  /* ---------- Creating Widget:    label_1 -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 30); n++;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 10); n++;
  XtSetArg(args[n], "leftAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "leftOffset", 5); n++;
  XtSetArg(args[n], "topAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "topOffset", 5); n++;


  /* Creating Widget */
  label_1 = XtCreateWidget("label_1", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(label_1);
  


  
  /* ---------- Creating Widget:    titleText -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "width", 346); n++;
  XtSetArg(args[n], "x", 90); n++;
  XtSetArg(args[n], "y", 10); n++;
  XtSetArg(args[n], "maxLength", 32); n++;
  XtSetArg(args[n], "leftAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "leftOffset", 5); n++;
  XtSetArg(args[n], "rightAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "rightOffset", 5); n++;
  XtSetArg(args[n], "topAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "topOffset", 5); n++;


  /* Creating Widget */
  titleText = XtCreateWidget("titleText", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(titleText);
  


  
  /* ---------- Creating Widget:    scrolledWindow_2 -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 234); n++;
  XtSetArg(args[n], "width", 269); n++;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 50); n++;
  XtSetArg(args[n], "bottomAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "bottomOffset", 1); n++;
  XtSetArg(args[n], "leftAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "leftOffset", 5); n++;
  XtSetArg(args[n], "rightAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "rightOffset", 5); n++;
  XtSetArg(args[n], "topAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "topOffset", 5); n++;


  /* Creating Widget */
  scrolledWindow_2 = XtCreateWidget("scrolledWindow_2", xmScrolledWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(scrolledWindow_2);
  


  
  /* ---------- Creating Widget:    text -------------- */
  parent = scrolledWindow_2;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "editMode", XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], "maxLength", 512); n++;
  XtSetArg(args[n], "scrollHorizontal", 0); n++;
  XtSetArg(args[n], "wordWrap", 1); n++;


  /* Creating Widget */
  text = XtCreateWidget("text", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(text);
  


  
  /* ---------- Creating Widget:    frame_1 -------------- */
  parent = form_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "rightAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "rightOffset", 5); n++;
  XtSetArg(args[n], "topAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "topOffset", 5); n++;


  /* Creating Widget */
  frame_1 = XtCreateWidget("frame_1", xmFrameWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(frame_1);
  


  
  /* ---------- Creating Widget:    radioBox_1 -------------- */
  parent = frame_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 143); n++;
  XtSetArg(args[n], "width", 103); n++;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  radioBox_1 = XmCreateRadioBox( parent, "radioBox_1", args, n);
  
  /* Manage the Widget */
  XtManageChild(radioBox_1);
  


  
  /* ---------- Creating Widget:    veryHighToggle -------------- */
  parent = radioBox_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 10); n++;
  XtSetArg(args[n], "set", XmSET); n++;


  /* Creating Widget */
  veryHighToggle = XtCreateWidget("veryHighToggle", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(veryHighToggle);
  


  
  /* ---------- Creating Widget:    highToggle -------------- */
  parent = radioBox_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  highToggle = XtCreateWidget("highToggle", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(highToggle);
  


  
  /* ---------- Creating Widget:    middleToggle -------------- */
  parent = radioBox_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  middleToggle = XtCreateWidget("middleToggle", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(middleToggle);
  


  
  /* ---------- Creating Widget:    lowToggle -------------- */
  parent = radioBox_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  lowToggle = XtCreateWidget("lowToggle", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(lowToggle);
  


  
  /* ---------- Creating Widget:    niceToHaveToggle -------------- */
  parent = radioBox_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  niceToHaveToggle = XtCreateWidget("niceToHaveToggle", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(niceToHaveToggle);
  


  
  /* ---------- Creating Widget:    label -------------- */
  parent = frame_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "childType", XmFRAME_TITLE_CHILD); n++;


  /* Creating Widget */
  label = XtCreateWidget("label", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(label);
  



}



// ----------------------------
// addCallbacks()
// ----------------------------

void ItemView_base::addCallbacks()
{

  XtAddCallback( form_1, "helpCallback",
                 help_me_CB, this);

  XtAddCallback( okButton, "activateCallback",
                 save_and_close_CB, this);

  XtAddCallback( cancelButton, "activateCallback",
                 close_view_CB, this);

  XtAddCallback( helpButton, "activateCallback",
                 help_me_CB, this);

}



// ----------------------------
// addRelations()
// ----------------------------

void ItemView_base::addRelations()
{
  XtVaSetValues(separator_1, "bottomWidget", rowColumn_1, NULL);

  XtVaSetValues(titleText, "leftWidget", label_1, NULL);

  XtVaSetValues(scrolledWindow_2, "bottomWidget", separator_1, NULL);

  XtVaSetValues(scrolledWindow_2, "rightWidget", frame_1, NULL);

  XtVaSetValues(scrolledWindow_2, "topWidget", titleText, NULL);

  XtVaSetValues(frame_1, "topWidget", titleText, NULL);


}


// ----------------------------
// manageWidget()
// ----------------------------
void ItemView_base::manageWidget(Widget, XtPointer c, XtPointer)
{
  XtManageChild((Widget)c);
}


// ----------------------------
// createPixmapFromData()
// ----------------------------

Pixmap ItemView_base::createPixmapFromData(char **data)
{
  Pixmap pix, mask;
  XpmAttributes attr;

  memset(&attr, 0, sizeof(attr));
  attr.valuemask = XpmReturnPixels;

  if( !XpmCreatePixmapFromData(XtDisplay(VcView::getTopLevel()),
		               XRootWindowOfScreen(XtScreen(VcView::getTopLevel())),
			       data,
			       &pix, &mask, &attr) )
    return pix;
  return XmUNSPECIFIED_PIXMAP;
}

// ------------------------------------------
// createPixmapFromFile()
//
// Creating a pixmap by XpmReadFileToPixmap()
// Uses XFILESEARCHPATH to find the pixmap
// default path: /usr/lib/X11/pixmaps/%N.xpm
// ------------------------------------------

Pixmap ItemView_base::createPixmapFromFile(char *name)
{
  String string;
  Pixmap pix, mask;
  XpmAttributes attr;

  string = XtResolvePathname(XtDisplay(VcView::getTopLevel()),
			     "pixmaps", name, "", NULL,
			     NULL, 0, NULL);
  if(string) {
    memset(&attr, 0, sizeof(attr));
    attr.valuemask = XpmReturnPixels;
    if( !XpmReadFileToPixmap(XtDisplay(VcView::getTopLevel()),
			     XRootWindowOfScreen(
			     XtScreen(VcView::getTopLevel())),
			     string,
			     &pix, &mask, &attr) )
      return pix;
    return XmUNSPECIFIED_PIXMAP;
    XtFree(string);
  }
  return XmUNSPECIFIED_PIXMAP;
}

// ---------------------------------------------------------
// Following class methods are used as a callback.
// The method is calling a abstract virtual method, which
// must be overloaded in the derived class 'ItemView'
// ---------------------------------------------------------

void ItemView_base::help_me_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ItemView_base*)clientData)->help_me(wg,callData);
}

void ItemView_base::save_and_close_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ItemView_base*)clientData)->save_and_close(wg,callData);
}

void ItemView_base::close_view_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ItemView_base*)clientData)->close_view(wg,callData);
}


