/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
/* -----------------------------------------
 * TabManager.c                           
 *                                          
 * This file was automaticly generated by   
 * View Designer/X v1.2.beta
 *                 
 * User: lazy@apfel.goetting5
 * Date: Sun Feb  8 18:49:30 1998
 *                         
 * -----------------------------------------
 */

#include <stdio.h>

#include "TabManager.h"

extern TabManager *createTabManager_base(
#if NeedFunctionPrototypes
    	Widget,	ArgList, Cardinal
#endif
);




/* ------------------------------------------ */
/* Initialization function of this module     */
/*                                            */
/* If you want to create a popupShell         */
/* parent must be NULL, otherwise you create  */
/* a Frame                                    */
/* ------------------------------------------ */

TabManager *createTabManager(parent, args, n)
	Widget parent;
	ArgList args;
	Cardinal n;
{
  TabManager *self;

  self = createTabManager_base(parent,args,n);
  
  /* Init you data associated with this view ... */

  return self;
}


/* ------------------------------------------ */
/* Impelemtation of your methods              */
/* ------------------------------------------ */





