#
# Makefile for src directory
#
# $Log: Makefile,v $
# Revision 1.1.1.1.2.1  1999/08/27 15:29:15  dirk
# Transform the copyright to GPL
#
# Revision 1.1.1.1  1998/04/24 23:45:12  lazy
# Imported to CVS
#
# Revision 1.2  1998/03/30 19:09:44  lazy
# *** empty log message ***
#
# Revision 1.1  1997/07/25  20:13:03  lazy
# Initial revision
#
#

TOPDIR = ..
SUBDIRS = parse lwid Xfe lac vdxlib lic
PROGRAM = dummy
LIBRARY = dummy.a

include $(TOPDIR)/Makerules



all: subdirs

depend: depend-subdirs

clean: clean-subdirs

install: install-subdirs

