/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// ---------------------------------------
// MLXHelp_base.C
// This file was automaticly generated by
// View Designer/X                     
//
// Don't edit this file, please !
// ---------------------------------------


// Include class definition

#include "MLXHelp_base.h"

// Include X11 header
#include <X11/xpm.h>

// Include OSF/Motif header files
#include <Xm/Frame.h>
#include <X11/Shell.h>
#include <Xm/Form.h>
#include <Xm/SelectioB.h>
#include <Xm/RowColumn.h>
#include <Xm/ToggleB.h>
#include <Xm/CascadeB.h>
#include <Xm/PushB.h>
#include <Xm/ArrowB.h>
#include <Xm/PanedW.h>
#include <Xm/Frame.h>
#include <Xm/ScrolledW.h>
#include <Xm/Text.h>
#include <Xm/Label.h>
#include <Xm/FileSB.h>








#define RES_CONVERT(t,s) cvtResourceFromString(parent, t, s)


// -----------------------------------
// MLXHelp_base(parent,args,n)
// -----------------------------------

MLXHelp_base::MLXHelp_base(Widget p, ArgList f_args, Cardinal f_n, char *fbRes)
{
  Widget parent;
  Arg args[100];
  Cardinal n = 0;

  if(p) 
    parent = p;
  else
    parent = getTopLevel();

  if(fbRes) {
    XrmDatabase database, fallback;
    
    fallback = XrmGetStringDatabase(fbRes);
    database = XrmGetDatabase(XtDisplay(parent));
    
    XrmCombineDatabase(fallback, &database, FALSE);
  }

  if(!XtIsShell(parent)) {
    MLXHelp = XtCreateWidget("MLXHelp",xmFrameWidgetClass,
				       parent,f_args,f_n);
  } else { 
   
    popupShell = MLXHelp = XtCreatePopupShell("MLXHelp", topLevelShellWidgetClass,
			parent, args, n);
  }
  createWidgets();
  addCallbacks();
  addRelations();
}


// ----------------------------
// createWidgets()
// ----------------------------

void MLXHelp_base::createWidgets()
{
  Widget parent;           // the parent for every widget
  Arg args[100];           // resource list
  Cardinal n;              // number of resources

  // Now we create every Widget

  
  /* ---------- Creating Widget:    form -------------- */
  parent = MLXHelp;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 345); n++;
  XtSetArg(args[n], "width", 585); n++;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  form = XtCreateWidget("form", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(form);
  
  addQuickHelp(form);
  addHelpId(form,-1);

  
  /* ---------- Creating Widget:    titleDialog -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 150); n++;
  XtSetArg(args[n], "y", 340); n++;
  XtSetArg(args[n], "dialogStyle", XmDIALOG_FULL_APPLICATION_MODAL); n++;


  /* Creating Widget */
  titleDialog = XmCreatePromptDialog( parent, "titleDialog", args, n);
  
  addQuickHelp(titleDialog);
  addHelpId(titleDialog,-1);

  
  /* ---------- Creating Widget:    identDialog -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 150); n++;
  XtSetArg(args[n], "y", 340); n++;
  XtSetArg(args[n], "dialogStyle", XmDIALOG_FULL_APPLICATION_MODAL); n++;
  XtSetArg(args[n], "dialogTitle", RES_CONVERT("XmString", "Change Identifier")); n++;
  XtSetArg(args[n], "selectionLabelString", RES_CONVERT("XmString", "Identifier:")); n++;


  /* Creating Widget */
  identDialog = XmCreatePromptDialog( parent, "identDialog", args, n);
  
  addQuickHelp(identDialog);
  addHelpId(identDialog,-1);

  
  /* ---------- Creating Widget:    findDialog -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 230); n++;
  XtSetArg(args[n], "y", 60); n++;
  XtSetArg(args[n], "autoUnmanage", 0); n++;
  XtSetArg(args[n], "childPlacement", XmPLACE_BELOW_SELECTION); n++;


  /* Creating Widget */
  findDialog = XmCreatePromptDialog( parent, "findDialog", args, n);
  
  addQuickHelp(findDialog);
  addHelpId(findDialog,-1);

  
  /* ---------- Creating Widget:    rowColumn_1 -------------- */
  parent = findDialog;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 100); n++;
  XtSetArg(args[n], "width", 100); n++;
  XtSetArg(args[n], "x", 110); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  rowColumn_1 = XtCreateWidget("rowColumn_1", xmRowColumnWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(rowColumn_1);
  
  addQuickHelp(rowColumn_1);
  addHelpId(rowColumn_1,-1);

  
  /* ---------- Creating Widget:    findBeginToggle -------------- */
  parent = rowColumn_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 20); n++;
  XtSetArg(args[n], "y", 60); n++;


  /* Creating Widget */
  findBeginToggle = XtCreateWidget("findBeginToggle", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(findBeginToggle);
  
  addQuickHelp(findBeginToggle);
  addHelpId(findBeginToggle,-1);

  
  /* ---------- Creating Widget:    findCaseToggle -------------- */
  parent = rowColumn_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 10); n++;
  XtSetArg(args[n], "y", 60); n++;


  /* Creating Widget */
  findCaseToggle = XtCreateWidget("findCaseToggle", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(findCaseToggle);
  
  addQuickHelp(findCaseToggle);
  addHelpId(findCaseToggle,-1);

  
  /* ---------- Creating Widget:    menuBar_1 -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 32); n++;
  XtSetArg(args[n], "width", 583); n++;
  XtSetArg(args[n], "x", 550); n++;
  XtSetArg(args[n], "y", 230); n++;
  XtSetArg(args[n], "leftAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;
  XtSetArg(args[n], "topAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "topOffset", 1); n++;


  /* Creating Widget */
  menuBar_1 = XmCreateMenuBar( parent, "menuBar_1", args, n);
  
  /* Manage the Widget */
  XtManageChild(menuBar_1);
  
  addQuickHelp(menuBar_1);
  addHelpId(menuBar_1,-1);

  
  /* ---------- Creating Widget:    File -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  File = XtCreateWidget("File", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(File);
  
  addQuickHelp(File);
  addHelpId(File,-1);

  
  /* ---------- Creating Widget:    FileMenu -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  FileMenu = XmCreatePulldownMenu( parent, "FileMenu", args, n);
  
  addQuickHelp(FileMenu);
  addHelpId(FileMenu,-1);

  
  /* ---------- Creating Widget:    Save -------------- */
  parent = FileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  Save = XtCreateWidget("Save", xmPushButtonWidgetClass,
			parent, args, n);
  
  addQuickHelp(Save);
  addHelpId(Save,-1);

  
  /* ---------- Creating Widget:    exportLatex -------------- */
  parent = FileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  exportLatex = XtCreateWidget("exportLatex", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(exportLatex);
  
  addQuickHelp(exportLatex);
  addHelpId(exportLatex,-1);

  
  /* ---------- Creating Widget:    Exit -------------- */
  parent = FileMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  Exit = XtCreateWidget("Exit", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(Exit);
  
  addQuickHelp(Exit);
  addHelpId(Exit,-1);

  
  /* ---------- Creating Widget:    Edit -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  Edit = XtCreateWidget("Edit", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  addQuickHelp(Edit);
  addHelpId(Edit,-1);

  
  /* ---------- Creating Widget:    EditMenu -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  EditMenu = XmCreatePulldownMenu( parent, "EditMenu", args, n);
  
  addQuickHelp(EditMenu);
  addHelpId(EditMenu,-1);

  
  /* ---------- Creating Widget:    View -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  View = XtCreateWidget("View", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(View);
  
  addQuickHelp(View);
  addHelpId(View,-1);

  
  /* ---------- Creating Widget:    ViewMenu -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  ViewMenu = XmCreatePulldownMenu( parent, "ViewMenu", args, n);
  
  addQuickHelp(ViewMenu);
  addHelpId(ViewMenu,-1);

  
  /* ---------- Creating Widget:    contentsButton -------------- */
  parent = ViewMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  contentsButton = XtCreateWidget("contentsButton", xmToggleButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(contentsButton);
  
  addQuickHelp(contentsButton);
  addHelpId(contentsButton,-1);

  
  /* ---------- Creating Widget:    Navigate -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  Navigate = XtCreateWidget("Navigate", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(Navigate);
  
  addQuickHelp(Navigate);
  addHelpId(Navigate,-1);

  
  /* ---------- Creating Widget:    NavigateMenu -------------- */
  parent = menuBar_1;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  NavigateMenu = XmCreatePulldownMenu( parent, "NavigateMenu", args, n);
  
  addQuickHelp(NavigateMenu);
  addHelpId(NavigateMenu,-1);

  
  /* ---------- Creating Widget:    findButton -------------- */
  parent = NavigateMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "mnemonic", RES_CONVERT("KeySym", "d")); n++;


  /* Creating Widget */
  findButton = XtCreateWidget("findButton", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(findButton);
  
  addQuickHelp(findButton);
  addHelpId(findButton,-1);

  
  /* ---------- Creating Widget:    historyBack -------------- */
  parent = NavigateMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  historyBack = XtCreateWidget("historyBack", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(historyBack);
  
  addQuickHelp(historyBack);
  addHelpId(historyBack,-1);

  
  /* ---------- Creating Widget:    historyForward -------------- */
  parent = NavigateMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  historyForward = XtCreateWidget("historyForward", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(historyForward);
  
  addQuickHelp(historyForward);
  addHelpId(historyForward,-1);

  
  /* ---------- Creating Widget:    lastSection -------------- */
  parent = NavigateMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  lastSection = XtCreateWidget("lastSection", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(lastSection);
  
  addQuickHelp(lastSection);
  addHelpId(lastSection,-1);

  
  /* ---------- Creating Widget:    nextSection -------------- */
  parent = NavigateMenu;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  nextSection = XtCreateWidget("nextSection", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(nextSection);
  
  addQuickHelp(nextSection);
  addHelpId(nextSection,-1);

  
  /* ---------- Creating Widget:    backButton -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 30); n++;
  XtSetArg(args[n], "width", 30); n++;
  XtSetArg(args[n], "x", 5); n++;
  XtSetArg(args[n], "y", 40); n++;
  XtSetArg(args[n], "arrowDirection", XmARROW_LEFT); n++;
  XtSetArg(args[n], "bottomAttachment", XmATTACH_NONE); n++;
  XtSetArg(args[n], "leftAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "leftOffset", 5); n++;
  XtSetArg(args[n], "topAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "topOffset", 5); n++;


  /* Creating Widget */
  backButton = XtCreateWidget("backButton", xmArrowButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(backButton);
  
  addQuickHelp(backButton);
  addHelpId(backButton,-1);

  
  /* ---------- Creating Widget:    panedWindow -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "orientation", XmHORIZONTAL); n++;
  XtSetArg(args[n], "bottomAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "bottomOffset", 1); n++;
  XtSetArg(args[n], "leftAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;
  XtSetArg(args[n], "topAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "topOffset", 5); n++;


  /* Creating Widget */
  panedWindow = XtCreateWidget("panedWindow", xmPanedWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(panedWindow);
  
  addQuickHelp(panedWindow);
  addHelpId(panedWindow,-1);

  
  /* ---------- Creating Widget:    frame -------------- */
  parent = panedWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 244); n++;
  XtSetArg(args[n], "width", 200); n++;
  XtSetArg(args[n], "x", 3); n++;
  XtSetArg(args[n], "y", 3); n++;


  /* Creating Widget */
  frame = XtCreateWidget("frame", xmFrameWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(frame);
  
  addQuickHelp(frame);
  addHelpId(frame,-1);

  
  /* ---------- Creating Widget:    scrolledWindow -------------- */
  parent = panedWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 90); n++;
  XtSetArg(args[n], "y", 130); n++;


  /* Creating Widget */
  scrolledWindow = XtCreateWidget("scrolledWindow", xmScrolledWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(scrolledWindow);
  
  addQuickHelp(scrolledWindow);
  addHelpId(scrolledWindow,-1);

  
  /* ---------- Creating Widget:    text -------------- */
  parent = scrolledWindow;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 50); n++;
  XtSetArg(args[n], "y", 30); n++;
  XtSetArg(args[n], "editMode", XmMULTI_LINE_EDIT); n++;
  XtSetArg(args[n], "scrollHorizontal", 0); n++;
  XtSetArg(args[n], "wordWrap", 1); n++;


  /* Creating Widget */
  text = XtCreateWidget("text", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(text);
  
  addQuickHelp(text);
  addHelpId(text,-1);

  
  /* ---------- Creating Widget:    forwardButton -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 30); n++;
  XtSetArg(args[n], "width", 30); n++;
  XtSetArg(args[n], "x", 40); n++;
  XtSetArg(args[n], "y", 40); n++;
  XtSetArg(args[n], "arrowDirection", XmARROW_RIGHT); n++;
  XtSetArg(args[n], "leftAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "leftOffset", 5); n++;
  XtSetArg(args[n], "topAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "topOffset", 5); n++;


  /* Creating Widget */
  forwardButton = XtCreateWidget("forwardButton", xmArrowButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(forwardButton);
  
  addQuickHelp(forwardButton);
  addHelpId(forwardButton,-1);

  
  /* ---------- Creating Widget:    titleLabel -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 30); n++;
  XtSetArg(args[n], "x", 117); n++;
  XtSetArg(args[n], "y", 40); n++;
  XtSetArg(args[n], "alignment", XmALIGNMENT_END); n++;
  XtSetArg(args[n], "leftAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "leftOffset", 10); n++;
  XtSetArg(args[n], "topAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "topOffset", 5); n++;


  /* Creating Widget */
  titleLabel = XtCreateWidget("titleLabel", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(titleLabel);
  
  addQuickHelp(titleLabel);
  addHelpId(titleLabel,-1);

  
  /* ---------- Creating Widget:    titleText -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "width", 469); n++;
  XtSetArg(args[n], "x", 121); n++;
  XtSetArg(args[n], "y", 34); n++;
  XtSetArg(args[n], "autoShowCursorPosition", 0); n++;
  XtSetArg(args[n], "cursorPositionVisible", 0); n++;
  XtSetArg(args[n], "editable", 0); n++;
  XtSetArg(args[n], "leftAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "rightOffset", 5); n++;
  XtSetArg(args[n], "topAttachment", XmATTACH_WIDGET); n++;
  XtSetArg(args[n], "topOffset", 2); n++;


  /* Creating Widget */
  titleText = XtCreateWidget("titleText", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(titleText);
  
  addQuickHelp(titleText);
  addHelpId(titleText,-1);

  
  /* ---------- Creating Widget:    quickHelp -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 20); n++;
  XtSetArg(args[n], "width", 583); n++;
  XtSetArg(args[n], "x", 20); n++;
  XtSetArg(args[n], "y", 310); n++;
  XtSetArg(args[n], "alignment", XmALIGNMENT_BEGINNING); n++;
  XtSetArg(args[n], "bottomAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "bottomOffset", 1); n++;
  XtSetArg(args[n], "leftAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "leftOffset", 1); n++;
  XtSetArg(args[n], "rightAttachment", XmATTACH_FORM); n++;
  XtSetArg(args[n], "rightOffset", 1); n++;


  /* Creating Widget */
  quickHelp = XtCreateWidget("quickHelp", xmLabelWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(quickHelp);
  
  addQuickHelp(quickHelp);
  addHelpId(quickHelp,-1);

  
  /* ---------- Creating Widget:    exportDialog -------------- */
  parent = form;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 100); n++;
  XtSetArg(args[n], "y", 50); n++;
  XtSetArg(args[n], "autoUnmanage", 1); n++;


  /* Creating Widget */
  exportDialog = XmCreateFileSelectionDialog( parent, "exportDialog", args, n);
  
  addQuickHelp(exportDialog);
  addHelpId(exportDialog,-1);

  
  /* ---------- Creating Widget:    exportType -------------- */
  parent = exportDialog;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 70); n++;
  XtSetArg(args[n], "y", 240); n++;


  /* Creating Widget */
  exportType = XmCreateOptionMenu( parent, "exportType", args, n);
  
  /* Manage the Widget */
  XtManageChild(exportType);
  
  addQuickHelp(exportType);
  addHelpId(exportType,-1);

  
  /* ---------- Creating Widget:    exportPulldown -------------- */
  parent = exportDialog;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 90); n++;
  XtSetArg(args[n], "y", 10); n++;


  /* Creating Widget */
  exportPulldown = XmCreatePulldownMenu( parent, "exportPulldown", args, n);
  
  addQuickHelp(exportPulldown);
  addHelpId(exportPulldown,-1);

  
  /* ---------- Creating Widget:    plainText -------------- */
  parent = exportPulldown;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  plainText = XtCreateWidget("plainText", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(plainText);
  
  addQuickHelp(plainText);
  addHelpId(plainText,-1);

  
  /* ---------- Creating Widget:    latexFormat -------------- */
  parent = exportPulldown;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  latexFormat = XtCreateWidget("latexFormat", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(latexFormat);
  
  addQuickHelp(latexFormat);
  addHelpId(latexFormat,-1);

  
  /* ---------- Creating Widget:    htmlText -------------- */
  parent = exportPulldown;

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  htmlText = XtCreateWidget("htmlText", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(htmlText);
  
  addQuickHelp(htmlText);
  addHelpId(htmlText,-1);


}



// ----------------------------
// addCallbacks()
// ----------------------------

void MLXHelp_base::addCallbacks()
{

  XtAddCallback( titleDialog, "mapCallback",
                 titleDialogMap_CB, this);

  XtAddCallback( titleDialog, "okCallback",
                 titleChanged_CB, this);

  XtAddCallback( identDialog, "mapCallback",
                 identDialogMap_CB, this);

  XtAddCallback( identDialog, "okCallback",
                 identChanged_CB, this);

  XtAddCallback( findDialog, "cancelCallback",
                 cancelFindDialog_CB, this);

  XtAddCallback( findDialog, "mapCallback",
                 mapFindDialog_CB, this);

  XtAddCallback( findDialog, "okCallback",
                 okFindDialog_CB, this);

  XtAddCallback( Save, "activateCallback",
                 saveFile_CB, this);

  XtAddCallback( exportLatex, "activateCallback",
                 manageWidget, (XtPointer)exportDialog); 

  XtAddCallback( Exit, "activateCallback",
                 exitMLXHelp_CB, this);

  XtAddCallback( contentsButton, "valueChangedCallback",
                 contentsButtonChanged_CB, this);

  XtAddCallback( findButton, "activateCallback",
                 manageWidget, (XtPointer)findDialog); 

  XtAddCallback( historyBack, "activateCallback",
                 do_backward_CB, this);

  XtAddCallback( historyForward, "activateCallback",
                 do_forward_CB, this);

  XtAddCallback( lastSection, "activateCallback",
                 do_lastSection_CB, this);

  XtAddCallback( nextSection, "activateCallback",
                 do_nextSection_CB, this);

  XtAddCallback( backButton, "activateCallback",
                 do_backward_CB, this);

  XtAddCallback( text, "modifyVerifyCallback",
                 textValueChanged_CB, this);

  XtAddCallback( forwardButton, "activateCallback",
                 do_forward_CB, this);

  XtAddCallback( exportDialog, "mapCallback",
                 mapExportDialog_CB, this);

  XtAddCallback( exportDialog, "okCallback",
                 do_export_CB, this);

  XtAddCallback( exportPulldown, "entryCallback",
                 exportTypeChanged_CB, this);

}



// ----------------------------
// addRelations()
// ----------------------------

void MLXHelp_base::addRelations()
{
  XtVaSetValues(File, "subMenuId", FileMenu, NULL);

  XtVaSetValues(Edit, "subMenuId", EditMenu, NULL);

  XtVaSetValues(View, "subMenuId", ViewMenu, NULL);

  XtVaSetValues(Navigate, "subMenuId", NavigateMenu, NULL);

  XtVaSetValues(backButton, "topWidget", menuBar_1, NULL);

  XtVaSetValues(panedWindow, "bottomWidget", quickHelp, NULL);

  XtVaSetValues(panedWindow, "topWidget", backButton, NULL);

  XtVaSetValues(forwardButton, "leftWidget", backButton, NULL);

  XtVaSetValues(forwardButton, "topWidget", menuBar_1, NULL);

  XtVaSetValues(titleLabel, "leftWidget", forwardButton, NULL);

  XtVaSetValues(titleLabel, "topWidget", menuBar_1, NULL);

  XtVaSetValues(titleText, "leftWidget", titleLabel, NULL);

  XtVaSetValues(titleText, "topWidget", menuBar_1, NULL);

  XtVaSetValues(exportType, "subMenuId", exportPulldown, NULL);


}


// ----------------------------
// manageWidget()
// ----------------------------
void MLXHelp_base::manageWidget(Widget, XtPointer c, XtPointer)
{
  XtManageChild((Widget)c);
}


// ----------------------------
// createPixmapFromData()
// ----------------------------

Pixmap MLXHelp_base::createPixmapFromData(char **data)
{
  Pixmap pix, mask;
  XpmAttributes attr;

  memset(&attr, 0, sizeof(attr));
  attr.valuemask = XpmReturnPixels;

  if( !XpmCreatePixmapFromData(XtDisplay(LicView::getTopLevel()),
		               XRootWindowOfScreen(XtScreen(LicView::getTopLevel())),
			       data,
			       &pix, &mask, &attr) )
    return pix;
  return XmUNSPECIFIED_PIXMAP;
}

// ------------------------------------------
// createPixmapFromFile()
//
// Creating a pixmap by XpmRaedFileToPixmap()
// Uses XFILESEARCHPATH to find the pixmap
// default path: /usr/lib/X11/pixmaps/%N.xpm
// ------------------------------------------

Pixmap MLXHelp_base::createPixmapFromFile(char *name)
{
  String string;
  Pixmap pix, mask;
  XpmAttributes attr;

  string = XtResolvePathname(XtDisplay(LicView::getTopLevel()),
			     "pixmaps", name, "", NULL,
			     NULL, 0, NULL);
  if(string) {
    memset(&attr, 0, sizeof(attr));
    attr.valuemask = XpmReturnPixels;
    if( !XpmReadFileToPixmap(XtDisplay(LicView::getTopLevel()),
			     XRootWindowOfScreen(
			     XtScreen(LicView::getTopLevel())),
			     string,
			     &pix, &mask, &attr) )
      return pix;
    return XmUNSPECIFIED_PIXMAP;
    XtFree(string);
  }
  return XmUNSPECIFIED_PIXMAP;
}

// ---------------------------------------------------------
// Following class method are used as a callback.
// The method is calling a abstract virtual method, which
// must be overloaded in the derived class 'MLXHelp'
// ---------------------------------------------------------

void MLXHelp_base::titleDialogMap_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->titleDialogMap(wg,callData);
}

void MLXHelp_base::titleChanged_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->titleChanged(wg,callData);
}

void MLXHelp_base::identDialogMap_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->identDialogMap(wg,callData);
}

void MLXHelp_base::identChanged_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->identChanged(wg,callData);
}

void MLXHelp_base::cancelFindDialog_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->cancelFindDialog(wg,callData);
}

void MLXHelp_base::mapFindDialog_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->mapFindDialog(wg,callData);
}

void MLXHelp_base::okFindDialog_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->okFindDialog(wg,callData);
}

void MLXHelp_base::saveFile_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->saveFile(wg,callData);
}

void MLXHelp_base::exitMLXHelp_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->exitMLXHelp(wg,callData);
}

void MLXHelp_base::contentsButtonChanged_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->contentsButtonChanged(wg,callData);
}

void MLXHelp_base::do_backward_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->do_backward(wg,callData);
}

void MLXHelp_base::do_forward_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->do_forward(wg,callData);
}

void MLXHelp_base::do_lastSection_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->do_lastSection(wg,callData);
}

void MLXHelp_base::do_nextSection_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->do_nextSection(wg,callData);
}

void MLXHelp_base::textValueChanged_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->textValueChanged(wg,callData);
}

void MLXHelp_base::mapExportDialog_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->mapExportDialog(wg,callData);
}

void MLXHelp_base::do_export_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->do_export(wg,callData);
}

void MLXHelp_base::exportTypeChanged_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((MLXHelp_base*)clientData)->exportTypeChanged(wg,callData);
}


