"*MLXHelp.defaultFontList: -adobe-helvetica-medium-r-*-*-12-*-*-*-*-*-iso8859-1\n"
"*MLXHelp.title: Help System\n"
"*MLXHelp*titleDialog.dialogTitle: Change Section Title\n"
"*MLXHelp*titleDialog.selectionLabelString: Title:\n"
"*MLXHelp*findDialog.cancelLabelString: Close\n"
"*MLXHelp*findDialog.dialogTitle: Find Dialog\n"
"*MLXHelp*findDialog.okLabelString: Find\n"
"*MLXHelp*findDialog.selectionLabelString: Search for:\n"
"*MLXHelp*findBeginToggle.labelString: Search from the beginning\n"
"*MLXHelp*findCaseToggle.labelString: Case sensitive\n"
"*MLXHelp*File.labelString: File\n"
"*MLXHelp*File.mnemonic: F\n"
"*MLXHelp*Save.accelerator: Ctrl<Key>s\n"
"*MLXHelp*Save.acceleratorText: ^S\n"
"*MLXHelp*Save.labelString: Save\n"
"*MLXHelp*Save.mnemonic: S\n"
"*MLXHelp*Save.quickHelpLabel: Save help file.\n"
"*MLXHelp*exportLatex.accelerator: Ctrl<Key>e\n"
"*MLXHelp*exportLatex.acceleratorText: ^e\n"
"*MLXHelp*exportLatex.labelString: Export ...\n"
"*MLXHelp*exportLatex.mnemonic: E\n"
"*MLXHelp*exportLatex.quickHelpLabel: Export whole help document to a file.\n"
"*MLXHelp*Exit.accelerator: <Key>Escape\n"
"*MLXHelp*Exit.acceleratorText: Esc\n"
"*MLXHelp*Exit.labelString: Close\n"
"*MLXHelp*Exit.mnemonic: C\n"
"*MLXHelp*Exit.quickHelpLabel: Hide the help view.\n"
"*MLXHelp*Edit.labelString: Edit\n"
"*MLXHelp*Edit.mnemonic: E\n"
"*MLXHelp*View.labelString: View\n"
"*MLXHelp*View.mnemonic: V\n"
"*MLXHelp*contentsButton.accelerator: Ctrl<Key>c\n"
"*MLXHelp*contentsButton.acceleratorText: ^C\n"
"*MLXHelp*contentsButton.labelString: Contents\n"
"*MLXHelp*contentsButton.mnemonic: C\n"
"*MLXHelp*contentsButton.quickHelpLabel: Show or hide the contents tree view.\n"
"*MLXHelp*Navigate.labelString: Navigate\n"
"*MLXHelp*Navigate.mnemonic: N\n"
"*MLXHelp*findButton.accelerator: Ctrl<Key>f\n"
"*MLXHelp*findButton.acceleratorText: ^F\n"
"*MLXHelp*findButton.labelString: Find ...\n"
"*MLXHelp*findButton.quickHelpLabel: Find a specific string in the help document.\n"
"*MLXHelp*historyBack.accelerator: Ctrl<Key>Left\n"
"*MLXHelp*historyBack.acceleratorText: ^Left\n"
"*MLXHelp*historyBack.labelString: History Backward\n"
"*MLXHelp*historyBack.mnemonic: B\n"
"*MLXHelp*historyBack.quickHelpLabel: Back to the last section in the history.\n"
"*MLXHelp*historyForward.accelerator: Ctrl<Key>Right\n"
"*MLXHelp*historyForward.acceleratorText: ^Right\n"
"*MLXHelp*historyForward.labelString: History Forward\n"
"*MLXHelp*historyForward.mnemonic: F\n"
"*MLXHelp*historyForward.quickHelpLabel: Forward in the history.\n"
"*MLXHelp*lastSection.accelerator: Ctrl<Key>Prior\n"
"*MLXHelp*lastSection.acceleratorText: ^Page up\n"
"*MLXHelp*lastSection.labelString: Last Section\n"
"*MLXHelp*lastSection.mnemonic: L\n"
"*MLXHelp*lastSection.quickHelpLabel: To the preceding section in the contents tree.\n"
"*MLXHelp*nextSection.accelerator: Ctrl<Key>Next\n"
"*MLXHelp*nextSection.acceleratorText: ^Page down\n"
"*MLXHelp*nextSection.labelString: Next Section\n"
"*MLXHelp*nextSection.mnemonic: N\n"
"*MLXHelp*nextSection.quickHelpLabel: To the next section in the contents tree.\n"
"*MLXHelp*backButton.quickHelpLabel: Back in the history.\n"
"*MLXHelp*frame.quickHelpLabel: The contents tree. Click the tree node.\n"
"*MLXHelp*text.fontList: -adobe-times-medium-r-normal--14-*-*-*-*-*-iso8859-1\n"
"*MLXHelp*text.quickHelpLabel: Help text of the selected section. Click the hypertext links.\n"
"*MLXHelp*forwardButton.quickHelpLabel: Forward in the history.\n"
"*MLXHelp*titleLabel.labelString: Title:\n"
"*MLXHelp*titleText.quickHelpLabel: The title of the selected section.\n"
"*MLXHelp*exportDialog.dialogTitle: Export\n"
"*MLXHelp*exportDialog.okLabelString: Export\n"
"*MLXHelp*exportType.labelString: Export Format:\n"
"*MLXHelp*plainText.labelString: Plain Text\n"
"*MLXHelp*latexFormat.labelString: Latex\n"
"*MLXHelp*htmlText.labelString: HTML\n"
