/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// ---------------------------------------
// ToolBoxSample_base.C
//
// This file was automaticly generated by
// View Designer/X v1.2
//
// User: lazy@apfel
// Date: Thu Apr 23 03:41:00 1998
// 
// Don't edit this file, please !
// ---------------------------------------


// Include class definition

#include "ToolBoxSample_base.h"

// Include X11 header
#include <X11/xpm.h>

// Include OSF/Motif header files
#include <Xm/Frame.h>
#include <X11/Shell.h>
#include <Xm/MainW.h>
#include <Xm/RowColumn.h>
#include <Xm/CascadeB.h>
#include <Xm/PushB.h>
#include <Xm/Form.h>
#include <Xfe/ToolBox.h>
#include <Xfe/ToolBar.h>
#include <Xfe/Button.h>
#include <Xm/Text.h>
#include <Xfe/ProgressBar.h>



#include "foo.xpm"





#define RES_CONVERT(t,s) cvtResourceFromString(parent, t, s)


// -----------------------------------
// ToolBoxSample_base(parent,args,n)
// -----------------------------------

ToolBoxSample_base::ToolBoxSample_base(Widget p, ArgList f_args, Cardinal f_n)
{
  Widget parent;
  Arg args[100];
  Cardinal n = 0;

  if(p) 
    parent = p;
  else
    parent = getTopLevel();

  if(p) {
    ToolBoxSample = XtCreateWidget("ToolBoxSample",xmFrameWidgetClass,
				       parent,f_args,f_n);
  } else { 
   
    popupShell = ToolBoxSample = XtCreatePopupShell("ToolBoxSample", topLevelShellWidgetClass,
			parent, args, n);
  }
  createWidgets();
  addCallbacks();
  addRelations();
}


// ----------------------------
// createWidgets()
// ----------------------------

void ToolBoxSample_base::createWidgets()
{
  Widget parent;           // the parent for every widget
  Arg args[100];           // resource list
  Cardinal n;              // number of resources

  // Now we create every Widget

  
  /* ---------- Creating Widget:    mainWindow_1 -------------- */
  parent = ToolBoxSample;

  /* Converters must be registered, so call XtInitializeWidgetClass() */
  if(xmMainWindowWidgetClass != NULL) {
    XtInitializeWidgetClass(xmMainWindowWidgetClass);
  }

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 220); n++;
  XtSetArg(args[n], "width", 420); n++;
  XtSetArg(args[n], "x", 450); n++;
  XtSetArg(args[n], "y", 300); n++;


  /* Creating Widget */
  mainWindow_1 = XtCreateWidget("mainWindow_1", xmMainWindowWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(mainWindow_1);
  
  


  
  /* ---------- Creating Widget:    menuBar_1 -------------- */
  parent = mainWindow_1;

  /* Converters must be registered, so call XtInitializeWidgetClass() */
  if(NULL != NULL) {
    XtInitializeWidgetClass(NULL);
  }

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 30); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  menuBar_1 = XmCreateMenuBar( parent, "menuBar_1", args, n);
  
  /* Manage the Widget */
  XtManageChild(menuBar_1);
  
  


  
  /* ---------- Creating Widget:    File -------------- */
  parent = menuBar_1;

  /* Converters must be registered, so call XtInitializeWidgetClass() */
  if(xmCascadeButtonWidgetClass != NULL) {
    XtInitializeWidgetClass(xmCascadeButtonWidgetClass);
  }

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  File = XtCreateWidget("File", xmCascadeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(File);
  
  


  
  /* ---------- Creating Widget:    pulldownMenu -------------- */
  parent = menuBar_1;

  /* Converters must be registered, so call XtInitializeWidgetClass() */
  if(NULL != NULL) {
    XtInitializeWidgetClass(NULL);
  }

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  pulldownMenu = XmCreatePulldownMenu( parent, "pulldownMenu", args, n);
  
  


  
  /* ---------- Creating Widget:    Exit -------------- */
  parent = pulldownMenu;

  /* Converters must be registered, so call XtInitializeWidgetClass() */
  if(xmPushButtonWidgetClass != NULL) {
    XtInitializeWidgetClass(xmPushButtonWidgetClass);
  }

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;


  /* Creating Widget */
  Exit = XtCreateWidget("Exit", xmPushButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(Exit);
  
  


  
  /* ---------- Creating Widget:    form -------------- */
  parent = mainWindow_1;

  /* Converters must be registered, so call XtInitializeWidgetClass() */
  if(xmFormWidgetClass != NULL) {
    XtInitializeWidgetClass(xmFormWidgetClass);
  }

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 100); n++;
  XtSetArg(args[n], "width", 180); n++;
  XtSetArg(args[n], "x", 150); n++;
  XtSetArg(args[n], "y", 50); n++;


  /* Creating Widget */
  form = XtCreateWidget("form", xmFormWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(form);
  
  


  
  /* ---------- Creating Widget:    toolBox -------------- */
  parent = form;

  /* Converters must be registered, so call XtInitializeWidgetClass() */
  if(xfeToolBoxWidgetClass != NULL) {
    XtInitializeWidgetClass(xfeToolBoxWidgetClass);
  }

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "usePreferredHeight", 1); n++;
  XtSetArg(args[n], "usePreferredWidth", 0); n++;
  XtSetArg(args[n], "bottomAttachment", 0); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 0); n++;
  XtSetArg(args[n], "resizable", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 0); n++;
  XtSetArg(args[n], "topAttachment", 1); n++;
  XtSetArg(args[n], "topOffset", 0); n++;


  /* Creating Widget */
  toolBox = XtCreateWidget("toolBox", xfeToolBoxWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(toolBox);
  
  


  
  /* ---------- Creating Widget:    xfeToolBar -------------- */
  parent = toolBox;

  /* Converters must be registered, so call XtInitializeWidgetClass() */
  if(xfeToolBarWidgetClass != NULL) {
    XtInitializeWidgetClass(xfeToolBarWidgetClass);
  }

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "buttonLayout", 3); n++;


  /* Creating Widget */
  xfeToolBar = XtCreateWidget("xfeToolBar", xfeToolBarWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(xfeToolBar);
  
  


  
  /* ---------- Creating Widget:    xfeButton -------------- */
  parent = xfeToolBar;

  /* Converters must be registered, so call XtInitializeWidgetClass() */
  if(xfeButtonWidgetClass != NULL) {
    XtInitializeWidgetClass(xfeButtonWidgetClass);
  }

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "pixmap", createPixmapFromData(foo_xpm)); n++;


  /* Creating Widget */
  xfeButton = XtCreateWidget("xfeButton", xfeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(xfeButton);
  
  


  
  /* ---------- Creating Widget:    xfeButton_3 -------------- */
  parent = xfeToolBar;

  /* Converters must be registered, so call XtInitializeWidgetClass() */
  if(xfeButtonWidgetClass != NULL) {
    XtInitializeWidgetClass(xfeButtonWidgetClass);
  }

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "pixmap", createPixmapFromData(foo_xpm)); n++;


  /* Creating Widget */
  xfeButton_3 = XtCreateWidget("xfeButton_3", xfeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(xfeButton_3);
  
  


  
  /* ---------- Creating Widget:    xfeToolBar_1 -------------- */
  parent = toolBox;

  /* Converters must be registered, so call XtInitializeWidgetClass() */
  if(xfeToolBarWidgetClass != NULL) {
    XtInitializeWidgetClass(xfeToolBarWidgetClass);
  }

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "buttonLayout", 1); n++;
  XtSetArg(args[n], "radioBehavior", 1); n++;


  /* Creating Widget */
  xfeToolBar_1 = XtCreateWidget("xfeToolBar_1", xfeToolBarWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(xfeToolBar_1);
  
  


  
  /* ---------- Creating Widget:    xfeButton_3_1 -------------- */
  parent = xfeToolBar_1;

  /* Converters must be registered, so call XtInitializeWidgetClass() */
  if(xfeButtonWidgetClass != NULL) {
    XtInitializeWidgetClass(xfeButtonWidgetClass);
  }

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "armed", 1); n++;
  XtSetArg(args[n], "pixmap", createPixmapFromData(foo_xpm)); n++;


  /* Creating Widget */
  xfeButton_3_1 = XtCreateWidget("xfeButton_3_1", xfeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(xfeButton_3_1);
  
  


  
  /* ---------- Creating Widget:    xfeButton_3_2 -------------- */
  parent = xfeToolBar_1;

  /* Converters must be registered, so call XtInitializeWidgetClass() */
  if(xfeButtonWidgetClass != NULL) {
    XtInitializeWidgetClass(xfeButtonWidgetClass);
  }

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "pixmap", createPixmapFromData(foo_xpm)); n++;


  /* Creating Widget */
  xfeButton_3_2 = XtCreateWidget("xfeButton_3_2", xfeButtonWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(xfeButton_3_2);
  
  


  
  /* ---------- Creating Widget:    text -------------- */
  parent = form;

  /* Converters must be registered, so call XtInitializeWidgetClass() */
  if(xmTextWidgetClass != NULL) {
    XtInitializeWidgetClass(xmTextWidgetClass);
  }

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "x", 0); n++;
  XtSetArg(args[n], "y", 0); n++;
  XtSetArg(args[n], "bottomAttachment", 3); n++;
  XtSetArg(args[n], "bottomOffset", 0); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 0); n++;
  XtSetArg(args[n], "resizable", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 0); n++;
  XtSetArg(args[n], "topAttachment", 3); n++;
  XtSetArg(args[n], "topOffset", 0); n++;


  /* Creating Widget */
  text = XtCreateWidget("text", xmTextWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(text);
  
  


  
  /* ---------- Creating Widget:    progress -------------- */
  parent = form;

  /* Converters must be registered, so call XtInitializeWidgetClass() */
  if(xfeProgressBarWidgetClass != NULL) {
    XtInitializeWidgetClass(xfeProgressBarWidgetClass);
  }

  /* Building resource list */
  n = 0;
  XtSetArg(args[n], "height", 15); n++;
  XtSetArg(args[n], "barColor", RES_CONVERT("Pixel", "CornflowerBlue")); n++;
  XtSetArg(args[n], "shadowType", 8); n++;
  XtSetArg(args[n], "usePreferredHeight", 0); n++;
  XtSetArg(args[n], "usePreferredWidth", 0); n++;
  XtSetArg(args[n], "bottomAttachment", 1); n++;
  XtSetArg(args[n], "bottomOffset", 0); n++;
  XtSetArg(args[n], "leftAttachment", 1); n++;
  XtSetArg(args[n], "leftOffset", 0); n++;
  XtSetArg(args[n], "resizable", 1); n++;
  XtSetArg(args[n], "rightAttachment", 1); n++;
  XtSetArg(args[n], "rightOffset", 0); n++;
  XtSetArg(args[n], "topAttachment", 0); n++;


  /* Creating Widget */
  progress = XtCreateWidget("progress", xfeProgressBarWidgetClass,
			parent, args, n);
  
  /* Manage the Widget */
  XtManageChild(progress);
  
  



}



// ----------------------------
// addCallbacks()
// ----------------------------

void ToolBoxSample_base::addCallbacks()
{

  XtAddCallback( Exit, "activateCallback",
                 do_exit_CB, this);

  XtAddCallback( xfeButton, "activateCallback",
                 run_CB, this);

  XtAddCallback( xfeButton_3, "activateCallback",
                 stop_CB, this);

  XtAddCallback( xfeButton_3_1, "activateCallback",
                 lowSpeed_CB, this);

  XtAddCallback( xfeButton_3_2, "activateCallback",
                 highSpeed_CB, this);

}



// ----------------------------
// addRelations()
// ----------------------------

void ToolBoxSample_base::addRelations()
{
  XtVaSetValues(File, "subMenuId", pulldownMenu, NULL);

  XtVaSetValues(text, "bottomWidget", progress, NULL);

  XtVaSetValues(text, "topWidget", toolBox, NULL);


}


// ----------------------------
// manageWidget()
// ----------------------------
void ToolBoxSample_base::manageWidget(Widget, XtPointer c, XtPointer)
{
  XtManageChild((Widget)c);
}


// ----------------------------
// createPixmapFromData()
// ----------------------------

Pixmap ToolBoxSample_base::createPixmapFromData(char **data)
{
  Pixmap pix, mask;
  XpmAttributes attr;

  memset(&attr, 0, sizeof(attr));
  attr.valuemask = XpmReturnPixels;

  if( !XpmCreatePixmapFromData(XtDisplay(VcView::getTopLevel()),
		               XRootWindowOfScreen(XtScreen(VcView::getTopLevel())),
			       data,
			       &pix, &mask, &attr) )
    return pix;
  return XmUNSPECIFIED_PIXMAP;
}

// ------------------------------------------
// createPixmapFromFile()
//
// Creating a pixmap by XpmReadFileToPixmap()
// Uses XFILESEARCHPATH to find the pixmap
// default path: /usr/lib/X11/pixmaps/%N.xpm
// ------------------------------------------

Pixmap ToolBoxSample_base::createPixmapFromFile(char *name)
{
  String string;
  Pixmap pix, mask;
  XpmAttributes attr;

  string = XtResolvePathname(XtDisplay(VcView::getTopLevel()),
			     "pixmaps", name, "", NULL,
			     NULL, 0, NULL);
  if(string) {
    memset(&attr, 0, sizeof(attr));
    attr.valuemask = XpmReturnPixels;
    if( !XpmReadFileToPixmap(XtDisplay(VcView::getTopLevel()),
			     XRootWindowOfScreen(
			     XtScreen(VcView::getTopLevel())),
			     string,
			     &pix, &mask, &attr) )
      return pix;
    return XmUNSPECIFIED_PIXMAP;
    XtFree(string);
  }
  return XmUNSPECIFIED_PIXMAP;
}

// ---------------------------------------------------------
// Following class methods are used as a callback.
// The method is calling a abstract virtual method, which
// must be overloaded in the derived class 'ToolBoxSample'
// ---------------------------------------------------------

void ToolBoxSample_base::do_exit_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ToolBoxSample_base*)clientData)->do_exit(wg,callData);
}

void ToolBoxSample_base::run_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ToolBoxSample_base*)clientData)->run(wg,callData);
}

void ToolBoxSample_base::stop_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ToolBoxSample_base*)clientData)->stop(wg,callData);
}

void ToolBoxSample_base::lowSpeed_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ToolBoxSample_base*)clientData)->lowSpeed(wg,callData);
}

void ToolBoxSample_base::highSpeed_CB(Widget wg, XtPointer clientData, XtPointer callData)
{
   ((ToolBoxSample_base*)clientData)->highSpeed(wg,callData);
}


