/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// -------------------------------------------- 
// ToolBoxSample.C 
// Generated by View Designer/X v1.2
//
// User: lazy@apfel
// Date: Thu Apr 23 02:33:07 1998
// --------------------------------------------


#include "ToolBoxSample.h"
#include <stdio.h>

#include <Xfe/ProgressBar.h>
#include <Xfe/ToolBox.h>

// ------------------------------
// createToolBoxSample()
// ------------------------------

ToolBoxSample *createToolBoxSample(Widget parent, ArgList args, Cardinal n)
{
  return new ToolBoxSample(parent,args,n);
}


// ------------------------------
// ToolBoxSample()
// ------------------------------

ToolBoxSample::ToolBoxSample(Widget wg, ArgList args, Cardinal n)
:ToolBoxSample_base(wg,args,n) 
{
  // add your own code to initialize your data

  running = False;

  lowSpeed(NULL, NULL);

  XtAppAddTimeOut(XtWidgetToApplicationContext(getTopLevel()),  
		  speed,
		  timer, 
		  this);
}


// -------------------------
// do_exit()
// -------------------------

void ToolBoxSample::do_exit(Widget wg, XtPointer)
{
  exit(0);
}


// -------------------------
// lowSpeed()
// -------------------------

void ToolBoxSample::lowSpeed(Widget wg, XtPointer)
{
  speed = 100;
}

// -------------------------
// highSpeed()
// -------------------------

void ToolBoxSample::highSpeed(Widget wg, XtPointer)
{
  speed = 30;
}


// -------------------------
// run()
// -------------------------

void ToolBoxSample::run(Widget wg, XtPointer)
{
  XfeProgressBarCylonReset(progress);
  XfeProgressBarCylonStart(progress);
  running = True;
}


// -------------------------
// stop()
// -------------------------

void ToolBoxSample::stop(Widget wg, XtPointer)
{
  XfeProgressBarCylonStop(progress);
  running = False;
}



// -------------------------
// timer
// -------------------------

void ToolBoxSample::timer(XtPointer clientData, XtIntervalId *id)
{
  ::ToolBoxSample *self = (::ToolBoxSample*)clientData;

  if(self->running) {
    XfeProgressBarCylonTick(self->progress);
  }

  XtAppAddTimeOut(XtWidgetToApplicationContext(getTopLevel()),  
		  self->speed,
		  timer, 
		  clientData);
}





