/*
 * All files in this project are distributed under the GNU General
 * Public License. This is Free Software.
 */
// ----------------------------------------------
// This file was generated by View Designer/X
//
// Do not edit !
//
// ----------------------------------------------

#include "VcView.h"
#include <stdio.h>
#include <X11/Shell.h>
#include <X11/StringDefs.h>
#include <Xm/RowColumn.h>

XtAppContext VcView::context;
Widget VcView::firstTopLevel;


// -------------------------------
// VcView:   open()
// -------------------------------

void VcView::open()
{
  XtPopup(popupShell, XtGrabNone);
}


// -------------------------------
// VcView:   close()
// -------------------------------

void VcView::close()
{
  XtPopdown(popupShell);
}


// -------------------------------
// VcView:   init() - class method
// -------------------------------

Widget VcView::init( char *applClass, int &argc, char **argv, char *fbRes )
{
  Display *display;
  Widget topLevel;

  if( context == NULL ) {
    // initialize X-Toolkit
    XtToolkitInitialize();
    
    context = XtCreateApplicationContext();
    
  }

  display = XtOpenDisplay(context, 
			  NULL, NULL,
			  applClass, 
			  NULL, 0,
			  &argc, argv);
  if(display == NULL) {
    fprintf(stderr, "Can't open display.\n");
    exit(0);
  }

  if(fbRes) {
    XrmDatabase database, fallback;
    
    fallback = XrmGetStringDatabase(fbRes);
    database = XrmGetDatabase(display);
    
    XrmCombineDatabase(fallback, &database, FALSE);
  }
  
  topLevel = XtAppCreateShell(NULL, applClass, 
			      applicationShellWidgetClass,
			      display, NULL, 0);
  if(firstTopLevel == NULL)
    firstTopLevel = topLevel;

  return topLevel;
}


// -------------------------------
// VcView:   run() - class method
// -------------------------------

void VcView::run()
{
  XtAppMainLoop(context);
}

// -------------------------------
// Free allocated memory 
// -------------------------------

void VcView::freeMem(Widget wg, XtPointer client, XtPointer call)
{
  XtFree(client);
}


// -----------------------
// cvtResourceFromString()
// -----------------------

XtArgVal VcView::cvtResourceFromString(Widget wg, char *type, char *value)
{
  XtArgVal v;
  XrmValue from, to;

  from.addr = (caddr_t)value;
  from.size = strlen(value)+1;
  to.addr = (caddr_t)&v;
  to.size = sizeof(v);

  if( XtConvertAndStore(wg, XtRString, &from, type, &to) ) {
    return v;
  } else {
    from.addr = (caddr_t)value;
    from.size = strlen(value)+1;
    to.addr = (caddr_t)NULL;        /* Converter will allocate the storage */
    to.size = 0;

    if(XtConvertAndStore(wg, XtRString, &from, type, &to)) {
      caddr_t mem;
      mem = XtMalloc(to.size);      /* Copy private storage */
      memcpy(mem, to.addr, to.size);
      XtAddCallback(wg, XmNdestroyCallback, freeMem, mem);
      return (XtArgVal)mem;
    }
  }


  printf("Can't convert %s to %s.\n", value, type);
  return 0;
}


// ---------------------------------------
// popupMenuHandler()                     
// ---------------------------------------

void VcView::popupMenuHandler(Widget wg, XtPointer clientData, 
			      XEvent *event, Boolean *cont)
{
  XButtonEvent *button_event = (XButtonEvent*)event;
  Widget menu = (Widget)clientData;

  if(button_event->button == Button3) {
    XmMenuPosition(menu, button_event);
    XtManageChild(menu);
  }
}

// ---------------------------------------
// addPopupMenuHandler()                  
// ---------------------------------------

void VcView::addPopupMenuHandler(Widget menu, Widget parent)
{
  XtAddEventHandler(parent, ButtonPressMask,
		    False, popupMenuHandler, menu);
}
